// lfsr.sv — generated by atlas rtl-gen
// SSOT: lfsr/yaml/lfsr.ssot.yaml
module lfsr #(
    parameter integer LFSR_WIDTH     = 32,         // Changes the PRBS state and parallel output width.
    parameter integer POLY_DEGREE    = 32,         // SSOT polynomial degree; constrained by integration to LFSR_WIDTH.
    parameter integer APB_ADDR_WIDTH = 8,          // Changes the APB byte-address bus width.
    parameter integer APB_DATA_WIDTH = 32,         // Changes the APB data bus and CSR access width.
    parameter [LFSR_WIDTH-1:0] DEFAULT_POLY = 32'h80000057,
    parameter [LFSR_WIDTH-1:0] DEFAULT_SEED = 32'h00000001,
    parameter integer CLOCK_FREQ_MHZ = 50,
    parameter integer RESET_ACTIVE_LOW = 1
) (
    input  logic                      PCLK,
    input  logic                      PRESETn,
    input  logic [APB_ADDR_WIDTH-1:0] PADDR,
    input  logic                      PSEL,
    input  logic                      PENABLE,
    input  logic                      PWRITE,
    input  logic [APB_DATA_WIDTH-1:0] PWDATA,
    output logic [APB_DATA_WIDTH-1:0] PRDATA,
    output logic                      PREADY,
    output logic                      PSLVERR,
    output logic [LFSR_WIDTH-1:0]     prbs_out,
    output logic                      prbs_bit,
    output logic                      prbs_valid
);
    localparam [APB_ADDR_WIDTH-1:0] ADDR_CTRL   = 8'h00;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_POLY   = 8'h04;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_SEED   = 8'h08;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_STATUS = 8'h0C;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_PRBS   = 8'h10;

    localparam [1:0] IDLE    = 2'd0,
                     RUNNING = 2'd1,
                     LOCKUP  = 2'd2;

    localparam [APB_DATA_WIDTH-1:0] APB_ZERO = {APB_DATA_WIDTH{1'b0}};
    localparam [LFSR_WIDTH-1:0]     LFSR_ZERO = {LFSR_WIDTH{1'b0}};
    // TBD: internal signals
    // TBD: reset / synchronizers
    // TBD: fsm
    // TBD: datapath
    // TBD: output assignments
endmodule
