// lfsr.sv — generated by atlas rtl-gen
// SSOT: lfsr/yaml/lfsr.ssot.yaml
module lfsr (
    input  logic [0:0]                PCLK,
    input  logic [0:0]                PRESETn,
    input  logic [APB_ADDR_WIDTH-1:0] PADDR,
    input  logic                      PSEL,
    input  logic                      PENABLE,
    input  logic                      PWRITE,
    input  logic [31:0]               PWDATA,
    output logic [31:0]               PRDATA,
    output logic                      PREADY,
    output logic                      PSLVERR,
    output logic [31:0]               prbs_out,
    output logic                      prbs_bit,
    output logic                      prbs_valid
);
    localparam integer LFSR_WIDTH = 32;
    localparam integer APB_ADDR_WIDTH = 8;
    localparam integer APB_DATA_WIDTH = 32;
    localparam [LFSR_WIDTH-1:0] DEFAULT_POLY = 32'h80000057;
    localparam [LFSR_WIDTH-1:0] DEFAULT_SEED = 32'h00000001;

    localparam [APB_ADDR_WIDTH-1:0] ADDR_CTRL   = 8'h00;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_POLY   = 8'h04;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_SEED   = 8'h08;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_STATUS = 8'h0C;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_PRBS   = 8'h10;

    localparam [1:0] IDLE    = 2'd0,
                     RUNNING = 2'd1,
                     LOCKUP  = 2'd2;

    localparam [APB_DATA_WIDTH-1:0] APB_ZERO = {APB_DATA_WIDTH{1'b0}};
    localparam [LFSR_WIDTH-1:0]     LFSR_ZERO = {LFSR_WIDTH{1'b0}};
    logic [1:0] state;
    logic [1:0] next_state;

    logic [LFSR_WIDTH-1:0] lfsr_state;
    logic [LFSR_WIDTH-1:0] poly_reg;
    logic [1:0] ctrl_reg;
    logic [1:0] status_reg;

    logic apb_access;
    logic apb_write;
    logic apb_read;
    logic addr_hit_ctrl;
    logic addr_hit_poly;
    logic addr_hit_seed;
    logic addr_hit_status;
    logic addr_hit_prbs;
    logic addr_legal;
    logic poly_write_blocked;
    logic seed_write_pulse;
    logic ctrl_write_pulse;
    logic poly_write_pulse;

    logic feedback_bit;
    logic [LFSR_WIDTH-1:0] feedback_masked_state;
    logic [LFSR_WIDTH-1:0] lfsr_next_state;
    logic lockup_now;
    logic lockup_after_step;
    logic enabled_step;
    logic [APB_DATA_WIDTH-1:0] status_read_data;
    logic [APB_DATA_WIDTH-1:0] prbs_read_data;
    logic [LFSR_WIDTH-1:0] seed_write_value;
    logic [LFSR_WIDTH-1:0] poly_write_value;

    assign apb_access = PSEL & PENABLE;
    assign apb_write  = apb_access & PWRITE;
    assign apb_read   = apb_access & (~PWRITE);

    assign addr_hit_ctrl   = (PADDR == ADDR_CTRL);
    assign addr_hit_poly   = (PADDR == ADDR_POLY);
    assign addr_hit_seed   = (PADDR == ADDR_SEED);
    assign addr_hit_status = (PADDR == ADDR_STATUS);
    assign addr_hit_prbs   = (PADDR == ADDR_PRBS);
    assign addr_legal = addr_hit_ctrl | addr_hit_poly | addr_hit_seed | addr_hit_status | addr_hit_prbs;

    assign poly_write_blocked = apb_write & addr_hit_poly & ctrl_reg[0];
    assign ctrl_write_pulse = apb_write & addr_hit_ctrl;
    assign poly_write_pulse = apb_write & addr_hit_poly & (~ctrl_reg[0]);
    assign seed_write_pulse = apb_write & addr_hit_seed;

    // Fibonacci-form PRBS feedback: XOR-reduce state bits selected by POLY taps.
    assign feedback_masked_state = lfsr_state & poly_reg;
    assign feedback_bit = ^feedback_masked_state;
    assign lfsr_next_state = {feedback_bit, lfsr_state[LFSR_WIDTH-1:1]};
    assign lockup_now = (lfsr_state == LFSR_ZERO);
    assign lockup_after_step = (lfsr_next_state == LFSR_ZERO);
    assign enabled_step = ctrl_reg[0] & (state == RUNNING) & (~lockup_now);
    assign seed_write_value = PWDATA[LFSR_WIDTH-1:0];
    assign poly_write_value = PWDATA[LFSR_WIDTH-1:0];

    assign status_read_data = {{(APB_DATA_WIDTH-2){1'b0}}, status_reg[1], status_reg[0]};
    assign prbs_read_data = {{(APB_DATA_WIDTH-LFSR_WIDTH){1'b0}}, lfsr_state};
    // PRESETn is the sole SSOT reset; all architectural registers return to SSOT reset values.
    always @(posedge PCLK or negedge PRESETn) begin
        if (!PRESETn) begin
            state       <= IDLE;
            lfsr_state  <= DEFAULT_SEED;
            poly_reg    <= DEFAULT_POLY;
            ctrl_reg    <= 2'b00;
            status_reg  <= 2'b00;
            PRDATA      <= {APB_DATA_WIDTH{1'b0}};
            PREADY      <= 1'b0;
            PSLVERR     <= 1'b0;
            prbs_out    <= DEFAULT_SEED;
            prbs_bit    <= DEFAULT_SEED[0];
            prbs_valid  <= 1'b0;
        end else begin
            state <= next_state;
            PREADY <= apb_access;
            PSLVERR <= apb_access & ((~addr_legal) | poly_write_blocked | (apb_write & (addr_hit_status | addr_hit_prbs)));

            if (ctrl_write_pulse) begin
                ctrl_reg <= PWDATA[1:0];
            end

            if (poly_write_pulse) begin
                poly_reg <= poly_write_value;
            end

            if (seed_write_pulse) begin
                lfsr_state <= seed_write_value;
                prbs_out <= seed_write_value;
                prbs_bit <= seed_write_value[0];
                prbs_valid <= 1'b0;
                status_reg[1] <= 1'b0;
            end else if (enabled_step) begin
                if (lockup_after_step) begin
                    lfsr_state <= ctrl_reg[1] ? DEFAULT_SEED : LFSR_ZERO;
                    prbs_out <= ctrl_reg[1] ? DEFAULT_SEED : LFSR_ZERO;
                    prbs_bit <= ctrl_reg[1] ? DEFAULT_SEED[0] : 1'b0;
                    prbs_valid <= 1'b0;
                    status_reg[1] <= 1'b1;
                end else begin
                    lfsr_state <= lfsr_next_state;
                    prbs_out <= lfsr_next_state;
                    prbs_bit <= lfsr_next_state[0];
                    prbs_valid <= 1'b1;
                end
            end else begin
                prbs_out <= lfsr_state;
                prbs_bit <= lfsr_state[0];
                prbs_valid <= 1'b0;
                if (!ctrl_reg[0]) begin
                    status_reg[1] <= 1'b0;
                end
            end

            status_reg[0] <= ctrl_reg[0] & (~status_reg[1]) & (~lockup_now);

            if (apb_read) begin
                case (PADDR)
                    ADDR_CTRL:   PRDATA <= {{(APB_DATA_WIDTH-2){1'b0}}, ctrl_reg[1], ctrl_reg[0]};
                    ADDR_POLY:   PRDATA <= {{(APB_DATA_WIDTH-LFSR_WIDTH){1'b0}}, poly_reg};
                    ADDR_SEED:   PRDATA <= {{(APB_DATA_WIDTH-LFSR_WIDTH){1'b0}}, lfsr_state};
                    ADDR_STATUS: PRDATA <= status_read_data;
                    ADDR_PRBS:   PRDATA <= prbs_read_data;
                    default:     PRDATA <= APB_ZERO;
                endcase
            end else begin
                PRDATA <= APB_ZERO;
            end
        end
    end
    // SSOT lfsr_control FSM separates halted, stepping, and detected lockup behavior.
    always @(*) begin
        next_state = state;
        case (state)
            IDLE: begin
                if (ctrl_reg[0] && (lfsr_state != LFSR_ZERO)) begin
                    next_state = RUNNING;
                end
            end
            RUNNING: begin
                if (!ctrl_reg[0]) begin
                    next_state = IDLE;
                end else if (lockup_now || lockup_after_step) begin
                    next_state = LOCKUP;
                end
            end
            LOCKUP: begin
                if (!ctrl_reg[0]) begin
                    next_state = IDLE;
                end else if (ctrl_reg[1]) begin
                    next_state = RUNNING;
                end
            end
            default: begin
                next_state = IDLE;
            end
        endcase
    end
    // APB-lite is single-cycle ready in the completing access phase; unsupported accesses raise PSLVERR.
    // POLY writes are accepted only while halted, matching the SSOT polynomial programming rule.
    // SEED writes directly load lfsr_state and suppress prbs_valid for the load cycle.
    // PRBS output has no backpressure; prbs_valid marks cycles where prbs_out/prbs_bit advanced.
    // Outputs are registered in the sequential block so APB read data and PRBS status are stable after PCLK.
endmodule
