# Makefile for quad_spi_ctrl cocotb simulation
export PATH := /Users/brian/Library/Python/3.9/bin:$(PATH)

# Work around broken cocotb-config shebang
include $(shell cocotb-config --makefiles)/Makefile.sim
