#!/usr/bin/env python3
"""run_fp.py — Port of run_fp.sh. Floorplan stage. Single OpenROAD invocation.

Args: <ip>
Reads: scan.v|synth.v + SDC + LEFs. Writes: <ip>/pnr/out/floorplan.def.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _pnr_common as common  # noqa: E402


# Inline python heredoc from run_fp.sh: pull floorplan params from SSOT.
_FP_PARAMS_PY = r"""
import sys, pathlib
try:
    import yaml; d = yaml.safe_load(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace")) or {}
except Exception: d = {}
p = d.get("pnr", {}) or {}
io = p.get("io_layers", {}) or {}
print(int(p.get("utilization_pct", 60)),
      float(p.get("aspect_ratio", 1.0)),
      float(p.get("core_space_um", 2.0)),
      io.get("horizontal", "met3"),
      io.get("vertical",   "met2"))
"""


def main(argv: "list[str]") -> int:
    argv = common.argv_from_hook(argv)
    common.load_pdk_env(os.environ)

    ip = argv[0] if argv else ""
    if not ip:
        print("[PNR] usage: run_fp.sh <ip>", file=sys.stderr)
        return 2
    if not Path(ip).is_dir():
        print(f"[PNR] no such IP dir: {ip}", file=sys.stderr)
        return 2

    rc = common.check_tools()
    if rc != 0:
        return rc
    netlist, rc = common.check_handoff(ip)
    if rc != 0:
        return rc
    top = common.top_from_ssot(ip)
    sdc = f"{ip}/sta/out/{ip}.sdc"
    tcl = f"{ip}/pnr/tcl/floorplan.tcl"
    deff = f"{ip}/pnr/out/floorplan.def"
    log = f"{ip}/pnr/out/pnr.log"
    Path(f"{ip}/pnr/tcl").mkdir(parents=True, exist_ok=True)
    Path(f"{ip}/pnr/out").mkdir(parents=True, exist_ok=True)

    proc = common.run_embedded_py(_FP_PARAMS_PY, [f"{ip}/yaml/{ip}.ssot.yaml"], capture=True)
    util, ar, cspace, hor, ver = proc.stdout.split()

    rc = common.check_io_layers(hor, ver)
    if rc != 0:
        return rc

    tlef = os.environ["SKY130_TLEF"]
    lef = os.environ["SKY130_LEF"]
    lib = os.environ["SKY130_LIB"]
    tcl_text = (
        "# Generated by workflow/pnr/scripts/run_fp.sh\n"
        f"read_lef {tlef}\n"
        f"read_lef {lef}\n"
        f"read_liberty {lib}\n"
        f"read_verilog {netlist}\n"
        f"link_design {top}\n"
        f"read_sdc {sdc}\n"
        "\n"
        "# DFT-aware: tie scan_en low so functional-mode timing drives placement.\n"
        "if {[llength [info commands get_ports]] && ![catch {get_ports scan_en}]} {\n"
        "  set_case_analysis 0 [get_ports scan_en]\n"
        "}\n"
        "\n"
        f"initialize_floorplan -utilization {util} -aspect_ratio {ar} \\\n"
        f"  -core_space {cspace} -site unithd\n"
        "\n"
        "# Routing tracks per metal layer — required by place_pins / global_route.\n"
        "# ORFS sky130hd platform tracks; falls back to no-op if file absent.\n"
        "if {[file exists $::env(SKY130_TRACKS)]} {\n"
        "  source $::env(SKY130_TRACKS)\n"
        "}\n"
        "\n"
        f"place_pins -hor_layers {hor} -ver_layers {ver}\n"
        f"write_def {deff}\n"
        "report_design_area\n"
        "exit\n"
    )
    Path(tcl).write_text(tcl_text, encoding="utf-8")

    print(f"[PNR-FP] openroad → {deff}  (util={util}% AR={ar})")
    rc = common.run_openroad_tee(tcl, log)
    if rc != 0 or not (Path(deff).is_file() and Path(deff).stat().st_size > 0):
        print(f"[PNR-FP] FAILED rc={rc}", file=sys.stderr)
        return rc
    print(f"[PNR-FP HANDOFF] {deff} ready — run /pnr-place")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
