// arbiter_rr_core.sv — round-robin arbitration core generated by atlas rtl-gen
module arbiter_rr_core #(
    parameter integer NUM_REQ = 4,
    parameter integer IDX_WIDTH = 2
) (
    input  logic                     clk_i,
    input  logic                     rst_ni,
    input  logic [NUM_REQ-1:0]       req_i,
    input  logic [NUM_REQ-1:0]       mask_i,
    input  logic                     enable_i,
    output logic [NUM_REQ-1:0]       gnt_o,
    output logic                     gnt_valid_o,
    output logic [IDX_WIDTH-1:0]     gnt_idx_o,
    output logic [NUM_REQ-1:0]       winner_oh_o,
    output logic [NUM_REQ-1:0]       active_req_o
);
    localparam [1:0] IDLE  = 2'd0,
                     EVAL  = 2'd1,
                     GRANT = 2'd2;

    localparam [IDX_WIDTH-1:0] IDX_0 = 0;
    localparam [IDX_WIDTH-1:0] IDX_1 = 1;
    localparam [IDX_WIDTH-1:0] IDX_2 = 2;
    localparam [IDX_WIDTH-1:0] IDX_3 = 3;

    logic [1:0]                 state;
    logic [1:0]                 next_state;
    logic [NUM_REQ-1:0]         req_masked_now;
    logic [NUM_REQ-1:0]         req_masked_q;
    logic [IDX_WIDTH-1:0]       last_winner;
    logic [NUM_REQ-1:0]         selected_oh;
    logic [IDX_WIDTH-1:0]       selected_index;
    logic                       selected_valid;
    logic [NUM_REQ-1:0]         last_winner_oh;
    logic                       arb_enabled;

    assign arb_enabled = enable_i;
    assign req_masked_now = req_i & mask_i;
    assign active_req_o = req_masked_now;
    assign winner_oh_o = last_winner_oh;

    // Conceptual IDLE/EVAL/GRANT states mirror the SSOT FSM while outputs use the 1-stage pipeline.
    always @(*) begin
        next_state = state;
        case (state)
            IDLE: begin
                if (arb_enabled & (req_masked_now != {NUM_REQ{1'b0}})) begin
                    next_state = EVAL;
                end else begin
                    next_state = IDLE;
                end
            end
            EVAL: begin
                next_state = GRANT;
            end
            GRANT: begin
                next_state = IDLE;
            end
            default: begin
                next_state = IDLE;
            end
        endcase
    end

    // Circular priority scan for four requestors: last_winner+1 is checked first.
    always @(*) begin
        selected_oh = {NUM_REQ{1'b0}};
        selected_index = IDX_0;
        selected_valid = 1'b0;
        case (last_winner)
            IDX_0: begin
                if (req_masked_q[1]) begin
                    selected_oh[1] = 1'b1;
                    selected_index = IDX_1;
                    selected_valid = 1'b1;
                end else if (req_masked_q[2]) begin
                    selected_oh[2] = 1'b1;
                    selected_index = IDX_2;
                    selected_valid = 1'b1;
                end else if (req_masked_q[3]) begin
                    selected_oh[3] = 1'b1;
                    selected_index = IDX_3;
                    selected_valid = 1'b1;
                end else if (req_masked_q[0]) begin
                    selected_oh[0] = 1'b1;
                    selected_index = IDX_0;
                    selected_valid = 1'b1;
                end
            end
            IDX_1: begin
                if (req_masked_q[2]) begin
                    selected_oh[2] = 1'b1;
                    selected_index = IDX_2;
                    selected_valid = 1'b1;
                end else if (req_masked_q[3]) begin
                    selected_oh[3] = 1'b1;
                    selected_index = IDX_3;
                    selected_valid = 1'b1;
                end else if (req_masked_q[0]) begin
                    selected_oh[0] = 1'b1;
                    selected_index = IDX_0;
                    selected_valid = 1'b1;
                end else if (req_masked_q[1]) begin
                    selected_oh[1] = 1'b1;
                    selected_index = IDX_1;
                    selected_valid = 1'b1;
                end
            end
            IDX_2: begin
                if (req_masked_q[3]) begin
                    selected_oh[3] = 1'b1;
                    selected_index = IDX_3;
                    selected_valid = 1'b1;
                end else if (req_masked_q[0]) begin
                    selected_oh[0] = 1'b1;
                    selected_index = IDX_0;
                    selected_valid = 1'b1;
                end else if (req_masked_q[1]) begin
                    selected_oh[1] = 1'b1;
                    selected_index = IDX_1;
                    selected_valid = 1'b1;
                end else if (req_masked_q[2]) begin
                    selected_oh[2] = 1'b1;
                    selected_index = IDX_2;
                    selected_valid = 1'b1;
                end
            end
            default: begin
                if (req_masked_q[0]) begin
                    selected_oh[0] = 1'b1;
                    selected_index = IDX_0;
                    selected_valid = 1'b1;
                end else if (req_masked_q[1]) begin
                    selected_oh[1] = 1'b1;
                    selected_index = IDX_1;
                    selected_valid = 1'b1;
                end else if (req_masked_q[2]) begin
                    selected_oh[2] = 1'b1;
                    selected_index = IDX_2;
                    selected_valid = 1'b1;
                end else if (req_masked_q[3]) begin
                    selected_oh[3] = 1'b1;
                    selected_index = IDX_3;
                    selected_valid = 1'b1;
                end
            end
        endcase
    end

    // STATUS.winner exposes the last granted requestor as one-hot for the CSR block.
    always @(*) begin
        last_winner_oh = {NUM_REQ{1'b0}};
        case (last_winner)
            IDX_0: last_winner_oh[0] = 1'b1;
            IDX_1: last_winner_oh[1] = 1'b1;
            IDX_2: last_winner_oh[2] = 1'b1;
            IDX_3: last_winner_oh[3] = 1'b1;
            default: last_winner_oh[0] = 1'b1;
        endcase
    end

    // S0 samples requests; S1 registers grant and rotates last_winner on valid grants.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            state <= IDLE;
            req_masked_q <= {NUM_REQ{1'b0}};
            last_winner <= IDX_0;
            gnt_o <= {NUM_REQ{1'b0}};
            gnt_valid_o <= 1'b0;
            gnt_idx_o <= IDX_0;
        end else begin
            state <= next_state;
            if (arb_enabled) begin
                req_masked_q <= req_masked_now;
                // For latency-1, compute the registered grant from the current accepted request vector.
                if (req_masked_now != {NUM_REQ{1'b0}}) begin
                    if ((last_winner == IDX_0) && req_masked_now[1]) begin
                        gnt_o <= 4'b0010;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_1;
                        last_winner <= IDX_1;
                    end else if ((last_winner == IDX_0) && req_masked_now[2]) begin
                        gnt_o <= 4'b0100;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_2;
                        last_winner <= IDX_2;
                    end else if ((last_winner == IDX_0) && req_masked_now[3]) begin
                        gnt_o <= 4'b1000;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_3;
                        last_winner <= IDX_3;
                    end else if ((last_winner == IDX_0) && req_masked_now[0]) begin
                        gnt_o <= 4'b0001;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_0;
                        last_winner <= IDX_0;
                    end else if ((last_winner == IDX_1) && req_masked_now[2]) begin
                        gnt_o <= 4'b0100;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_2;
                        last_winner <= IDX_2;
                    end else if ((last_winner == IDX_1) && req_masked_now[3]) begin
                        gnt_o <= 4'b1000;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_3;
                        last_winner <= IDX_3;
                    end else if ((last_winner == IDX_1) && req_masked_now[0]) begin
                        gnt_o <= 4'b0001;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_0;
                        last_winner <= IDX_0;
                    end else if ((last_winner == IDX_1) && req_masked_now[1]) begin
                        gnt_o <= 4'b0010;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_1;
                        last_winner <= IDX_1;
                    end else if ((last_winner == IDX_2) && req_masked_now[3]) begin
                        gnt_o <= 4'b1000;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_3;
                        last_winner <= IDX_3;
                    end else if ((last_winner == IDX_2) && req_masked_now[0]) begin
                        gnt_o <= 4'b0001;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_0;
                        last_winner <= IDX_0;
                    end else if ((last_winner == IDX_2) && req_masked_now[1]) begin
                        gnt_o <= 4'b0010;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_1;
                        last_winner <= IDX_1;
                    end else if ((last_winner == IDX_2) && req_masked_now[2]) begin
                        gnt_o <= 4'b0100;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_2;
                        last_winner <= IDX_2;
                    end else if (req_masked_now[0]) begin
                        gnt_o <= 4'b0001;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_0;
                        last_winner <= IDX_0;
                    end else if (req_masked_now[1]) begin
                        gnt_o <= 4'b0010;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_1;
                        last_winner <= IDX_1;
                    end else if (req_masked_now[2]) begin
                        gnt_o <= 4'b0100;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_2;
                        last_winner <= IDX_2;
                    end else begin
                        gnt_o <= 4'b1000;
                        gnt_valid_o <= 1'b1;
                        gnt_idx_o <= IDX_3;
                        last_winner <= IDX_3;
                    end
                end else begin
                    gnt_o <= {NUM_REQ{1'b0}};
                    gnt_valid_o <= 1'b0;
                    gnt_idx_o <= IDX_0;
                end
            end else begin
                req_masked_q <= {NUM_REQ{1'b0}};
                gnt_o <= {NUM_REQ{1'b0}};
                gnt_valid_o <= 1'b0;
                gnt_idx_o <= IDX_0;
            end
        end
    end

endmodule
