// arbiter_rr_param.vh — shared CSR constants generated by atlas rtl-gen
// SSOT: registers.register_list offsets and reset values for arbiter_rr.
`ifndef ARBITER_RR_PARAM_VH
`define ARBITER_RR_PARAM_VH

localparam [7:0] ARBITER_RR_CTRL_ADDR     = 8'h00;
localparam [7:0] ARBITER_RR_REQ_MASK_ADDR = 8'h04;
localparam [7:0] ARBITER_RR_STATUS_ADDR   = 8'h08;

localparam [31:0] ARBITER_RR_CTRL_RESET     = 32'h00000001;
localparam [31:0] ARBITER_RR_REQ_MASK_RESET = 32'h0000000F;

`endif
