// arbiter_rr_regs.sv — APB-lite CSR block generated by atlas rtl-gen
module arbiter_rr_regs #(
    parameter integer NUM_REQ = 4,
    parameter integer APB_ADDR_WIDTH = 8,
    parameter integer APB_DATA_WIDTH = 32
) (
    input  logic                       PCLK,
    input  logic                       PRESETn,
    input  logic [APB_ADDR_WIDTH-1:0]  PADDR,
    input  logic                       PSEL,
    input  logic                       PENABLE,
    input  logic                       PWRITE,
    input  logic [APB_DATA_WIDTH-1:0]  PWDATA,
    output logic [APB_DATA_WIDTH-1:0]  PRDATA,
    output logic                       PREADY,
    output logic                       PSLVERR,
    output logic                       enable_o,
    output logic [NUM_REQ-1:0]         mask_o,
    input  logic [NUM_REQ-1:0]         winner_oh_i,
    input  logic [NUM_REQ-1:0]         active_req_i
);
    `include "arbiter_rr_param.vh"

    localparam integer CTRL_ENABLE_BIT = 0;

    logic [APB_DATA_WIDTH-1:0] ctrl_reg;
    logic [NUM_REQ-1:0]        req_mask_reg;
    logic                      apb_access;
    logic                      apb_write;
    logic                      apb_read;
    logic                      addr_ctrl;
    logic                      addr_req_mask;
    logic                      addr_status;
    logic                      addr_legal;
    logic [APB_DATA_WIDTH-1:0] status_value;
    logic [APB_DATA_WIDTH-1:0] req_mask_read_value;
    logic [APB_DATA_WIDTH-1:0] ctrl_reset_value;
    logic [NUM_REQ-1:0]        req_mask_reset_value;
    logic [NUM_REQ-1:0]        req_mask_write_value;
    logic [APB_DATA_WIDTH-1:0] prdata_next;

    // APB-lite transfers complete in one access cycle per cycle_model register latency.
    assign apb_access = PSEL & PENABLE;
    assign apb_write  = apb_access & PWRITE;
    assign apb_read   = apb_access & (~PWRITE);

    assign addr_ctrl     = (PADDR == ARBITER_RR_CTRL_ADDR[APB_ADDR_WIDTH-1:0]);
    assign addr_req_mask = (PADDR == ARBITER_RR_REQ_MASK_ADDR[APB_ADDR_WIDTH-1:0]);
    assign addr_status   = (PADDR == ARBITER_RR_STATUS_ADDR[APB_ADDR_WIDTH-1:0]);
    assign addr_legal    = addr_ctrl | addr_req_mask | addr_status;

    assign PREADY  = apb_access;
    assign PSLVERR = apb_access & (~addr_legal);
    assign enable_o = ctrl_reg[CTRL_ENABLE_BIT];
    assign mask_o = req_mask_reg;

    // Parameter-derived slices stay outside procedural blocks for portable Icarus lint.
    assign status_value = {{(APB_DATA_WIDTH-(NUM_REQ+NUM_REQ)){1'b0}}, active_req_i, winner_oh_i};
    assign req_mask_read_value = {{(APB_DATA_WIDTH-NUM_REQ){1'b0}}, req_mask_reg};
    assign ctrl_reset_value = ARBITER_RR_CTRL_RESET;
    assign req_mask_reset_value = ARBITER_RR_REQ_MASK_RESET[NUM_REQ-1:0];
    assign req_mask_write_value = PWDATA[NUM_REQ-1:0];

    // Reserved fields read as zero; undefined offsets return zero with PSLVERR.
    always @(*) begin
        prdata_next = {APB_DATA_WIDTH{1'b0}};
        if (addr_ctrl) begin
            prdata_next[CTRL_ENABLE_BIT] = ctrl_reg[CTRL_ENABLE_BIT];
        end else if (addr_req_mask) begin
            prdata_next = req_mask_read_value;
        end else if (addr_status) begin
            prdata_next = status_value;
        end else begin
            prdata_next = {APB_DATA_WIDTH{1'b0}};
        end
    end

    always @(posedge PCLK or negedge PRESETn) begin
        if (!PRESETn) begin
            ctrl_reg <= ctrl_reset_value;
            req_mask_reg <= req_mask_reset_value;
            PRDATA <= {APB_DATA_WIDTH{1'b0}};
        end else begin
            if (apb_write & addr_ctrl) begin
                ctrl_reg[CTRL_ENABLE_BIT] <= PWDATA[CTRL_ENABLE_BIT];
            end
            if (apb_write & addr_req_mask) begin
                req_mask_reg <= req_mask_write_value;
            end
            if (apb_read) begin
                PRDATA <= prdata_next;
            end else begin
                PRDATA <= {APB_DATA_WIDTH{1'b0}};
            end
        end
    end

endmodule
