// arbiter_rr.sv — top-level integration generated by atlas rtl-gen
module arbiter_rr #(
    parameter integer NUM_REQ = 4,
    parameter integer IDX_WIDTH = 2,
    parameter integer APB_ADDR_WIDTH = 8,
    parameter integer APB_DATA_WIDTH = 32
) (
    input  logic                       PCLK,
    input  logic                       PRESETn,
    input  logic [APB_ADDR_WIDTH-1:0]  PADDR,
    input  logic                       PSEL,
    input  logic                       PENABLE,
    input  logic                       PWRITE,
    input  logic [APB_DATA_WIDTH-1:0]  PWDATA,
    output logic [APB_DATA_WIDTH-1:0]  PRDATA,
    output logic                       PREADY,
    output logic                       PSLVERR,
    input  logic [NUM_REQ-1:0]         req_i,
    output logic [NUM_REQ-1:0]         gnt_o,
    output logic                       gnt_valid_o,
    output logic [IDX_WIDTH-1:0]       gnt_idx_o
);
    logic                      arb_enable;
    logic [NUM_REQ-1:0]        req_mask;
    logic [NUM_REQ-1:0]        status_winner;
    logic [NUM_REQ-1:0]        status_active_req;

    // CSR block owns CTRL/REQ_MASK/STATUS and APB-lite illegal-offset response.
    arbiter_rr_regs #(
        .NUM_REQ(NUM_REQ),
        .APB_ADDR_WIDTH(APB_ADDR_WIDTH),
        .APB_DATA_WIDTH(APB_DATA_WIDTH)
    ) u_regs (
        .PCLK(PCLK),
        .PRESETn(PRESETn),
        .PADDR(PADDR),
        .PSEL(PSEL),
        .PENABLE(PENABLE),
        .PWRITE(PWRITE),
        .PWDATA(PWDATA),
        .PRDATA(PRDATA),
        .PREADY(PREADY),
        .PSLVERR(PSLVERR),
        .enable_o(arb_enable),
        .mask_o(req_mask),
        .winner_oh_i(status_winner),
        .active_req_i(status_active_req)
    );

    // Arbitration core implements FM1/FM2 grant rules and cycle_model one-stage grant pipeline.
    arbiter_rr_core #(
        .NUM_REQ(NUM_REQ),
        .IDX_WIDTH(IDX_WIDTH)
    ) u_core (
        .clk_i(PCLK),
        .rst_ni(PRESETn),
        .req_i(req_i),
        .mask_i(req_mask),
        .enable_i(arb_enable),
        .gnt_o(gnt_o),
        .gnt_valid_o(gnt_valid_o),
        .gnt_idx_o(gnt_idx_o),
        .winner_oh_o(status_winner),
        .active_req_o(status_active_req)
    );

endmodule
