#!/usr/bin/env python3
"""run_openroad.py — OpenROAD floorplan + global placement + STA.

Python port of run_openroad.sh for native-Windows portability. Same CLI, exit
codes, generated TCL, and ``openroad -no_init -exit <tcl>`` invocation.

Usage:
  run_openroad.py <ip> [--root .]

Inputs:
  <ip>/syn/<ip>.netlist.v      from yosys (sky130-mapped)
  <ip>/sdc/<ip>.sdc            from emit_sdc.py

Outputs:
  <ip>/pnr/<ip>.def            placed DEF
  <ip>/pnr/openroad.log        full openroad log
  <ip>/pnr/pnr_report.txt      summary (area, slack, util)

Exit codes: 2 usage/bad flag, 1 missing PDK / netlist / SDC / OpenROAD failed.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


def _parse_args(argv: list[str]) -> tuple[str, str] | int:
    ip = ""
    root = "."
    i = 0
    n = len(argv)
    while i < n:
        arg = argv[i]
        if arg == "--root":
            root = argv[i + 1] if i + 1 < n else ""
            i += 2
        elif arg.startswith("-"):
            print(f"[run_openroad] unknown flag: {arg}", file=sys.stderr)
            return 2
        else:
            ip = arg
            i += 1
    return ip, root


def _detect_top(ip_dir: Path, ip: str) -> str:
    try:
        import yaml

        with open(ip_dir / "yaml" / f"{ip}.ssot.yaml", encoding="utf-8") as handle:
            d = yaml.safe_load(handle)
        for sm in d.get("sub_modules") or []:
            if isinstance(sm, dict) and sm.get("wiring_only"):
                nm = (
                    (sm.get("file") or "")
                    .split("/")[-1]
                    .replace(".sv", "")
                    .replace(".v", "")
                )
                if nm:
                    return nm
        return str((d.get("top_module") or {}).get("name") or ip)
    except Exception:
        return ""


def _tail(text: str, n: int) -> str:
    lines = text.splitlines(keepends=True)
    return "".join(lines[-n:])


def main(argv: list[str]) -> int:
    parsed = _parse_args(argv)
    if isinstance(parsed, int):
        return parsed
    ip, root = parsed

    if not ip:
        print("usage: run_openroad.sh <ip> [--root .]", file=sys.stderr)
        return 2
    try:
        root = str(Path(root).resolve(strict=True))
    except OSError:
        print(f"usage: run_openroad.sh <ip> [--root .]", file=sys.stderr)
        return 2
    ip_dir = Path(root) / ip

    pdk = Path(os.path.expanduser("~")) / "src" / "OpenROAD" / "test" / "sky130hd"
    liberty = pdk / "sky130_fd_sc_hd__tt_025C_1v80.lib"
    tech_lef = pdk / "sky130_fd_sc_hd__nom.tlef"
    cells_lef = pdk / "sky130_fd_sc_hd_merged.lef"

    for f in (liberty, tech_lef, cells_lef):
        if not f.is_file():
            print(f"[run_openroad] missing PDK file: {f}", file=sys.stderr)
            return 1

    netlist = ip_dir / "syn" / f"{ip}.netlist.v"
    sdc = ip_dir / "sdc" / f"{ip}.sdc"
    if not netlist.is_file():
        print(
            f"[run_openroad] missing netlist: {netlist}. Run run_synth.sh first.",
            file=sys.stderr,
        )
        return 1
    if not sdc.is_file():
        print(
            f"[run_openroad] missing SDC: {sdc}. Run emit_sdc.py first.",
            file=sys.stderr,
        )
        return 1

    top = _detect_top(ip_dir, ip)
    if not top:
        top = f"{ip}_wrapper"

    pnr_dir = ip_dir / "pnr"
    pnr_dir.mkdir(parents=True, exist_ok=True)
    tcl = pnr_dir / "openroad_run.tcl"
    log = pnr_dir / "openroad.log"
    report = pnr_dir / "pnr_report.txt"
    def_out = pnr_dir / f"{ip}.def"

    tcl_text = f"""# OpenROAD flow auto-generated by run_openroad.sh
read_liberty {liberty}
read_lef {tech_lef}
read_lef {cells_lef}
read_verilog {netlist}
link_design {top}
read_sdc {sdc}

# ── Floorplan ────────────────────────────────────────────────
# Aspect ratio 1, utilization 50%, sky130hd unit_hd site
initialize_floorplan \\
    -utilization 15 \\
    -aspect_ratio 1.0 \\
    -core_space 20 \\
    -site unithd

source {pdk}/sky130hd.tracks

# Routing layers must be declared before place_pins picks legal positions.
set_routing_layers -signal met1-met5

# Pin placement on the die boundary so global_placement can route to them.
puts "─── Pin placement ──────────────────────────────"
place_pins -hor_layers met3 -ver_layers met2

puts "─── Floorplan ──────────────────────────────────"
report_design_area

# ── Power planning (basic strap grid) ────────────────────────
# Skip full PDN for this PoC — OpenROAD pdngen requires a config file.
# Without PDN, routing won't be meaningful, but placement and STA work.

# ── Placement ────────────────────────────────────────────────
puts "─── Global placement ───────────────────────────"
global_placement -density 0.6 -pad_left 1 -pad_right 1

puts "─── Detailed placement ─────────────────────────"
detailed_placement
check_placement -verbose

puts "─── Post-placement timing ──────────────────────"
estimate_parasitics -placement
report_worst_slack -max
report_worst_slack -min
report_tns
report_wns
report_design_area

# Save the placed DEF
write_def {def_out}
puts "DEF: placed DEF written to {def_out}"

exit
"""
    tcl.write_text(tcl_text, encoding="utf-8")

    print("[run_openroad] PDK: sky130hd typical corner")
    print(f"[run_openroad] top: {top}")
    print(
        "[run_openroad] running OpenROAD "
        "(floorplan + global + detailed placement + STA)..."
    )

    proc = subprocess.run(
        ["openroad", "-no_init", "-exit", str(tcl)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    combined = proc.stdout or ""
    log.write_text(combined, encoding="utf-8")
    report.write_text(_tail(combined, 120), encoding="utf-8")

    if proc.returncode == 0:
        print("")
        print("[run_openroad] === SUMMARY ===")
        pat = re.compile(
            r"Design area|Util|worst slack|tns max|wns max|placement violations"
        )
        hits = [ln for ln in combined.splitlines() if pat.search(ln)]
        for ln in hits[-20:]:
            print(ln)
        print("")
        print("[run_openroad] OK")
        print(f"[run_openroad]   def:    {def_out}")
        print(f"[run_openroad]   log:    {log}")
        print(f"[run_openroad]   report: {report}")
        return 0

    print(f"[run_openroad] OpenROAD failed — see {log}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
