#!/usr/bin/env bash
# write_yosys_script.sh — Generate <ip>/syn/run.ys from SSOT yaml + filelist.
# Args: <ip_name>
# Reads:  <ip>/yaml/<ip>.ssot.yaml (top_module), <ip>/list/<ip>.f (rtl files)
# Writes: <ip>/syn/run.ys
set -uo pipefail

PDK_ENV="$(cd "$(dirname "$0")/../.." && pwd -P)/scripts/pdk_env.sh"
[ -f "${PDK_ENV}" ] && source "${PDK_ENV}"

IP="${1:-}"
if [ -z "${IP}" ]; then echo "[SYN] usage: write_yosys_script.sh <ip_name>" >&2; exit 2; fi

SSOT="${IP}/yaml/${IP}.ssot.yaml"
FLIST="${IP}/list/${IP}.f"
SCRIPT="${IP}/syn/run.ys"

if [ ! -f "${SSOT}" ]; then echo "[SYN] missing SSOT: ${SSOT}" >&2; exit 2; fi
if [ ! -f "${FLIST}" ]; then echo "[SYN] missing filelist: ${FLIST}" >&2; exit 2; fi

# Extract top_module from SSOT (look for 'top_module:' or 'top:' line).
TOP=$(grep -E "^[[:space:]]*(top_module|top)[[:space:]]*:" "${SSOT}" | head -1 \
  | sed -E 's/^[[:space:]]*(top_module|top)[[:space:]]*:[[:space:]]*//; s/[\"'\'']//g; s/[[:space:]]+$//')
if [ -z "${TOP}" ]; then TOP="${IP}"; fi

# yosys script-mode does not expand TCL env vars in -liberty arguments —
# substitute the absolute path at script-write time.
LIB="${SKY130_LIB:-}"

mkdir -p "${IP}/syn" "${IP}/syn/out"

{
  echo "# Generated by workflow/syn/scripts/write_yosys_script.sh"
  echo "# IP: ${IP}   top: ${TOP}   corner: ${LIB}"
  echo "read_liberty -lib ${LIB}"
  while IFS= read -r line; do
    line="${line%%#*}"               # strip trailing comments
    line="$(echo "$line" | sed -e 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [ -z "${line}" ] && continue
    case "${line}" in
      +*|-*) continue ;;             # skip +incdir / -y style lines for now
    esac
    echo "read_verilog -sv ${line}"
  done < "${FLIST}"
  echo "hierarchy -check -top ${TOP}"
  echo "synth -top ${TOP}"
  echo "dfflibmap -liberty ${LIB}"
  echo "abc -liberty ${LIB}"
  echo "opt_clean -purge"
  echo "write_verilog -noattr ${IP}/syn/out/synth.v"
  echo "stat -liberty ${LIB}"
} > "${SCRIPT}"

echo "[SYN] wrote ${SCRIPT} (top=${TOP})"
