#!/usr/bin/env python3
"""write_yosys_script.py — Generate <ip>/syn/run.ys from SSOT yaml + filelist.

Python port of write_yosys_script.sh for native-Windows portability. Same CLI,
exit codes, and byte-identical run.ys output.

Args: <ip_name>
Reads:  <ip>/yaml/<ip>.ssot.yaml (top_module), <ip>/list/<ip>.f (rtl files)
Writes: <ip>/syn/run.ys

Falls back to HOOK_CMD_ARGS for the IP name when no positional arg is given
(matching the shell original). Sources pdk_env semantics via pdk_env.py so the
SKY130_LIB default resolves identically to ``source pdk_env.sh``.

Exit codes: 2 usage/missing inputs, 4 PDK liberty unreadable.
"""

from __future__ import annotations

import os
import shlex
import sys
from pathlib import Path

# Import the pdk_env port (workflow/scripts/pdk_env.py) for SKY130_LIB resolution.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "scripts"))
import pdk_env  # noqa: E402


def _resolve_ip(argv: list[str]) -> str:
    args = list(argv)
    if not args and os.environ.get("HOOK_CMD_ARGS", ""):
        args = shlex.split(os.environ["HOOK_CMD_ARGS"])
    return args[0] if args else ""


def _q(path: object) -> str:
    return '"' + str(path).replace("\\", "/").replace('"', '\\"') + '"'


def main(argv: list[str]) -> int:
    ip = _resolve_ip(argv)
    if not ip:
        print("[SYN] usage: write_yosys_script.sh <ip_name>", file=sys.stderr)
        return 2

    # `[ -f "${PDK_ENV}" ] && source "${PDK_ENV}"` — apply pdk env to os.environ.
    pdk_env.apply_pdk_env(os.environ)

    ssot_path = Path(ip) / "yaml" / f"{ip}.ssot.yaml"
    flist_path = Path(ip) / "list" / f"{ip}.f"
    script_path = Path(ip) / "syn" / "run.ys"

    if not ssot_path.is_file():
        print(f"[SYN] missing SSOT: {ssot_path}", file=sys.stderr)
        return 2
    if not flist_path.is_file():
        print(f"[SYN] missing filelist: {flist_path}", file=sys.stderr)
        return 2

    lib = os.environ.get("SKY130_LIB", "")
    if not lib or not os.access(lib, os.R_OK):
        print(f"[SYN MISSING PDK] $SKY130_LIB unreadable: {lib}", file=sys.stderr)
        return 4

    Path(ip, "syn").mkdir(parents=True, exist_ok=True)
    Path(ip, "syn", "out").mkdir(parents=True, exist_ok=True)

    try:
        import yaml
    except Exception as exc:  # pragma: no cover - PyYAML present in this repo
        print(f"[SYN] PyYAML required to read SSOT: {exc}", file=sys.stderr)
        return 2

    ip_dir = Path(ip)
    ssot = ssot_path
    flist = flist_path
    script = script_path
    lib_path = Path(lib).resolve(strict=False)

    doc = yaml.safe_load(ssot.read_text(encoding="utf-8", errors="replace")) or {}
    top_raw = doc.get("top_module") or doc.get("top")
    if isinstance(top_raw, dict):
        top = str(top_raw.get("name") or top_raw.get("module") or "").strip()
    elif top_raw is None:
        top = ""
    else:
        top = str(top_raw).strip()
    top = top or ip_dir.name

    missing: list[str] = []
    rtl_files: list[Path] = []
    incdirs: list[Path] = []
    for raw in flist.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.split("//", 1)[0].split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("+incdir+"):
            inc = line[len("+incdir+"):]
            p = Path(inc)
            incdirs.append(p if p.is_absolute() else (ip_dir / p).resolve(strict=False))
            continue
        if line.startswith("-"):
            continue
        if not line.endswith((".v", ".sv", ".vh", ".svh")):
            continue
        p = Path(line)
        candidates = [p] if p.is_absolute() else [ip_dir / p, Path.cwd() / p]
        hit = next((c for c in candidates if c.is_file()), None)
        if hit is None:
            missing.append(line)
        else:
            rtl_files.append(hit.resolve(strict=False))

    if missing:
        print("[SYN] missing RTL filelist entries:", file=sys.stderr)
        for item in missing:
            print(f"  - {item}", file=sys.stderr)
        return 2
    if not rtl_files:
        print(f"[SYN] no RTL files found in {flist}", file=sys.stderr)
        return 2

    out_netlist = (ip_dir / "syn" / "out" / "synth.v").resolve(strict=False)
    lines = [
        "# Generated by workflow/syn/scripts/write_yosys_script.sh",
        f"# IP: {ip_dir.name}   top: {top}   corner: {lib_path}",
        f"read_liberty -lib {_q(lib_path)}",
    ]
    for inc in incdirs:
        lines.append(f"verilog_defaults -add -I{_q(inc)}")
    for path in rtl_files:
        lines.append(f"read_verilog -sv {_q(path)}")
    lines.extend(
        [
            f"hierarchy -check -top {top}",
            f"synth -top {top}",
            f"dfflibmap -liberty {_q(lib_path)}",
            f"abc -liberty {_q(lib_path)}",
            "opt_clean -purge",
            f"write_verilog -noattr {_q(out_netlist)}",
            f"stat -liberty {_q(lib_path)}",
        ]
    )
    script.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"[SYN] wrote {script} (top={top}, rtl_files={len(rtl_files)}, lib={lib_path})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
