// parity_gen_core.sv — generated by atlas rtl-gen from parity_gen SSOT
module parity_gen_core #(
    parameter integer DATA_WIDTH = 32  // Width of data_in covered by the XOR parity reduction.
) (
    input  logic                  PCLK,
    input  logic                  PRESETn,
    input  logic [DATA_WIDTH-1:0] data_in,
    input  logic                  enable,
    input  logic                  check_enable,
    input  logic                  expected_parity,
    output logic                  parity_out,
    output logic                  parity_error,
    output logic                  parity_mismatch_comb
);

    logic sampled_parity;

    // SSOT FM_GEN/FM_CHK: even parity is the XOR reduction of the sampled data word.
    always @(*) begin
        sampled_parity = ^data_in;
        parity_mismatch_comb = sampled_parity ^ expected_parity;
    end

    // SSOT cycle_model latency: registered outputs update one PCLK after the stable input/control cycle.
    always @(posedge PCLK or negedge PRESETn) begin
        if (!PRESETn) begin
            parity_out   <= 1'b0;
            parity_error <= 1'b0;
        end else begin
            if (enable) begin
                parity_out <= sampled_parity;
            end else begin
                parity_out <= 1'b0;
            end

            if (check_enable) begin
                parity_error <= parity_mismatch_comb;
            end else begin
                parity_error <= 1'b0;
            end
        end
    end

endmodule
