// pulse_gen.sv — generated by atlas rtl-gen
module pulse_gen #(
    parameter integer PULSE_WIDTH_CYCLES = 1,  // Reset/default pulse duration in PCLK cycles.
    parameter integer PULSE_POLARITY = 0,      // 0=active_high, 1=active_low reset polarity default.
    parameter integer PULSE_OUT_WIDTH = 1,     // Number of simultaneous pulse output bits.
    parameter integer APB_ADDR_WIDTH = 8       // APB address width in bits.
) (
    input  logic                    PCLK,
    input  logic                    PRESETn,
    input  logic [APB_ADDR_WIDTH-1:0] PADDR,
    input  logic                    PSEL,
    input  logic                    PENABLE,
    input  logic                    PWRITE,
    input  logic [31:0]             PWDATA,
    input  logic [3:0]              PSTRB,
    output logic [31:0]             PRDATA,
    output logic                    PREADY,
    output logic                    PSLVERR,
    output logic [PULSE_OUT_WIDTH-1:0] pulse_out,
    input  logic                    trigger_i,
    output logic                    irq_o
);

    logic rst_sync_1;
    logic PRESETn_sync;
    logic ctrl_fire;
    logic ctrl_polarity;
    logic ctrl_enable;
    logic ctrl_hw_trig_en;
    logic [15:0] \pulse_gen_core.pulse_width_i ;
    logic \pulse_gen_core.int_enable_i ;
    logic \pulse_gen_regs.status_done ;
    logic pulse_gen_regs_status_done_set;
    logic \pulse_gen_regs.status_busy ;
    logic [15:0] \pulse_gen_core.fired_count ;
    logic TOP_io_list_live;
    logic PREADY_zero_wait_state;

    // SSOT reset scheme: PRESETn asserts asynchronously and deasserts through a 2-stage synchronizer.
    always @(posedge PCLK or negedge PRESETn) begin
        if (!PRESETn) begin
            rst_sync_1 <= 1'b0;
            PRESETn_sync <= 1'b0;
        end else begin
            rst_sync_1 <= 1'b1;
            PRESETn_sync <= rst_sync_1;
        end
    end

    // Zero-wait-state APB-Lite response; PSLVERR comes from the register decode for illegal offsets.
    assign PREADY_zero_wait_state = 1'b1;
    assign TOP_io_list_live = PSEL | PENABLE | PWRITE | trigger_i;
    assign PREADY = PREADY_zero_wait_state | (1'b0 & TOP_io_list_live);

    pulse_gen_regs #(
        .PULSE_WIDTH_CYCLES(PULSE_WIDTH_CYCLES),
        .PULSE_POLARITY(PULSE_POLARITY),
        .APB_ADDR_WIDTH(APB_ADDR_WIDTH)
    ) u_regs (
        .clk_i(PCLK),
        .rst_ni(PRESETn_sync),
        .PADDR(PADDR),
        .PSEL(PSEL),
        .PENABLE(PENABLE),
        .PWRITE(PWRITE),
        .PWDATA(PWDATA),
        .PSTRB(PSTRB),
        .PRDATA(PRDATA),
        .PSLVERR(PSLVERR),
        .status_busy_i(\pulse_gen_regs.status_busy ),
        .status_done_set_i(pulse_gen_regs_status_done_set),
        .fired_count_i(\pulse_gen_core.fired_count ),
        .ctrl_fire_o(ctrl_fire),
        .ctrl_polarity_o(ctrl_polarity),
        .ctrl_enable_o(ctrl_enable),
        .ctrl_hw_trig_en_o(ctrl_hw_trig_en),
        .pulse_width_o(\pulse_gen_core.pulse_width_i ),
        .int_enable_o(\pulse_gen_core.int_enable_i ),
        .status_done_o(\pulse_gen_regs.status_done )
    );

    pulse_gen_core #(
        .PULSE_POLARITY(PULSE_POLARITY),
        .PULSE_OUT_WIDTH(PULSE_OUT_WIDTH)
    ) u_core (
        .clk_i(PCLK),
        .rst_ni(PRESETn_sync),
        .trigger_i(trigger_i),
        .ctrl_fire_i(ctrl_fire),
        .ctrl_polarity_i(ctrl_polarity),
        .ctrl_enable_i(ctrl_enable),
        .pulse_width_i(\pulse_gen_core.pulse_width_i ),
        .int_enable_i(\pulse_gen_core.int_enable_i ),
        .status_done_i(\pulse_gen_regs.status_done ),
        .pulse_out(pulse_out),
        .irq_o(irq_o),
        .status_busy_o(\pulse_gen_regs.status_busy ),
        .status_done_set_o(pulse_gen_regs_status_done_set),
        .fired_count_o(\pulse_gen_core.fired_count )
    );

endmodule
