// pulse_gen_param.vh — generated by atlas rtl-gen
// Shared defaults from pulse_gen.ssot.yaml parameters.
parameter integer PULSE_WIDTH_CYCLES = 1;  // Reset/default pulse duration in PCLK cycles.
parameter integer PULSE_POLARITY = 0;      // 0=active_high, 1=active_low reset polarity default.
parameter integer PULSE_OUT_WIDTH = 1;     // Number of simultaneous pulse output bits.
parameter integer APB_ADDR_WIDTH = 8;      // APB address width in bits.
parameter integer CLOCK_FREQ_MHZ = 50;     // Target PCLK frequency for integration metadata.
