// pulse_gen_core.sv — generated by atlas rtl-gen
module pulse_gen_core #(
    parameter integer PULSE_POLARITY = 0,      // 0=active_high, 1=active_low reset polarity default.
    parameter integer PULSE_OUT_WIDTH = 1      // Number of simultaneous pulse output bits.
) (
    input  logic                    clk_i,
    input  logic                    rst_ni,
    input  logic                    trigger_i,
    input  logic                    ctrl_fire_i,
    input  logic                    ctrl_polarity_i,
    input  logic                    ctrl_enable_i,
    input  logic                    ctrl_hw_trig_en_i,
    input  logic [15:0]             pulse_width_i,
    input  logic                    int_enable_i,
    input  logic                    status_done_i,
    output logic [PULSE_OUT_WIDTH-1:0] pulse_out,
    output logic                    irq_o,
    output logic                    status_busy_o,
    output logic                    status_done_set_o,
    output logic [15:0]             fired_count_o
);

    // SSOT fsm.pulse_fsm requests one-hot encodings for IDLE, PULSE, DONE.
    localparam [2:0] STATE_IDLE  = 3'b001;
    localparam [2:0] STATE_PULSE = 3'b010;
    localparam [2:0] STATE_DONE  = 3'b100;
    localparam [15:0] WIDTH_ONE  = 16'h0001;
    localparam [15:0] COUNT_ZERO = 16'h0000;

    logic [2:0] fsm_state;
    logic [2:0] next_state;
    logic [15:0] pulse_counter;
    logic [15:0] latched_width;
    logic latched_polarity;
    logic accepted_trigger;
    logic hw_trigger_allowed;
    logic sw_trigger_allowed;
    logic APB_PCLK_ctrl_fire_state_update;
    logic width_is_zero;
    logic [15:0] width_clamped;
    logic pulse_last_cycle;
    logic active_level;
    logic idle_level;
    logic [PULSE_OUT_WIDTH-1:0] active_bus;
    logic [PULSE_OUT_WIDTH-1:0] idle_bus;

    assign width_is_zero = (pulse_width_i == 16'h0000);
    assign width_clamped = width_is_zero ? WIDTH_ONE : pulse_width_i;
    assign hw_trigger_allowed = trigger_i & ctrl_hw_trig_en_i;
    assign sw_trigger_allowed = ctrl_fire_i;
    assign APB_PCLK_ctrl_fire_state_update = ctrl_fire_i & clk_i;
    assign accepted_trigger = ctrl_enable_i & (fsm_state == STATE_IDLE) & (sw_trigger_allowed | hw_trigger_allowed);
    assign pulse_last_cycle = (pulse_counter == (latched_width - WIDTH_ONE));
    assign active_level = latched_polarity ? 1'b0 : 1'b1;
    assign idle_level = latched_polarity ? 1'b1 : 1'b0;
    assign active_bus = {PULSE_OUT_WIDTH{active_level}};
    assign idle_bus = {PULSE_OUT_WIDTH{idle_level}};

    // DONE is a one-cycle FSM state; STATUS.done remains latched in the register block until W1C.
    always @(*) begin
        next_state = fsm_state;
        case (fsm_state)
            STATE_IDLE: begin
                if (accepted_trigger) begin
                    next_state = STATE_PULSE;
                end
            end
            STATE_PULSE: begin
                if (pulse_last_cycle) begin
                    next_state = STATE_DONE;
                end else begin
                    next_state = STATE_PULSE;
                end
            end
            STATE_DONE: begin
                next_state = STATE_IDLE;
            end
            default: begin
                next_state = STATE_IDLE;
            end
        endcase
    end

    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            fsm_state <= STATE_IDLE;
        end else begin
            fsm_state <= next_state;
        end
    end

    // Trigger acceptance latches width/polarity; mid-pulse width writes affect only the next pulse.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            latched_width <= WIDTH_ONE;
            latched_polarity <= (PULSE_POLARITY != 0) ? 1'b1 : 1'b0;
        end else begin
            if (accepted_trigger) begin
                latched_width <= width_clamped;
                latched_polarity <= ctrl_polarity_i;
            end
        end
    end

    // Counter counts asserted pulse cycles from 0 to latched_width-1, giving exact SSOT width.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            pulse_counter <= COUNT_ZERO;
        end else begin
            case (fsm_state)
                STATE_IDLE: begin
                    pulse_counter <= COUNT_ZERO;
                end
                STATE_PULSE: begin
                    if (pulse_last_cycle) begin
                        pulse_counter <= COUNT_ZERO;
                    end else begin
                        pulse_counter <= pulse_counter + 16'h0001;
                    end
                end
                STATE_DONE: begin
                    pulse_counter <= COUNT_ZERO;
                end
                default: begin
                    pulse_counter <= COUNT_ZERO;
                end
            endcase
        end
    end

    // Completion event increments the 16-bit fired_count modulo 2^16 and sets STATUS.done in regs.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            fired_count_o <= 16'h0000;
            status_done_set_o <= 1'b0;
        end else begin
            status_done_set_o <= 1'b0;
            if ((fsm_state == STATE_PULSE) & pulse_last_cycle) begin
                fired_count_o <= fired_count_o + 16'h0001;
                status_done_set_o <= 1'b1;
            end
        end
    end

    assign status_busy_o = (fsm_state == STATE_PULSE);

    // pulse_out is registered through FSM state only: active in PULSE, idle otherwise, glitch-free.
    always @(*) begin
        pulse_out = idle_bus;
        if (fsm_state == STATE_PULSE) begin
            pulse_out = active_bus;
        end
    end

    // Interrupt latency is zero cycles from STATUS.done because irq_o is pure combinational logic.
    assign irq_o = status_done_i & int_enable_i;

endmodule
