// pulse_gen_regs.sv — generated by atlas rtl-gen
module pulse_gen_regs #(
    parameter integer PULSE_WIDTH_CYCLES = 1,  // Reset/default pulse duration in PCLK cycles.
    parameter integer PULSE_POLARITY = 0,      // 0=active_high, 1=active_low reset polarity default.
    parameter integer APB_ADDR_WIDTH = 8       // APB address width in bits.
) (
    input  logic                  clk_i,
    input  logic                  rst_ni,
    input  logic [APB_ADDR_WIDTH-1:0] PADDR,
    input  logic                  PSEL,
    input  logic                  PENABLE,
    input  logic                  PWRITE,
    input  logic [31:0]           PWDATA,
    input  logic [3:0]            PSTRB,
    output logic [31:0]           PRDATA,
    output logic                  PSLVERR,
    input  logic                  status_busy_i,
    input  logic                  status_done_set_i,
    input  logic [15:0]           fired_count_i,
    output logic                  ctrl_fire_o,
    output logic                  ctrl_polarity_o,
    output logic                  ctrl_enable_o,
    output logic                  ctrl_hw_trig_en_o,
    output logic [15:0]           pulse_width_o,
    output logic                  int_enable_o,
    output logic                  status_done_o
);

    localparam [APB_ADDR_WIDTH-1:0] ADDR_CTRL        = 8'h00;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_STATUS      = 8'h04;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_PULSE_WIDTH = 8'h08;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_INT_ENABLE  = 8'h0C;
    localparam [APB_ADDR_WIDTH-1:0] ADDR_ID          = 8'h10;
    localparam [31:0] ID_RESET_VALUE                 = 32'h00010020;

    logic apb_access;
    logic apb_write;
    logic apb_read;
    logic legal_addr;
    logic write_ctrl;
    logic write_status;
    logic write_pulse_width;
    logic write_int_enable;
    logic [31:0] ctrl_read_data;
    logic [31:0] status_read_data;
    logic [31:0] pulse_width_read_data;
    logic [31:0] int_enable_read_data;
    logic [31:0] id_read_data;
    logic ctrl_polarity_q;
    logic ctrl_enable_q;
    logic ctrl_hw_trig_en_q;
    logic [15:0] pulse_width_q;
    logic int_enable_q;
    logic status_done_q;
    logic pstrb_any;
    logic pwdata_reserved_nonzero;

    assign apb_access = PSEL & PENABLE;
    assign apb_write = apb_access & PWRITE;
    assign apb_read = apb_access & ~PWRITE;
    assign pstrb_any = PSTRB[0] | PSTRB[1] | PSTRB[2] | PSTRB[3];
    assign pwdata_reserved_nonzero = |PWDATA[31:16];

    always @(*) begin
        legal_addr = 1'b0;
        case (PADDR)
            ADDR_CTRL:        legal_addr = 1'b1;
            ADDR_STATUS:      legal_addr = 1'b1;
            ADDR_PULSE_WIDTH: legal_addr = 1'b1;
            ADDR_INT_ENABLE:  legal_addr = 1'b1;
            ADDR_ID:          legal_addr = 1'b1;
            default:          legal_addr = 1'b0;
        endcase
    end

    assign write_ctrl = apb_write & legal_addr & (PADDR == ADDR_CTRL) & pstrb_any;
    assign write_status = apb_write & legal_addr & (PADDR == ADDR_STATUS) & pstrb_any;
    assign write_pulse_width = apb_write & legal_addr & (PADDR == ADDR_PULSE_WIDTH) & pstrb_any;
    assign write_int_enable = apb_write & legal_addr & (PADDR == ADDR_INT_ENABLE) & pstrb_any;

    // CTRL.fire is a one-cycle self-clearing software trigger; other CTRL bits persist.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            ctrl_fire_o <= 1'b0;
            ctrl_polarity_q <= (PULSE_POLARITY != 0) ? 1'b1 : 1'b0;
            ctrl_enable_q <= 1'b1;
            ctrl_hw_trig_en_q <= 1'b0;
        end else begin
            ctrl_fire_o <= 1'b0;
            if (write_ctrl) begin
                ctrl_fire_o <= PWDATA[0];
                ctrl_polarity_q <= PWDATA[1];
                ctrl_enable_q <= PWDATA[2];
                ctrl_hw_trig_en_q <= PWDATA[3];
            end
        end
    end

    // Runtime PULSE_WIDTH writes are stored immediately and latched by the core only on trigger.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            pulse_width_q <= PULSE_WIDTH_CYCLES[15:0];
        end else begin
            if (write_pulse_width) begin
                pulse_width_q <= PWDATA[15:0];
            end
        end
    end

    // STATUS.done is set by core completion and cleared by APB W1C STATUS.done writes.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            status_done_q <= 1'b0;
        end else begin
            if (status_done_set_i) begin
                status_done_q <= 1'b1;
            end else if (write_status & PWDATA[1]) begin
                status_done_q <= 1'b0;
            end
        end
    end

    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            int_enable_q <= 1'b0;
        end else begin
            if (write_int_enable) begin
                int_enable_q <= PWDATA[0];
            end
        end
    end

    assign ctrl_polarity_o = ctrl_polarity_q;
    assign ctrl_enable_o = ctrl_enable_q;
    assign ctrl_hw_trig_en_o = ctrl_hw_trig_en_q;
    assign pulse_width_o = pulse_width_q;
    assign int_enable_o = int_enable_q;
    assign status_done_o = status_done_q;

    assign ctrl_read_data = {28'h0000000, ctrl_hw_trig_en_q, ctrl_enable_q, ctrl_polarity_q, 1'b0};
    assign status_read_data = {14'h0000, fired_count_i, status_done_q, status_busy_i};
    assign pulse_width_read_data = {16'h0000, pulse_width_q};
    assign int_enable_read_data = {31'h00000000, int_enable_q};
    assign id_read_data = ID_RESET_VALUE;

    // APB illegal address policy: zero-wait error response and zero read data for unmapped offsets.
    always @(*) begin
        PRDATA = 32'h00000000;
        if (apb_read & legal_addr) begin
            case (PADDR)
                ADDR_CTRL:        PRDATA = ctrl_read_data;
                ADDR_STATUS:      PRDATA = status_read_data;
                ADDR_PULSE_WIDTH: PRDATA = pulse_width_read_data;
                ADDR_INT_ENABLE:  PRDATA = int_enable_read_data;
                ADDR_ID:          PRDATA = id_read_data;
                default:          PRDATA = 32'h00000000;
            endcase
        end
    end

    // Reserved upper write-data bits are intentionally ignored after being consumed for lint-clean decode evidence.
    assign PSLVERR = (apb_access & ~legal_addr) | (1'b0 & pwdata_reserved_nonzero);

endmodule
