#!/usr/bin/env python3
"""run_sta.py — OpenSTA timing analysis on the synthesised netlist.

Python port of run_sta.sh for native-Windows portability. Same CLI, exit
codes, generated TCL, and ``sta -no_init -exit <tcl>`` invocation. Stage 1
delegates to the sibling run_synth.py port (the shell ran run_synth.sh).

Usage:
  run_sta.py <ip> [--root .] [--liberty <file>] [--corner tt|ff|ss]

Outputs:
  <ip>/syn/<ip>.netlist.v          netlist (sky130-mapped)
  <ip>/syn/synth_report.txt        yosys area
  <ip>/syn/sta_report.txt          OpenSTA timing slack + area

Exit codes: 2 usage/bad flag, 1 no liberty / netlist missing / SDC missing.
The trailing ``sta`` step's own rc is not propagated (matching the shell,
which ends with plain echoes after the pipeline).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


def _parse_args(argv: list[str]) -> tuple[str, str, str, str] | int:
    ip = ""
    root = "."
    liberty = ""
    corner = "tt"
    i = 0
    n = len(argv)
    while i < n:
        arg = argv[i]
        if arg == "--root":
            root = argv[i + 1] if i + 1 < n else ""
            i += 2
        elif arg == "--liberty":
            liberty = argv[i + 1] if i + 1 < n else ""
            i += 2
        elif arg == "--corner":
            corner = argv[i + 1] if i + 1 < n else ""
            i += 2
        elif arg.startswith("-"):
            print(f"[run_sta] unknown flag: {arg}", file=sys.stderr)
            return 2
        else:
            ip = arg
            i += 1
    return ip, root, liberty, corner


def _detect_top(ip_dir: Path, ip: str) -> str:
    try:
        import yaml

        with open(ip_dir / "yaml" / f"{ip}.ssot.yaml", encoding="utf-8") as handle:
            d = yaml.safe_load(handle)
        for sm in d.get("sub_modules") or []:
            if isinstance(sm, dict) and sm.get("wiring_only"):
                nm = (
                    (sm.get("file") or "")
                    .split("/")[-1]
                    .replace(".sv", "")
                    .replace(".v", "")
                )
                if nm:
                    return nm
        return str((d.get("top_module") or {}).get("name") or ip)
    except Exception:
        return ""


def _tail(text: str, n: int) -> str:
    lines = text.splitlines(keepends=True)
    return "".join(lines[-n:])


def main(argv: list[str]) -> int:
    parsed = _parse_args(argv)
    if isinstance(parsed, int):
        return parsed
    ip, root, liberty, corner = parsed

    if not ip:
        print("usage: run_sta.sh <ip> [--root .] [--liberty file]", file=sys.stderr)
        return 2
    try:
        root = str(Path(root).resolve(strict=True))
    except OSError:
        print("usage: run_sta.sh <ip> [--root .] [--liberty file]", file=sys.stderr)
        return 2
    ip_dir = Path(root) / ip

    scripts = Path(__file__).resolve().parent
    source_root = scripts.parent.parent.parent

    # Default liberty: sky130 typical corner from OpenROAD test PDK if not given.
    if not liberty:
        home = os.path.expanduser("~")
        for cand in (
            f"{home}/src/OpenROAD/test/sky130hd/"
            f"sky130_fd_sc_hd__{corner}_025C_1v80.lib",
            f"{home}/src/OpenROAD/test/sky130hd/"
            f"sky130_fd_sc_hd__tt_025C_1v80.lib",
            str(source_root / "pdk/sky130/lib/sky130_fd_sc_hd__tt_025C_1v80.lib"),
        ):
            if Path(cand).is_file():
                liberty = cand
                break

    if not liberty or not Path(liberty).is_file():
        print("[run_sta] no liberty file", file=sys.stderr)
        return 1

    print(f"[run_sta] liberty: {liberty}")

    # ── Stage 1: yosys synth with liberty ────────────────────────────────
    print("[run_sta] (1/2) yosys synth with sky130 mapping...")
    run_synth_py = scripts / "run_synth.py"
    proc = subprocess.run(
        [sys.executable, str(run_synth_py), ip, "--root", root, "--liberty", liberty],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    sys.stdout.write(_tail(proc.stdout or "", 15))
    sys.stdout.flush()

    netlist = ip_dir / "syn" / f"{ip}.netlist.v"
    if not netlist.is_file():
        print(f"[run_sta] netlist missing: {netlist}", file=sys.stderr)
        return 1

    top = _detect_top(ip_dir, ip)
    if not top:
        top = f"{ip}_wrapper"
    print(f"[run_sta] top: {top}")

    # ── Stage 2: OpenSTA ─────────────────────────────────────────────────
    sdc = ip_dir / "sdc" / f"{ip}.sdc"
    if not sdc.is_file():
        print(f"[run_sta] missing SDC: {sdc}", file=sys.stderr)
        return 1

    report = ip_dir / "syn" / "sta_report.txt"
    sta_tcl = ip_dir / "syn" / "sta_run.tcl"

    tcl_text = f"""# OpenSTA script auto-generated by run_sta.sh
read_liberty {liberty}
read_verilog {netlist}
link_design {top}
read_sdc {sdc}

puts "─── Clocks ──────────────────────────────────────"
report_clock_properties

puts "─── Worst-case timing path (setup) ──────────────"
report_checks -path_delay max

puts "─── Worst-case timing path (hold) ───────────────"
report_checks -path_delay min

puts "─── Slack summary ───────────────────────────────"
report_worst_slack -max
report_worst_slack -min

puts "─── TNS / WNS ───────────────────────────────────"
report_tns
report_wns

puts "─── Cell + area summary ─────────────────────────"
# OpenSTA doesn't have report_design_area; use report_units / power.
report_units
# Cell count and approximate area come from yosys synth_report.txt.

exit
"""
    sta_tcl.write_text(tcl_text, encoding="utf-8")

    print("[run_sta] (2/2) OpenSTA...")
    # `sta -no_init -exit "$TCL" 2>&1 | tee "$REPORT"`
    sta_proc = subprocess.run(
        ["sta", "-no_init", "-exit", str(sta_tcl)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    combined = sta_proc.stdout or ""
    sys.stdout.write(combined)  # tee → stdout
    sys.stdout.flush()
    report.write_text(combined, encoding="utf-8")  # tee → REPORT

    print("")
    print("[run_sta] OK")
    print(f"[run_sta]   netlist: {netlist}")
    print(f"[run_sta]   sta:     {report}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
