rtl/dma_real_apb_cfg.sv
rtl/dma_real_arbiter.sv
rtl/dma_real_channel.sv
rtl/dma_real_ahb_master.sv
rtl/dma_real_irq.sv
rtl/dma_real_engine.sv
rtl/dma_real_top.sv
rtl/dma_real_async_fifo.sv
rtl/dma_real_cdc_sync.sv
rtl/dma_real_cg_cell.sv
