// parity_gen_regs.sv — generated by atlas rtl-gen from parity_gen SSOT
module parity_gen_regs #(
    parameter integer ADDR_WIDTH = 12  // APB byte address width for the 4KB parity_gen aperture.
) (
    input  logic                  PCLK,
    input  logic                  PRESETn,
    input  logic [ADDR_WIDTH-1:0] PADDR,
    input  logic                  PSEL,
    input  logic                  PENABLE,
    input  logic                  PWRITE,
    input  logic [31:0]           PWDATA,
    input  logic                  parity_error_set,
    output logic [31:0]           PRDATA,
    output logic                  PREADY,
    output logic                  PSLVERR,
    output logic                  enable,
    output logic                  check_enable,
    output logic                  expected_parity,
    output logic [31:0]           control_reg,
    output logic [31:0]           status_reg
);

    localparam [ADDR_WIDTH-1:0] ADDR_CONTROL = {{(ADDR_WIDTH-12){1'b0}}, 12'h000};
    localparam [ADDR_WIDTH-1:0] ADDR_STATUS  = {{(ADDR_WIDTH-12){1'b0}}, 12'h004};

    logic        apb_access;
    logic        apb_write;
    logic        apb_read;
    logic        addr_is_control;
    logic        addr_is_status;
    logic        addr_is_valid;
    logic [31:0] prdata_next;

    // APB-lite zero-wait decode: every access phase completes immediately.
    always @(*) begin
        apb_access      = PSEL & PENABLE;
        apb_write       = apb_access & PWRITE;
        apb_read        = apb_access & ~PWRITE;
        addr_is_control = (PADDR == ADDR_CONTROL);
        addr_is_status  = (PADDR == ADDR_STATUS);
        addr_is_valid   = addr_is_control | addr_is_status;
        PREADY          = apb_access;
        PSLVERR         = apb_access & ~addr_is_valid;
    end

    // Reserved fields read as zero while CONTROL[2:0] and STATUS[0] remain software-visible.
    always @(*) begin
        prdata_next = 32'h00000000;
        if (addr_is_control) begin
            prdata_next = {29'h00000000, control_reg[2:0]};
        end else begin
            if (addr_is_status) begin
                prdata_next = {31'h00000000, status_reg[0]};
            end else begin
                prdata_next = 32'h00000000;
            end
        end
    end

    // CONTROL is RW for bits [2:0]; STATUS[0] is sticky W1C and also set by parity mismatch.
    always @(posedge PCLK or negedge PRESETn) begin
        if (!PRESETn) begin
            control_reg <= 32'h00000000;
            status_reg  <= 32'h00000000;
            PRDATA      <= 32'h00000000;
        end else begin
            PRDATA <= prdata_next;

            if (apb_write & addr_is_control) begin
                control_reg <= {29'h00000000, PWDATA[2:0]};
            end else begin
                control_reg <= {29'h00000000, control_reg[2:0]};
            end

            if (parity_error_set) begin
                status_reg[0] <= 1'b1;
            end else begin
                if (apb_write & addr_is_status & PWDATA[0]) begin
                    status_reg[0] <= 1'b0;
                end else begin
                    status_reg[0] <= status_reg[0];
                end
            end
            status_reg[31:1] <= 31'h00000000;
        end
    end

    always @(*) begin
        enable          = control_reg[0];
        check_enable    = control_reg[1];
        expected_parity = control_reg[2];
    end

endmodule
