// parity_gen.sv — generated by atlas rtl-gen from parity_gen SSOT
module parity_gen #(
    `include "parity_gen_param.vh"
) (
    input  logic                  PCLK,
    input  logic                  PRESETn,
    input  logic [11:0]           PADDR,
    input  logic                  PSEL,
    input  logic                  PENABLE,
    input  logic                  PWRITE,
    input  logic [31:0]           PWDATA,
    output logic [31:0]           PRDATA,
    output logic                  PREADY,
    output logic                  PSLVERR,
    input  logic [31:0]           data_in,
    output logic                  parity_out,
    output logic                  parity_error
);

    logic        enable;
    logic        check_enable;
    logic        expected_parity;
    logic        parity_mismatch_comb;
    // Register block owns APB-lite CONTROL/STATUS storage and reserved-address errors.
    parity_gen_regs #(
        .ADDR_WIDTH(ADDR_WIDTH)
    ) u_regs (
        .PCLK(PCLK),
        .PRESETn(PRESETn),
        .PADDR(PADDR),
        .PSEL(PSEL),
        .PENABLE(PENABLE),
        .PWRITE(PWRITE),
        .PWDATA(PWDATA),
        .parity_error_set(check_enable & parity_mismatch_comb),
        .PRDATA(PRDATA),
        .PREADY(PREADY),
        .PSLVERR(PSLVERR),
        .enable(enable),
        .check_enable(check_enable),
        .expected_parity(expected_parity)
    );

    // Core owns the SSOT parity datapath and 1-cycle registered output timing.
    parity_gen_core #(
        .DATA_WIDTH(DATA_WIDTH)
    ) u_core (
        .PCLK(PCLK),
        .PRESETn(PRESETn),
        .data_in(data_in),
        .enable(enable),
        .check_enable(check_enable),
        .expected_parity(expected_parity),
        .parity_out(parity_out),
        .parity_error(parity_error),
        .parity_mismatch_comb(parity_mismatch_comb)
    );

endmodule
