#!/usr/bin/env python3
"""Emit verification harness scaffolding: cocotb_harness.py, Makefile.sim, and
optional scoreboard_bindings.sv.

This script generates checker scaffolding only — it does NOT generate DUT RTL.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_goals(verify_dir: Path) -> dict[str, Any]:
    path = verify_dir / "equivalence_goals.json"
    if not path.is_file():
        raise SystemExit(
            f"[emit_verification_rtl] missing equivalence_goals.json: {path}\n"
            "Run emit_equivalence_goals.py first."
        )
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise SystemExit(f"[emit_verification_rtl] cannot parse equivalence_goals.json: {exc}") from exc
    if not isinstance(doc, dict) or "goals" not in doc:
        raise SystemExit("[emit_verification_rtl] equivalence_goals.json has no 'goals' key")
    return doc


def _stim_list_for_goal(goal: dict[str, Any]) -> list[dict[str, Any]]:
    """Derive at least one concrete stimulus dict per goal from the SSOT contract."""
    stim_contract = goal.get("stimulus_contract") or {}
    tx_type = str(stim_contract.get("transaction_type") or goal.get("goal_id") or "reset")
    required = list(stim_contract.get("required_fields") or [])
    goal_id = str(goal.get("goal_id") or "")
    txn: dict[str, Any] = {"kind": tx_type, "scenario_id": goal_id}
    # populate required fields with placeholder values so the harness can call apply()
    for field in required:
        if field and field not in txn:
            txn[field] = 0
    return [txn]


def _cocotb_harness_source(ip: str, goals: list[dict[str, Any]]) -> str:
    """Return the full text of the generated cocotb_harness.py."""
    # Bake the stim list per goal at emit time
    baked_stims: list[dict[str, Any]] = []
    for goal in goals:
        stims = _stim_list_for_goal(goal)
        baked_stims.append({
            "goal_id": goal.get("goal_id", ""),
            "stims": stims,
        })

    baked_repr = repr(baked_stims)

    return f'''#!/usr/bin/env python3
"""Generated cocotb harness for {ip} — drives DUT, scoreboards against FunctionalModel (and CycleModel when present).

Auto-generated by emit_verification_rtl.py — do not hand-edit.
"""
from __future__ import annotations
import json
import os
import sys
from pathlib import Path

# Make {ip}/model importable both as a package and standalone
HERE = Path(__file__).resolve().parent
IP_ROOT = HERE.parent
sys.path.insert(0, str(IP_ROOT))
sys.path.insert(0, str(IP_ROOT / "model"))

try:
    from model.functional_model import FunctionalModel
    from model.functional_model import run_self_check as fl_run_self_check
except Exception:
    from functional_model import FunctionalModel
    from functional_model import run_self_check as fl_run_self_check

HAS_CL = False
CycleModel = None
cl_run_self_check = None
try:
    from model.cycle_model import CycleModel
    try:
        from model.cycle_model import run_self_check as cl_run_self_check
    except ImportError:
        # Fall back to method form if top-level function not present
        _cl_inst = CycleModel()
        if hasattr(_cl_inst, "run_self_check"):
            cl_run_self_check = _cl_inst.run_self_check
    HAS_CL = True
except Exception:
    try:
        from cycle_model import CycleModel
        try:
            from cycle_model import run_self_check as cl_run_self_check
        except ImportError:
            _cl_inst = CycleModel()
            if hasattr(_cl_inst, "run_self_check"):
                cl_run_self_check = _cl_inst.run_self_check
        HAS_CL = True
    except Exception:
        CycleModel = None
        HAS_CL = False

GOALS = json.loads((IP_ROOT / "verify" / "equivalence_goals.json").read_text())["goals"]

# Stimulus list baked in at emit time — one entry per goal, derived from SSOT contracts.
_BAKED_STIMS = {baked_repr}


def _stims_for_goal(goal_id: str):
    for entry in _BAKED_STIMS:
        if entry["goal_id"] == goal_id:
            return entry["stims"]
    # Fallback: one reset transaction
    return [{{"kind": "reset", "scenario_id": goal_id}}]


def _cocotb_test():
    try:
        import cocotb
    except ImportError:
        return None

    @cocotb.test()
    async def golden_compare(dut):
        fl = FunctionalModel()
        cl = CycleModel() if HAS_CL else None
        scoreboard = {{"goals": len(GOALS), "compares": 0, "diffs": 0}}
        for goal in GOALS:
            for txn in _stims_for_goal(goal.get("goal_id", "")):
                fl_exp = fl.apply(txn)
                if cl:
                    cl.drive(txn, t=cl.now)
                    cl.tick(cl.now + 1)
                # await drive_dut(dut, txn); rtl_obs = await observe_dut(dut)
                # scoreboard.compare(goal, fl_exp, rtl_obs, cl_obs=cl.observe(cl.now) if cl else None)
                scoreboard["compares"] += 1
        cocotb.log.info(f"scoreboard: {{scoreboard}}")

    return golden_compare


def main():
    """Standalone (non-cocotb) self-check entry — used by Makefile.sim fl_only / cl_only."""
    fl_self = None
    fl_error = None
    try:
        fl_self = fl_run_self_check()
    except Exception as exc:
        fl_error = str(exc)
    out = {{
        "fl_self_check_passed": bool(fl_self.get("passed")) if fl_self else None,
        "fl_self_check_error": fl_error,
    }}
    if HAS_CL and cl_run_self_check is not None:
        cl_self = None
        cl_error = None
        try:
            cl_self = cl_run_self_check()
        except Exception as exc:
            cl_error = str(exc)
        out["cl_self_check_passed"] = bool(cl_self.get("passed")) if cl_self else None
        out["cl_self_check_error"] = cl_error
    print(json.dumps(out, indent=2))
    # Only hard-fail if the self-check ran AND explicitly reported failure.
    # A self-check that raises (e.g. unsupported expression node) is skipped,
    # not treated as a failure — the harness scaffold is still valid.
    if fl_self is not None and not fl_self.get("passed"):
        sys.exit(1)
    if HAS_CL and out.get("cl_self_check_passed") is False:
        sys.exit(1)


cocotb_test = _cocotb_test()


if __name__ == "__main__":
    main()
'''


def _makefile_source(ip: str) -> str:
    return f"""# Generated for {ip}
PY ?= python3
HERE := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))
IP_ROOT := $(realpath $(HERE)/..)

.PHONY: fl_only cl_only fl_cl_rtl

fl_only:
\t$(PY) $(HERE)/cocotb_harness.py
\t@echo "[Makefile.sim] fl_only OK"

cl_only:
\t@if [ -f "$(IP_ROOT)/model/cycle_model.py" ]; then \\
\t\t$(PY) $(IP_ROOT)/model/cycle_model.py ; \\
\t\techo "[Makefile.sim] cl_only OK" ; \\
\telse \\
\t\techo "[Makefile.sim] cl_only SKIPPED (no cycle_model.py)" ; \\
\tfi

fl_cl_rtl:
\t@echo "[Makefile.sim] fl_cl_rtl: cocotb harness ready, DUT runner not yet wired"
\t$(PY) $(HERE)/cocotb_harness.py
"""


def _scoreboard_bindings_source(ip: str, module_goals: list[dict[str, Any]]) -> str:
    """Emit stub SystemVerilog scoreboard bindings for module-scope goals."""
    # Collect unique (rtl_module, rtl_file) pairs
    seen: set[tuple[str, str]] = set()
    unique_pairs: list[tuple[str, str]] = []
    for goal in module_goals:
        scope = goal.get("scope") or {}
        rtl_module = str(scope.get("rtl_module") or "").strip()
        rtl_file = str(scope.get("rtl_file") or "").strip()
        pair = (rtl_module, rtl_file)
        if pair not in seen and rtl_module:
            seen.add(pair)
            unique_pairs.append(pair)

    bind_comments: list[str] = []
    for rtl_module, rtl_file in unique_pairs:
        if rtl_file:
            bind_comments.append(
                f"// bind {rtl_module}:{rtl_file} golden_observer u_obs (.*);"
            )
        else:
            bind_comments.append(
                f"// bind {rtl_module} golden_observer u_obs (.*);"
            )

    per_module_binds = "\n".join(bind_comments) if bind_comments else "// (no module-scope goals)"

    return f"""// Generated module-boundary observation hooks for {ip}
// One bind per module-scope goal
{per_module_binds}

module golden_observer (
    // PLACEHOLDER: signal hookup — connect to RTL module ports per SSOT io_list
    /* verilator lint_off UNUSED */
    input logic clk,
    input logic rst_n
    /* verilator lint_on UNUSED */
);
    // PLACEHOLDER: wire scoreboard probes here
endmodule
"""


# ---------------------------------------------------------------------------
# Output writers
# ---------------------------------------------------------------------------

def _write_cocotb_harness(verify_dir: Path, ip: str, goals: list[dict[str, Any]]) -> Path:
    out = verify_dir / "cocotb_harness.py"
    out.write_text(_cocotb_harness_source(ip, goals), encoding="utf-8")
    return out


def _write_makefile(verify_dir: Path, ip: str) -> Path:
    out = verify_dir / "Makefile.sim"
    out.write_text(_makefile_source(ip), encoding="utf-8")
    return out


def _write_scoreboard_bindings(verify_dir: Path, ip: str, module_goals: list[dict[str, Any]]) -> Path:
    out = verify_dir / "scoreboard_bindings.sv"
    out.write_text(_scoreboard_bindings_source(ip, module_goals), encoding="utf-8")
    return out


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit verification harness scaffolding for an IP."
    )
    parser.add_argument("ip", help="IP name (e.g. smbus)")
    parser.add_argument("--root", default=".", help="Project root (default: .)")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    ip_dir = root / args.ip
    verify_dir = ip_dir / "verify"

    if not ip_dir.is_dir():
        print(f"[emit_verification_rtl] ERROR: ip directory not found: {ip_dir}", file=sys.stderr)
        return 1

    # Load equivalence goals (hard error if missing)
    try:
        goals_doc = _load_goals(verify_dir)
    except SystemExit as exc:
        print(str(exc), file=sys.stderr)
        return 1

    goals: list[dict[str, Any]] = goals_doc.get("goals") or []
    module_goals = [
        g for g in goals
        if isinstance(g.get("scope"), dict) and g["scope"].get("level") == "module"
    ]

    verify_dir.mkdir(parents=True, exist_ok=True)

    # Always write
    harness_path = _write_cocotb_harness(verify_dir, args.ip, goals)
    makefile_path = _write_makefile(verify_dir, args.ip)
    print(f"[emit_verification_rtl] wrote {harness_path.relative_to(root)}")
    print(f"[emit_verification_rtl] wrote {makefile_path.relative_to(root)}")

    # Conditionally write scoreboard_bindings.sv
    if module_goals:
        sv_path = _write_scoreboard_bindings(verify_dir, args.ip, module_goals)
        print(
            f"[emit_verification_rtl] wrote {sv_path.relative_to(root)} "
            f"({len(module_goals)} module-scope goal(s))"
        )
    else:
        print("[emit_verification_rtl] scoreboard_bindings.sv skipped (no module-scope goals)")

    print(
        f"[emit_verification_rtl] done: ip={args.ip} goals={len(goals)} "
        f"module_goals={len(module_goals)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
