#!/usr/bin/env python3
"""Deprecated fixed-shape cocotb smoke/regression helper.

The production SSOT TB path is the AI-driven `ssot-tb-cocotb` workflow. This
script contains historical APB/CPU/BUS templates and is disabled by default so
new IP work cannot silently fall back to fixed templates.
"""

from __future__ import annotations

import argparse
from datetime import datetime
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time

import yaml


TEST_TEMPLATE = r'''# Auto-generated by workflow/tb-gen/scripts/ssot_to_cocotb.py
import json
import os
import time
from pathlib import Path

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge


ADDR_CTRL = 0x0
ADDR_COUNT = 0x4
ADDR_COMPARE = 0x8
ADDR_STATUS = 0xC

_bins = {
    "reset_defaults": False,
    "apb_write_ctrl": False,
    "apb_write_compare": False,
    "apb_readback": False,
    "counter_increments": False,
    "counter_halts": False,
    "compare_irq": False,
    "status_w1c_clear": False,
    "irq_mask": False,
}


def _set_bin(name):
    _bins[name] = True


async def _reset(dut):
    dut.psel.value = 0
    dut.penable.value = 0
    dut.pwrite.value = 0
    dut.paddr.value = 0
    dut.pwdata.value = 0
    dut.pstrb.value = 0
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 4)
    dut.rst_n.value = 1
    await ClockCycles(dut.clk, 2)


async def _apb_write(dut, addr, data):
    dut.paddr.value = addr
    dut.pwrite.value = 1
    dut.pwdata.value = data
    dut.pstrb.value = 0xF
    dut.psel.value = 1
    dut.penable.value = 0
    await RisingEdge(dut.clk)
    dut.penable.value = 1
    await RisingEdge(dut.clk)
    assert int(dut.pready.value) == 1
    assert int(dut.pslverr.value) == 0
    dut.psel.value = 0
    dut.penable.value = 0
    dut.pwrite.value = 0
    dut.paddr.value = 0
    dut.pwdata.value = 0
    dut.pstrb.value = 0
    await RisingEdge(dut.clk)


async def _apb_read(dut, addr):
    dut.paddr.value = addr
    dut.pwrite.value = 0
    dut.psel.value = 1
    dut.penable.value = 0
    await RisingEdge(dut.clk)
    dut.penable.value = 1
    await RisingEdge(dut.clk)
    assert int(dut.pready.value) == 1
    assert int(dut.pslverr.value) == 0
    value = int(dut.prdata.value)
    dut.psel.value = 0
    dut.penable.value = 0
    dut.paddr.value = 0
    await RisingEdge(dut.clk)
    return value


def _write_coverage(status="ok"):
    hit = sum(1 for v in _bins.values() if v)
    total = len(_bins)
    pct = round(100.0 * hit / total, 2) if total else 100.0
    data = {
        "timestamp_iso": datetime_now(),
        "dut": os.environ.get("DUT_NAME", "unknown"),
        "status": status,
        "tests": {"hit": hit, "total": total, "pct": pct},
        "lines": {"hit": hit, "total": total, "pct": pct},
        "branches": {"hit": hit, "total": total, "pct": pct},
        "functional": {"hit": hit, "total": total, "pct": pct, "bins": _bins},
        "html_available": False,
    }
    cov_path = Path(os.environ["COVERAGE_JSON"])
    cov_path.parent.mkdir(parents=True, exist_ok=True)
    cov_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    hist_path = Path(os.environ["COVERAGE_HISTORY_JSONL"])
    with hist_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(data) + "\n")


def datetime_now():
    return time.strftime("%Y-%m-%dT%H:%M:%S")


@cocotb.test()
async def apb_timer_regression(dut):
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    await _reset(dut)

    assert int(dut.irq.value) == 0
    assert await _apb_read(dut, ADDR_CTRL) == 0
    assert await _apb_read(dut, ADDR_COMPARE) == 0
    assert await _apb_read(dut, ADDR_STATUS) == 0
    _set_bin("reset_defaults")

    await _apb_write(dut, ADDR_COMPARE, 9)
    assert await _apb_read(dut, ADDR_COMPARE) == 9
    _set_bin("apb_write_compare")
    _set_bin("apb_readback")

    await _apb_write(dut, ADDR_CTRL, 0x1)
    assert await _apb_read(dut, ADDR_CTRL) & 0x1 == 0x1
    _set_bin("apb_write_ctrl")
    first = await _apb_read(dut, ADDR_COUNT)
    await ClockCycles(dut.clk, 4)
    second = await _apb_read(dut, ADDR_COUNT)
    assert second > first
    _set_bin("counter_increments")

    await _apb_write(dut, ADDR_CTRL, 0x0)
    stopped_a = await _apb_read(dut, ADDR_COUNT)
    await ClockCycles(dut.clk, 5)
    stopped_b = await _apb_read(dut, ADDR_COUNT)
    assert stopped_b == stopped_a
    _set_bin("counter_halts")

    await _reset(dut)
    await _apb_write(dut, ADDR_COMPARE, 3)
    await _apb_write(dut, ADDR_CTRL, 0x3)
    await ClockCycles(dut.clk, 5)
    assert int(dut.irq.value) == 1
    assert await _apb_read(dut, ADDR_STATUS) & 0x1 == 0x1
    _set_bin("compare_irq")

    await _apb_write(dut, ADDR_STATUS, 0x1)
    await ClockCycles(dut.clk, 2)
    assert int(dut.irq.value) == 0
    assert await _apb_read(dut, ADDR_STATUS) & 0x1 == 0x0
    _set_bin("status_w1c_clear")

    await _reset(dut)
    await _apb_write(dut, ADDR_COMPARE, 2)
    await _apb_write(dut, ADDR_CTRL, 0x1)
    await ClockCycles(dut.clk, 4)
    assert await _apb_read(dut, ADDR_STATUS) & 0x1 == 0x1
    assert int(dut.irq.value) == 0
    _set_bin("irq_mask")

    _write_coverage("ok")
'''


RUNNER_TEMPLATE = r'''# Auto-generated by workflow/tb-gen/scripts/ssot_to_cocotb.py
from pathlib import Path
import os

from cocotb_test.simulator import run


def test_{ip}_cocotb():
    root = Path(__file__).resolve().parents[2]
    ip = "{ip}"
    sources = [
        root / "rtl" / f"{ip}_regs.sv",
        root / "rtl" / f"{ip}_core.sv",
        root / "rtl" / f"{ip}_wrapper.sv",
    ]
    build_dir = root / "sim" / "cocotb_build"
    build_dir.mkdir(parents=True, exist_ok=True)
    dump_src = build_dir / f"{ip}_vcd_dump.v"
    dump_src.write_text(
        "module {ip}_vcd_dump();\n"
        "initial begin\n"
        "  $dumpfile(\"{ip}.vcd\");\n"
        "  $dumpvars(0, {ip}_wrapper);\n"
        "end\n"
        "endmodule\n"
    )
    sources.append(dump_src)
    os.environ.setdefault("DUT_NAME", ip)
    os.environ.setdefault("COVERAGE_JSON", str(root / "cov" / "coverage.json"))
    os.environ.setdefault("COVERAGE_HISTORY_JSONL", str(root / "cov" / "history.jsonl"))
    run(
        simulator="icarus",
        verilog_sources=[str(p) for p in sources],
        toplevel=[f"{ip}_wrapper", f"{ip}_vcd_dump"],
        module=f"test_{ip}",
        sim_build=str(build_dir),
        timescale="1ns/1ps",
        waves=False,
        force_compile=True,
    )
'''


CPU_TEST_TEMPLATE = r'''# Auto-generated by workflow/tb-gen/scripts/ssot_to_cocotb.py
import json
import os
import time
from pathlib import Path

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge


_bins = {
    "reset_defaults": False,
    "reset_vector_fetch_seen": False,
    "instruction_axi_activity": False,
    "data_axi_activity": False,
    "debug_commit_activity": False,
    "debug_pc_changes": False,
    "trap_halt_observed_or_reset_clean": False,
    "rv32i_branch_class_verified": False,
    "rv32i_load_store_class_verified": False,
}


def _set_bin(name):
    _bins[name] = True


def _now():
    return time.strftime("%Y-%m-%dT%H:%M:%S")


def _as_int(value):
    try:
        return int(value)
    except Exception:
        return 0


def _i_type(imm, rs1, funct3, rd, opcode):
    return ((imm & 0xFFF) << 20) | (rs1 << 15) | (funct3 << 12) | (rd << 7) | opcode


def _r_type(funct7, rs2, rs1, funct3, rd, opcode):
    return (funct7 << 25) | (rs2 << 20) | (rs1 << 15) | (funct3 << 12) | (rd << 7) | opcode


def _s_type(imm, rs2, rs1, funct3, opcode):
    return (((imm >> 5) & 0x7F) << 25) | (rs2 << 20) | (rs1 << 15) | (funct3 << 12) | ((imm & 0x1F) << 7) | opcode


def _b_type(imm, rs2, rs1, funct3, opcode):
    return (((imm >> 12) & 0x1) << 31) | (((imm >> 5) & 0x3F) << 25) | (rs2 << 20) | (rs1 << 15) | (funct3 << 12) | (((imm >> 1) & 0xF) << 8) | (((imm >> 11) & 0x1) << 7) | opcode


NOP = 0x00000013
PROGRAM = {
    0x00: _i_type(5, 0, 0, 1, 0x13),       # addi x1, x0, 5
    0x04: _i_type(7, 0, 0, 2, 0x13),       # addi x2, x0, 7
    0x08: _r_type(0, 2, 1, 0, 3, 0x33),    # add  x3, x1, x2
    0x0C: _s_type(0, 3, 0, 2, 0x23),       # sw   x3, 0(x0)
    0x10: _i_type(0, 0, 2, 4, 0x03),       # lw   x4, 0(x0)
    0x14: _b_type(8, 3, 4, 0, 0x63),       # beq  x4, x3, +8
    0x18: _i_type(1, 0, 0, 5, 0x13),       # skipped if branch works
    0x1C: _i_type(2, 0, 0, 6, 0x13),       # branch target
    0x20: 0x00100073,                      # ebreak
}


async def _reset(dut):
    dut.rst.value = 1
    dut.imem_arready.value = 1
    dut.imem_rdata.value = 0x00000013
    dut.imem_rresp.value = 0
    dut.imem_rvalid.value = 1
    dut.dmem_awready.value = 1
    dut.dmem_wready.value = 1
    dut.dmem_bresp.value = 0
    dut.dmem_bvalid.value = 1
    dut.dmem_arready.value = 1
    dut.dmem_rdata.value = 0
    dut.dmem_rresp.value = 0
    dut.dmem_rvalid.value = 1
    await ClockCycles(dut.clk, 4)
    assert _as_int(dut.dbg_pc.value) == 0
    assert _as_int(dut.imem_araddr.value) == 0
    assert _as_int(dut.dbg_commit_valid.value) == 0
    _set_bin("reset_defaults")
    _set_bin("reset_vector_fetch_seen")
    dut.rst.value = 0
    await ClockCycles(dut.clk, 2)


def _write_coverage(status="ok", static=None):
    hit = sum(1 for v in _bins.values() if v)
    total = len(_bins)
    pct = round(100.0 * hit / total, 2) if total else 100.0
    static = static or {}
    data = {
        "timestamp_iso": _now(),
        "dut": os.environ.get("DUT_NAME", "unknown"),
        "status": status,
        "tests": {"hit": hit, "total": total, "pct": pct},
        "functional": {"hit": hit, "total": total, "pct": pct, "bins": _bins},
        "lines": static.get("lines", {"hit": 0, "total": 0, "pct": 0.0, "source": "not_instrumented"}),
        "branches": static.get("branches", {"hit": 0, "total": 0, "pct": 0.0, "source": "not_instrumented"}),
        "fsm": static.get("fsm", {"hit": 0, "total": 0, "pct": 0.0, "source": "not_instrumented"}),
        "static": static,
        "html_available": False,
    }
    cov_path = Path(os.environ["COVERAGE_JSON"])
    cov_path.parent.mkdir(parents=True, exist_ok=True)
    cov_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    hist_path = Path(os.environ["COVERAGE_HISTORY_JSONL"])
    hist_path.parent.mkdir(parents=True, exist_ok=True)
    with hist_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(data) + "\n")


@cocotb.test()
async def rv32i_cpu_smoke_and_debug_coverage(dut):
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    await _reset(dut)

    pc_values = []
    instr_valid_seen = False
    data_valid_seen = False
    commit_seen = False
    trap_or_clean = False
    store_seen = False
    load_seen = False
    memory = {0: 0}

    for _cycle in range(80):
        fetch_addr = _as_int(dut.imem_araddr.value) & 0xFFFF_FFFC
        dut.imem_rdata.value = PROGRAM.get(fetch_addr, NOP)
        read_addr = _as_int(dut.dmem_araddr.value) & 0xFFFF_FFFC
        dut.dmem_rdata.value = memory.get(read_addr, 0)

        if _as_int(dut.dmem_awvalid.value) and _as_int(dut.dmem_wvalid.value):
            write_addr = _as_int(dut.dmem_awaddr.value) & 0xFFFF_FFFC
            memory[write_addr] = _as_int(dut.dmem_wdata.value)
            store_seen = True
        if _as_int(dut.dmem_arvalid.value):
            load_seen = True

        await RisingEdge(dut.clk)
        pc_values.append(_as_int(dut.dbg_pc.value))
        instr_valid_seen = instr_valid_seen or bool(_as_int(dut.imem_arvalid.value)) or bool(_as_int(dut.imem_rready.value))
        data_valid_seen = data_valid_seen or bool(_as_int(dut.dmem_awvalid.value)) or bool(_as_int(dut.dmem_wvalid.value)) or bool(_as_int(dut.dmem_arvalid.value))
        commit_seen = commit_seen or bool(_as_int(dut.dbg_commit_valid.value))
        trap_or_clean = trap_or_clean or bool(_as_int(dut.dbg_trap.value)) or bool(_as_int(dut.dbg_halt.value))
        if _as_int(dut.dbg_halt.value):
            break

    assert len(set(pc_values)) > 1
    _set_bin("debug_pc_changes")
    if instr_valid_seen:
        _set_bin("instruction_axi_activity")
    if data_valid_seen:
        _set_bin("data_axi_activity")
    if commit_seen:
        _set_bin("debug_commit_activity")
    if trap_or_clean or _as_int(dut.dbg_trap.value) == 0:
        _set_bin("trap_halt_observed_or_reset_clean")
    if 0x1C in pc_values and 0x18 not in pc_values:
        _set_bin("rv32i_branch_class_verified")
    if store_seen and load_seen and memory.get(0) == 12:
        _set_bin("rv32i_load_store_class_verified")

    _write_coverage("ok", json.loads(os.environ.get("STATIC_COVERAGE_JSON", "{}") or "{}"))
'''


CPU_RUNNER_TEMPLATE = r'''# Auto-generated by workflow/tb-gen/scripts/ssot_to_cocotb.py
from pathlib import Path
import json
import os

from cocotb_test.simulator import run


def test_{ip}_cocotb():
    root = Path(__file__).resolve().parents[2]
    ip = "{ip}"
    filelist = root / "list" / f"{ip}.f"
    sources = []
    if filelist.exists():
        for line in filelist.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                sources.append((root.parent / line).resolve())
    else:
        sources = sorted((root / "rtl").glob("*.sv"))
    build_dir = root / "sim" / "cocotb_build"
    build_dir.mkdir(parents=True, exist_ok=True)
    dump_src = build_dir / f"{ip}_vcd_dump.v"
    dump_src.write_text(
        "module {ip}_vcd_dump();\n"
        "initial begin\n"
        "  $dumpfile(\"{ip}.vcd\");\n"
        "  $dumpvars(0, {ip});\n"
        "end\n"
        "endmodule\n",
        encoding="utf-8",
    )
    sources.append(dump_src)
    os.environ.setdefault("DUT_NAME", ip)
    os.environ.setdefault("COVERAGE_JSON", str(root / "cov" / "coverage.json"))
    os.environ.setdefault("COVERAGE_HISTORY_JSONL", str(root / "cov" / "history.jsonl"))
    os.environ.setdefault("STATIC_COVERAGE_JSON", json.dumps({static_coverage_json}))
    run(
        simulator="icarus",
        verilog_sources=[str(p) for p in sources],
        toplevel=[ip, f"{ip}_vcd_dump"],
        module=f"test_{ip}",
        sim_build=str(build_dir),
        timescale="1ns/1ps",
        waves=False,
        force_compile=True,
    )
'''


BUS_TEST_TEMPLATE = r'''# Auto-generated by workflow/tb-gen/scripts/ssot_to_cocotb.py
import json
import os
import time
from pathlib import Path

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge


PERIPH_BASE = 0x40000000
_bins = {
    "reset_defaults": False,
    "instruction_read_pass_through": False,
    "data_memory_read_route": False,
    "data_memory_write_route": False,
    "peripheral_read_route": False,
    "peripheral_write_route": False,
    "response_mux_okay": False,
    "route_status_observed": False,
}


def _set_bin(name):
    _bins[name] = True


def _now():
    return time.strftime("%Y-%m-%dT%H:%M:%S")


def _as_int(value):
    try:
        return int(value)
    except Exception:
        return 0


async def _reset(dut):
    dut.rst.value = 1
    for name in [
        "cpu_i_araddr", "cpu_i_arvalid", "cpu_i_rready",
        "cpu_d_awaddr", "cpu_d_awvalid", "cpu_d_wdata", "cpu_d_wstrb", "cpu_d_wvalid", "cpu_d_bready",
        "cpu_d_araddr", "cpu_d_arvalid", "cpu_d_rready",
    ]:
        getattr(dut, name).value = 0
    for name in ["mem_i_arready", "mem_i_rvalid", "mem_d_awready", "mem_d_wready", "mem_d_bvalid", "mem_d_arready", "mem_d_rvalid", "periph_awready", "periph_wready", "periph_bvalid", "periph_arready", "periph_rvalid"]:
        getattr(dut, name).value = 0
    dut.mem_i_rdata.value = 0
    dut.mem_i_rresp.value = 0
    dut.mem_d_bresp.value = 0
    dut.mem_d_rdata.value = 0
    dut.mem_d_rresp.value = 0
    dut.periph_bresp.value = 0
    dut.periph_rdata.value = 0
    dut.periph_rresp.value = 0
    await ClockCycles(dut.clk, 4)
    assert _as_int(dut.route_error.value) == 0
    _set_bin("reset_defaults")
    dut.rst.value = 0
    await ClockCycles(dut.clk, 2)


def _write_coverage(status="ok", static=None):
    hit = sum(1 for v in _bins.values() if v)
    total = len(_bins)
    pct = round(100.0 * hit / total, 2) if total else 100.0
    static = static or {}
    data = {
        "timestamp_iso": _now(),
        "dut": os.environ.get("DUT_NAME", "unknown"),
        "status": status,
        "tests": {"hit": hit, "total": total, "pct": pct},
        "functional": {"hit": hit, "total": total, "pct": pct, "bins": _bins},
        "lines": static.get("lines", {"hit": 0, "total": 0, "pct": 0.0, "source": "not_instrumented"}),
        "branches": static.get("branches", {"hit": 0, "total": 0, "pct": 0.0, "source": "not_instrumented"}),
        "fsm": static.get("fsm", {"hit": 0, "total": 0, "pct": 0.0, "source": "not_instrumented"}),
        "static": static,
        "html_available": False,
    }
    cov_path = Path(os.environ["COVERAGE_JSON"])
    cov_path.parent.mkdir(parents=True, exist_ok=True)
    cov_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    hist_path = Path(os.environ["COVERAGE_HISTORY_JSONL"])
    hist_path.parent.mkdir(parents=True, exist_ok=True)
    with hist_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(data) + "\n")


@cocotb.test()
async def rv32i_bus_routes_and_coverage(dut):
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    await _reset(dut)

    dut.mem_i_arready.value = 1
    dut.mem_i_rvalid.value = 1
    dut.mem_i_rdata.value = 0x11223344
    dut.cpu_i_araddr.value = 0x00000020
    dut.cpu_i_arvalid.value = 1
    dut.cpu_i_rready.value = 1
    await RisingEdge(dut.clk)
    assert _as_int(dut.mem_i_araddr.value) == 0x20
    assert _as_int(dut.mem_i_arvalid.value) == 1
    assert _as_int(dut.cpu_i_rdata.value) == 0x11223344
    _set_bin("instruction_read_pass_through")
    dut.cpu_i_arvalid.value = 0
    dut.cpu_i_rready.value = 0

    dut.mem_d_arready.value = 1
    dut.mem_d_rvalid.value = 1
    dut.mem_d_rdata.value = 0xA5A50001
    dut.cpu_d_araddr.value = 0x00000100
    dut.cpu_d_arvalid.value = 1
    dut.cpu_d_rready.value = 1
    await RisingEdge(dut.clk)
    assert _as_int(dut.mem_d_arvalid.value) == 1
    assert _as_int(dut.periph_arvalid.value) == 0
    await RisingEdge(dut.clk)
    assert _as_int(dut.cpu_d_rdata.value) == 0xA5A50001
    _set_bin("data_memory_read_route")
    _set_bin("response_mux_okay")
    dut.cpu_d_arvalid.value = 0
    dut.cpu_d_rready.value = 0

    dut.mem_d_awready.value = 1
    dut.mem_d_wready.value = 1
    dut.mem_d_bvalid.value = 1
    dut.cpu_d_awaddr.value = 0x00000200
    dut.cpu_d_wdata.value = 0x12345678
    dut.cpu_d_wstrb.value = 0xF
    dut.cpu_d_awvalid.value = 1
    dut.cpu_d_wvalid.value = 1
    dut.cpu_d_bready.value = 1
    await RisingEdge(dut.clk)
    assert _as_int(dut.mem_d_awvalid.value) == 1
    assert _as_int(dut.mem_d_wdata.value) == 0x12345678
    assert _as_int(dut.periph_awvalid.value) == 0
    _set_bin("data_memory_write_route")
    dut.cpu_d_awvalid.value = 0
    dut.cpu_d_wvalid.value = 0
    dut.cpu_d_bready.value = 0

    dut.periph_arready.value = 1
    dut.periph_rvalid.value = 1
    dut.periph_rdata.value = 0xBEEFCAFE
    dut.cpu_d_araddr.value = PERIPH_BASE + 0x40
    dut.cpu_d_arvalid.value = 1
    dut.cpu_d_rready.value = 1
    await RisingEdge(dut.clk)
    assert _as_int(dut.periph_arvalid.value) == 1
    assert _as_int(dut.mem_d_arvalid.value) == 0
    await RisingEdge(dut.clk)
    assert _as_int(dut.cpu_d_rdata.value) == 0xBEEFCAFE
    _set_bin("peripheral_read_route")
    dut.cpu_d_arvalid.value = 0
    dut.cpu_d_rready.value = 0

    dut.periph_awready.value = 1
    dut.periph_wready.value = 1
    dut.periph_bvalid.value = 1
    dut.cpu_d_awaddr.value = PERIPH_BASE + 0x80
    dut.cpu_d_wdata.value = 0x55667788
    dut.cpu_d_wstrb.value = 0xF
    dut.cpu_d_awvalid.value = 1
    dut.cpu_d_wvalid.value = 1
    dut.cpu_d_bready.value = 1
    await RisingEdge(dut.clk)
    assert _as_int(dut.periph_awvalid.value) == 1
    assert _as_int(dut.periph_wdata.value) == 0x55667788
    assert _as_int(dut.mem_d_awvalid.value) == 0
    _set_bin("peripheral_write_route")
    if _as_int(dut.route_sel.value) == 1 or _as_int(dut.route_busy.value) == 1:
        _set_bin("route_status_observed")

    _write_coverage("ok", json.loads(os.environ.get("STATIC_COVERAGE_JSON", "{}") or "{}"))
'''


BUS_RUNNER_TEMPLATE = r'''# Auto-generated by workflow/tb-gen/scripts/ssot_to_cocotb.py
from pathlib import Path
import json
import os

from cocotb_test.simulator import run


def test_{ip}_cocotb():
    root = Path(__file__).resolve().parents[2]
    ip = "{ip}"
    filelist = root / "list" / f"{ip}.f"
    sources = []
    for line in filelist.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            sources.append((root.parent / line).resolve())
    build_dir = root / "sim" / "cocotb_build"
    build_dir.mkdir(parents=True, exist_ok=True)
    dump_src = build_dir / f"{ip}_vcd_dump.v"
    dump_src.write_text(
        "module {ip}_vcd_dump();\n"
        "initial begin\n"
        "  $dumpfile(\"{ip}.vcd\");\n"
        "  $dumpvars(0, {ip});\n"
        "end\n"
        "endmodule\n",
        encoding="utf-8",
    )
    sources.append(dump_src)
    os.environ.setdefault("DUT_NAME", ip)
    os.environ.setdefault("COVERAGE_JSON", str(root / "cov" / "coverage.json"))
    os.environ.setdefault("COVERAGE_HISTORY_JSONL", str(root / "cov" / "history.jsonl"))
    os.environ.setdefault("STATIC_COVERAGE_JSON", json.dumps({static_coverage_json}))
    run(
        simulator="icarus",
        verilog_sources=[str(p) for p in sources],
        toplevel=[ip, f"{ip}_vcd_dump"],
        module=f"test_{ip}",
        sim_build=str(build_dir),
        timescale="1ns/1ps",
        waves=False,
        force_compile=True,
    )
'''


def _load_ssot(ip_root: Path, ip: str) -> dict:
    path = ip_root / "yaml" / f"{ip}.ssot.yaml"
    if not path.exists():
        raise SystemExit(f"[ssot-tb] SSOT not found: {path}")
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _is_apb_timer(doc: dict) -> bool:
    regs = (doc.get("registers") or {}).get("register_list") or []
    reg_names = {str(r.get("name") or "").upper() for r in regs if isinstance(r, dict)}
    interfaces = (doc.get("io_list") or {}).get("interfaces") or []
    ports = set()
    for intf in interfaces:
        for p in (intf or {}).get("ports") or []:
            if isinstance(p, dict) and p.get("name"):
                ports.add(str(p["name"]))
    return {"CTRL", "COUNT", "COMPARE", "STATUS"}.issubset(reg_names) and {
        "paddr",
        "psel",
        "penable",
        "pwrite",
        "pwdata",
        "pstrb",
        "prdata",
        "pready",
        "pslverr",
        "irq",
    }.issubset(ports)


def _collect_ports(doc: dict) -> set[str]:
    interfaces = (doc.get("io_list") or {}).get("interfaces") or []
    ports = set()
    for intf in interfaces:
        for p in (intf or {}).get("ports") or []:
            if isinstance(p, dict) and p.get("name"):
                ports.add(str(p["name"]))
    return ports


def _is_cpu(doc: dict) -> bool:
    top = doc.get("top_module") or {}
    ports = _collect_ports(doc)
    cpu_ports = {
        "imem_araddr",
        "imem_arvalid",
        "imem_arready",
        "imem_rdata",
        "imem_rvalid",
        "imem_rready",
        "dmem_awaddr",
        "dmem_awvalid",
        "dmem_wdata",
        "dmem_wvalid",
        "dmem_araddr",
        "dmem_arvalid",
        "dbg_pc",
        "dbg_commit_valid",
    }
    return str(top.get("type") or "").lower() == "cpu" and cpu_ports.issubset(ports)


def _is_bus(doc: dict) -> bool:
    top = doc.get("top_module") or {}
    ports = _collect_ports(doc)
    bus_ports = {
        "cpu_i_araddr", "cpu_i_arvalid", "cpu_i_arready", "cpu_i_rdata", "cpu_i_rvalid",
        "cpu_d_awaddr", "cpu_d_awvalid", "cpu_d_wdata", "cpu_d_wvalid", "cpu_d_bvalid",
        "cpu_d_araddr", "cpu_d_arvalid", "cpu_d_rdata", "cpu_d_rvalid",
        "mem_i_araddr", "mem_i_arvalid", "mem_i_rdata", "mem_i_rvalid",
        "mem_d_awaddr", "mem_d_awvalid", "mem_d_wdata", "mem_d_wvalid", "mem_d_bvalid",
        "periph_awaddr", "periph_awvalid", "periph_wdata", "periph_wvalid", "periph_bvalid",
        "route_busy", "route_sel", "route_error",
    }
    return str(top.get("type") or "").lower() == "bus" and bus_ports.issubset(ports)


def _static_coverage(ip_root: Path, ip: str) -> dict:
    rtl_paths = sorted((ip_root / "rtl").glob("*.sv"))
    total_lines = 0
    branch_total = 0
    fsm_total = 0
    for path in rtl_paths:
        for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = raw.strip()
            if not line or line.startswith("//"):
                continue
            total_lines += 1
            if line.startswith("if ") or line.startswith("if(") or line.startswith("else") or " case " in f" {line} " or line.startswith("case"):
                branch_total += 1
            if "_state" in line or " state" in line or line.startswith("typedef enum"):
                fsm_total += 1
    return {
        "method": "static RTL universe scan plus cocotb functional smoke bins",
        "note": "Static scan defines line/branch/FSM universe only. It is not simulator-instrumented hit coverage.",
        "lines": {"hit": 0, "total": total_lines, "pct": 0.0, "source": "static_universe_only", "instrumented": False},
        "branches": {"hit": 0, "total": branch_total, "pct": 0.0, "source": "static_universe_only", "instrumented": False},
        "fsm": {"hit": 0, "total": fsm_total, "pct": 0.0, "source": "static_universe_only", "instrumented": False},
        "universe": {"lines": total_lines, "branches": branch_total, "fsm": fsm_total},
        "files": [str(p.relative_to(ip_root.parent)) for p in rtl_paths],
    }


def _write_sim_history(ip_root: Path, ip: str, ok: bool, start: float, cov_pct: float) -> None:
    sim_dir = ip_root / "sim"
    sim_dir.mkdir(parents=True, exist_ok=True)
    path = sim_dir / "history.json"
    try:
        doc = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    except Exception:
        doc = {}
    runs = doc.get("runs") if isinstance(doc.get("runs"), list) else []
    runs.insert(
        0,
        {
            "t": datetime.now().strftime("%H:%M:%S"),
            "tests": "9/9" if ok else "0/9",
            "cov": f"{cov_pct:.0f}%",
            "dur": f"{time.time() - start:.1f}s",
            "status": "ok" if ok else "err",
            "kind": "cocotb",
        },
    )
    path.write_text(json.dumps({"runs": runs[:20]}, indent=2), encoding="utf-8")


def _copy_vcd(ip_root: Path, ip: str) -> Path | None:
    sim_dir = ip_root / "sim"
    candidates = sorted((sim_dir / "cocotb_build").rglob("*.vcd"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        return None
    out = sim_dir / f"{ip}.vcd"
    shutil.copy2(candidates[0], out)
    return out


def _copy_results_xml(ip_root: Path) -> Path | None:
    build_dir = ip_root / "sim" / "cocotb_build"
    candidates = sorted(build_dir.rglob("*_results.xml"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        return None
    out = ip_root / "tb" / "cocotb" / "results.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(candidates[0], out)
    return out


def _write_toggle_summary(ip_root: Path, vcd_path: Path | None) -> None:
    cov_dir = ip_root / "cov"
    cov_dir.mkdir(parents=True, exist_ok=True)
    if not vcd_path or not vcd_path.exists():
        (cov_dir / "toggle.json").write_text(json.dumps({"signals": {}, "total_toggles": 0}, indent=2), encoding="utf-8")
        return
    id_to_name = {}
    last = {}
    toggles = {}
    scope = []
    for line in vcd_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[0] == "$scope":
            scope.append(parts[2])
        elif len(parts) >= 2 and parts[0] == "$upscope" and scope:
            scope.pop()
        elif len(parts) >= 5 and parts[0] == "$var":
            code = parts[3]
            name = ".".join(scope + [parts[4]])
            id_to_name[code] = name
            toggles.setdefault(name, 0)
        elif line and line[0] in "01xz":
            code = line[1:]
            if code in id_to_name and last.get(code) != line[0]:
                if code in last:
                    toggles[id_to_name[code]] += 1
                last[code] = line[0]
        elif line and line[0] == "b":
            seg = line.split()
            if len(seg) == 2 and seg[1] in id_to_name and last.get(seg[1]) != seg[0]:
                if seg[1] in last:
                    toggles[id_to_name[seg[1]]] += 1
                last[seg[1]] = seg[0]
    top = dict(sorted(toggles.items(), key=lambda item: item[1], reverse=True)[:50])
    (cov_dir / "toggle.json").write_text(
        json.dumps({"signals": top, "total_toggles": sum(toggles.values())}, indent=2),
        encoding="utf-8",
    )


def _write_coverage_report(ip_root: Path, ip: str) -> None:
    cov_path = ip_root / "cov" / "coverage.json"
    toggle_path = ip_root / "cov" / "toggle.json"
    sim_dir = ip_root / "sim"
    sim_dir.mkdir(parents=True, exist_ok=True)
    try:
        cov = json.loads(cov_path.read_text(encoding="utf-8"))
    except Exception:
        cov = {}
    try:
        toggle = json.loads(toggle_path.read_text(encoding="utf-8"))
    except Exception:
        toggle = {}
    lines = [
        f"# {ip} sim_debug coverage",
        "",
        f"status: {cov.get('status', 'unknown')}",
        f"functional: {(cov.get('functional') or {}).get('pct', 0)}%",
        f"line static universe: {(cov.get('lines') or {}).get('total', 0)} lines; instrumented hits unavailable",
        f"branch static universe: {(cov.get('branches') or {}).get('total', 0)} branches; instrumented hits unavailable",
        f"fsm static universe: {(cov.get('fsm') or {}).get('total', 0)} FSM markers; instrumented hits unavailable",
        f"toggle_signals: {len((toggle.get('signals') or {}))}",
        f"total_toggles: {toggle.get('total_toggles', 0)}",
        "",
        "Note: line/branch/FSM entries are static universe counts unless a later instrumented coverage flow provides hit data.",
    ]
    (sim_dir / "coverage_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    if os.environ.get("ATLAS_ALLOW_FIXED_TB_FALLBACK") != "1":
        raise SystemExit(
            "[ssot-tb] fixed fallback generator is disabled. "
            "Use ATLAS /ssot-tb so tb-gen derives a pyuvm/cocotb environment "
            "from the current SSOT and RTL. Set ATLAS_ALLOW_FIXED_TB_FALLBACK=1 "
            "only for explicit legacy migration."
        )

    ap = argparse.ArgumentParser()
    ap.add_argument("ip")
    ap.add_argument("--root", default=".")
    ns = ap.parse_args()

    root = Path(ns.root).resolve()
    ip = ns.ip
    ip_root = root / ip
    doc = _load_ssot(ip_root, ip)
    is_apb = _is_apb_timer(doc)
    is_cpu = _is_cpu(doc)
    is_bus = _is_bus(doc)
    if not (is_apb or is_cpu or is_bus):
        raise SystemExit("[ssot-tb] unsupported SSOT shape for cocotb fallback; expected APB timer, CPU, or AXI-lite bus ports")

    tb_dir = ip_root / "tb" / "cocotb"
    tb_dir.mkdir(parents=True, exist_ok=True)
    test_path = tb_dir / f"test_{ip}.py"
    runner_path = tb_dir / "test_runner.py"
    if is_bus:
        static_cov = _static_coverage(ip_root, ip)
        test_path.write_text(BUS_TEST_TEMPLATE, encoding="utf-8")
        runner_path.write_text(
            BUS_RUNNER_TEMPLATE.format(ip=ip, static_coverage_json=repr(static_cov)),
            encoding="utf-8",
        )
    elif is_cpu:
        static_cov = _static_coverage(ip_root, ip)
        test_path.write_text(CPU_TEST_TEMPLATE, encoding="utf-8")
        runner_path.write_text(
            CPU_RUNNER_TEMPLATE.format(ip=ip, static_coverage_json=repr(static_cov)),
            encoding="utf-8",
        )
    else:
        test_path.write_text(TEST_TEMPLATE, encoding="utf-8")
        runner_path.write_text(RUNNER_TEMPLATE.format(ip=ip), encoding="utf-8")

    start = time.time()
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", str(runner_path), "--tb=short"],
        cwd=str(ip_root),
        capture_output=True,
        text=True,
        timeout=180,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    sys.stdout.write(output)

    cov_path = ip_root / "cov" / "coverage.json"
    cov_pct = 0.0
    if cov_path.exists():
        try:
            cov_pct = float((json.loads(cov_path.read_text(encoding="utf-8")).get("functional") or {}).get("pct") or 0.0)
        except Exception:
            cov_pct = 0.0
    ok = proc.returncode == 0
    _write_sim_history(ip_root, ip, ok, start, cov_pct)
    vcd_path = _copy_vcd(ip_root, ip)
    results_path = _copy_results_xml(ip_root)
    _write_toggle_summary(ip_root, vcd_path)
    _write_coverage_report(ip_root, ip)

    print(f"[ssot-tb] cocotb {'PASS' if ok else 'FAIL'}: {ip}")
    print(f"[ssot-tb] coverage: functional {cov_pct:.0f}% -> {ip}/cov/coverage.json")
    if vcd_path:
        print(f"[ssot-tb] sim debug VCD: {vcd_path.relative_to(root)}")
    else:
        print("[ssot-tb] sim debug VCD: not generated by simulator")
    print("[ssot-tb] files:")
    for p in [
        test_path,
        runner_path,
        cov_path,
        ip_root / "cov" / "toggle.json",
        ip_root / "sim" / "history.json",
        ip_root / "sim" / "coverage_report.md",
    ]:
        if p.exists():
            print(str(p.relative_to(root)))
    if results_path and results_path.exists():
        print(str(results_path.relative_to(root)))
    return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
