#!/usr/bin/env python3
"""write_sta_post_tcl.py — Generate <ip>/sta-post/run.tcl with read_spef.

Python port of write_sta_post_tcl.sh. The generated run.tcl is byte-identical to
the bash original, including the literal Tcl ``$scan_en_ports`` variable refs
(the bash heredoc escapes them as ``\\$``).

Usage: write_sta_post_tcl.py <ip>
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sh_port_common import load_pdk_env, resolve_top  # noqa: E402


def main(argv: list[str]) -> int:
    if not argv and os.environ.get("HOOK_CMD_ARGS"):
        argv = os.environ["HOOK_CMD_ARGS"].split()

    env = load_pdk_env()

    ip = argv[0] if argv else ""
    if not ip:
        print("[STA-POST] usage: write_sta_post_tcl.py <ip>", file=sys.stderr)
        return 2

    routed_v = f"{ip}/pnr/out/routed.v"
    routed_spef = f"{ip}/pnr/out/routed.spef"
    sdc = f"{ip}/sta/out/{ip}.sdc"
    tcl = f"{ip}/sta-post/run.tcl"
    out = f"{ip}/sta-post/out"
    ssot = f"{ip}/yaml/{ip}.ssot.yaml"
    Path(f"{ip}/sta-post").mkdir(parents=True, exist_ok=True)
    Path(out).mkdir(parents=True, exist_ok=True)

    if not (Path(routed_v).is_file() and Path(routed_v).stat().st_size > 0):
        print(f"[STA-POST] missing {routed_v}", file=sys.stderr)
        return 5
    if not (Path(routed_spef).is_file() and Path(routed_spef).stat().st_size > 0):
        print(f"[STA-POST] missing {routed_spef}", file=sys.stderr)
        return 5
    if not Path(sdc).is_file():
        print(f"[STA-POST] missing {sdc}", file=sys.stderr)
        return 5
    sky130_lib = env.get("SKY130_LIB") or os.environ.get("SKY130_LIB", "")
    if not sky130_lib or not os.access(sky130_lib, os.R_OK):
        print(
            f"[STA-POST MISSING PDK] $SKY130_LIB unreadable: {sky130_lib}",
            file=sys.stderr,
        )
        return 4

    top = resolve_top(ip, ssot)

    tcl_text = (
        "# Generated by workflow/sta-post/scripts/write_sta_post_tcl.sh\n"
        f"# IP: {ip}   top: {top}   mode: post_route (parasitic-aware)\n"
        f"read_liberty {sky130_lib}\n"
        f"read_verilog {routed_v}\n"
        f"link_design {top}\n"
        f"read_sdc {sdc}\n"
        f"read_spef {routed_spef}\n"
        "\n"
        "# Functional-mode case analysis when scan ports exist.\n"
        "set scan_en_ports [get_ports -quiet scan_en]\n"
        "if {[llength $scan_en_ports] > 0} {\n"
        "  set_case_analysis 0 $scan_en_ports\n"
        "}\n"
        "\n"
        f"report_checks -path_delay max -group_count 5 -fields {{slew capacitance input_pins nets fanout}} > {out}/setup.rpt\n"
        f"report_checks -path_delay min -group_count 5 -fields {{slew capacitance input_pins nets fanout}} > {out}/hold.rpt\n"
        f"report_checks -path_delay min_max -group_count 10                                                > {out}/timing.rpt\n"
        f"report_clock_skew                                                                                > {out}/skew.rpt\n"
        "report_wns\n"
        "report_tns\n"
        "exit\n"
    )
    Path(tcl).write_text(tcl_text, encoding="utf-8")
    print(f"[STA-POST] wrote {tcl} (top={top})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
