#!/usr/bin/env bash
# new_ip_emit_chain.sh — after /to-ssot has produced <ip>/yaml/<ip>.ssot.yaml,
# run the proven emit chain: FL model -> equivalence goals ->
# IP evidence contract -> cocotb scoreboard -> pre-sim TB Python compile ->
# simulation.
#
# Usage:
#   bash "$ATLAS_WORKFLOW_ROOT/ssot-gen/scripts/new_ip_emit_chain.sh" <ip> [--root <ip-parent>] [--workflow-root <workflow-dir>] [--ip-root <ip-dir>]
#
# --workflow-root points at common_ai_agent/workflow.
# --root/ATLAS_PROJECT_ROOT points at the parent directory containing <ip>.
# --ip-root/ATLAS_IP_ROOT can pin the active IP directory directly.
#
# Prereqs (under --root):
#   - <ip>/yaml/<ip>.ssot.yaml
#   - <ip>/rtl/<ip>.sv
#   - <ip>/rtl/rtl_contract.json
#   - <ip>/list/<ip>.f  (auto-generated from <ip>/rtl/*.sv if missing)
#
# Exit:
#   0 = cocotb TESTS=1 PASS=1 FAIL=0  AND  CL co-sim N/N 100% match
#   non-zero = some emit step or cocotb failed; stderr carries the cause.

set -u

IP=""
ROOT="${ATLAS_PROJECT_ROOT:-${ATLAS_ROOT:-}}"
WORKFLOW_ROOT="${ATLAS_WORKFLOW_ROOT:-}"
IP_ROOT="${ATLAS_IP_ROOT:-}"
while [ $# -gt 0 ]; do
    case "$1" in
        --root) ROOT="${2:-}"; shift 2 ;;
        --root=*) ROOT="${1#--root=}"; shift ;;
        --workflow-root|--workflow_root) WORKFLOW_ROOT="${2:-}"; shift 2 ;;
        --workflow-root=*|--workflow_root=*) WORKFLOW_ROOT="${1#*=}"; shift ;;
        --ip-root|--ip_root) IP_ROOT="${2:-}"; shift 2 ;;
        --ip-root=*|--ip_root=*) IP_ROOT="${1#*=}"; shift ;;
        --help|-h)
            sed -n '2,21p' "$0"; exit 0 ;;
        *)
            [ -z "$IP" ] && IP="$1"
            shift ;;
    esac
done

if [ -n "$IP_ROOT" ]; then
    [ -d "$IP_ROOT" ] || { echo "[emit-chain] FAIL: --ip-root $IP_ROOT does not exist" >&2; exit 1; }
    IP_ROOT="$(cd "$IP_ROOT" && pwd)"
    [ -n "$IP" ] || IP="$(basename "$IP_ROOT")"
    [ -n "$ROOT" ] || ROOT="$(dirname "$IP_ROOT")"
fi

if [ -z "$IP" ]; then
    echo "[emit-chain] usage: $0 <ip_name> [--root <ip-parent>] [--workflow-root <workflow-dir>] [--ip-root <ip-dir>]" >&2
    exit 2
fi

if [ -z "$ROOT" ]; then
    ROOT="$PWD"
fi
if [ ! -d "$ROOT" ]; then
    echo "[emit-chain] FAIL: --root $ROOT does not exist" >&2
    exit 1
fi
ROOT="$(cd "$ROOT" && pwd)"

if [ -z "$WORKFLOW_ROOT" ]; then
    WORKFLOW_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
fi
if [ -d "$WORKFLOW_ROOT/workflow/ssot-gen" ]; then
    WORKFLOW_ROOT="$(cd "$WORKFLOW_ROOT/workflow" && pwd)"
elif [ -d "$WORKFLOW_ROOT/ssot-gen" ]; then
    WORKFLOW_ROOT="$(cd "$WORKFLOW_ROOT" && pwd)"
else
    echo "[emit-chain] FAIL: --workflow-root $WORKFLOW_ROOT does not contain ssot-gen/" >&2
    exit 1
fi

echo "[emit-chain] resolved PROJECT_ROOT = $ROOT"
echo "[emit-chain] resolved WORKFLOW_ROOT = $WORKFLOW_ROOT"

SSOT="${ROOT}/${IP}/yaml/${IP}.ssot.yaml"
if [ ! -f "$SSOT" ]; then
    echo "[emit-chain] FAIL: $SSOT missing — run /to-ssot first" >&2
    exit 1
fi

# Auto-generate filelist if missing (P3). Sourced from <ip>/rtl/*.sv .
FILELIST="${ROOT}/${IP}/list/${IP}.f"
if [ ! -f "$FILELIST" ]; then
    RTL_DIR="${ROOT}/${IP}/rtl"
    if [ ! -d "$RTL_DIR" ]; then
        echo "[emit-chain] FAIL: ${RTL_DIR} missing — cannot synthesize filelist" >&2
        exit 1
    fi
    mkdir -p "${ROOT}/${IP}/list"
    {
        echo "// Auto-generated by new_ip_emit_chain.sh — DUT-only filelist"
        echo "+incdir+rtl"
        for sv in "${RTL_DIR}"/*.sv; do
            [ -f "$sv" ] || continue
            echo "rtl/$(basename "$sv")"
        done
    } > "$FILELIST"
    echo "[emit-chain] auto-generated ${IP}/list/${IP}.f ($(wc -l < "$FILELIST" | tr -d ' ') lines)"
fi

step() {
    local label="$1"; shift
    echo "[emit-chain] ${label}"
    if ! "$@"; then
        echo "[emit-chain] FAIL at ${label}" >&2
        exit 1
    fi
}

step "1/6 emit_fl_model"          python3 "${WORKFLOW_ROOT}/fl-model-gen/scripts/emit_fl_model.py"          "$IP" --root "$ROOT"
step "2/6 emit_equivalence_goals" python3 "${WORKFLOW_ROOT}/fl-model-gen/scripts/emit_equivalence_goals.py" "$IP" --root "$ROOT"
step "3/6 derive_ip_contract"     python3 "${WORKFLOW_ROOT}/ip-contract/scripts/derive_ip_contract.py"      "$IP" --root "$ROOT"
step "4/6 emit_goal_scoreboard"   python3 "${WORKFLOW_ROOT}/tb-gen/scripts/emit_goal_scoreboard_cocotb.py"  "$IP" --root "$ROOT"
step "5/6 tb_python_compile"      python3 "${WORKFLOW_ROOT}/tb-gen/scripts/check_tb_python_compile.py"       "$IP" --root "$ROOT"
step "6/6 cocotb sim"             python3 "${ROOT}/${IP}/tb/cocotb/test_runner.py"

echo "[emit-chain] done — inspect ${IP}/sim/scoreboard_events.jsonl and CL_COSIM line above"
