#!/usr/bin/env python3
"""Render Human-vs-LLM authority diagram as Mermaid (.mmd) and optional SVG.

Reads <ip>/governance/authority.json (produced by emit_authority_manifest.py)
and emits <ip>/governance/loop_map.mmd. If `mmdc` (mermaid-cli) is on PATH,
also renders <ip>/governance/loop_map.svg. Pure Python; no extra deps.

Usage:
  python3 workflow/fl-model-gen/scripts/emit_loop_map.py <ip> --root .
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any


def _safe(text: str) -> str:
    return (
        str(text or "")
        .replace("\"", "'")
        .replace("\n", " ")
        .replace("[", "(")
        .replace("]", ")")
        .strip()
    )


def _mermaid(manifest: dict[str, Any]) -> str:
    gates = manifest.get("human_gates") or []
    loops = manifest.get("llm_loops") or []
    rules = manifest.get("operating_rules") or []
    ip = manifest.get("ip", "ip")

    lines: list[str] = []
    lines.append("%% Auto-generated by emit_loop_map.py — Human-LLM authority map")
    lines.append(f"%% IP: {ip}")
    lines.append("flowchart LR")
    lines.append("    classDef approved fill:#0a0,color:#fff,stroke:#040;")
    lines.append("    classDef pending  fill:#fa0,color:#000,stroke:#840;")
    lines.append("    classDef blocked  fill:#a00,color:#fff,stroke:#400;")
    lines.append("    classDef loop     fill:#06c,color:#fff,stroke:#024;")
    lines.append("")

    lines.append("    subgraph H[\"HUMAN GATES (locked truth)\"]")
    lines.append("        direction TB")
    prev_gid = None
    for gate in gates:
        gid = gate.get("id", "G?")
        title = _safe(gate.get("title", ""))
        status = gate.get("status", "pending")
        node = f"{gid}[\"{gid} {title}\"]:::{status}"
        lines.append(f"        {node}")
        if prev_gid is not None:
            lines.append(f"        {prev_gid} --> {gid}")
        prev_gid = gid
    lines.append("    end")
    lines.append("")

    lines.append("    subgraph L[\"LLM LOOPS (machine evidence)\"]")
    lines.append("        direction TB")
    for lp in loops:
        lid = lp.get("id", "L?")
        title = _safe(lp.get("title", ""))
        node = f"{lid}[\"{lid} {title}\"]:::loop"
        lines.append(f"        {node}")
    lines.append("    end")
    lines.append("")

    # Escalation edges — loop → gate when failure forces human review.
    escalations = [
        ("L1", "G4", "FL drift?"),
        ("L2", "G7", "module owner change?"),
        ("L3", "G5", "coverage goal weaken?"),
        ("L5", "G3", "interface contract?"),
        ("L6", "G6", "perf target change?"),
        ("L7", "G8", "PPA tradeoff?"),
        ("L8", "G7", "arch refactor?"),
        ("L9", "G9", "signoff readiness"),
    ]
    for src, dst, label in escalations:
        if any(g.get("id") == dst for g in gates) and any(l.get("id") == src for l in loops):
            lines.append(f"    {src} -.\"{label}\".-> {dst}")

    if rules:
        lines.append("")
        lines.append(f"    R[\"R1..R{len(rules)} operating rules — see authority.md\"]")
        lines.append("    H -. governs .- R")
        lines.append("    L -. constrained_by .- R")

    return "\n".join(lines) + "\n"


def _try_render_svg(mmd_path: Path, svg_path: Path) -> tuple[bool, str]:
    mmdc = shutil.which("mmdc") or shutil.which("npx")
    if mmdc is None:
        return False, "mmdc/npx not on PATH"
    cmd = [mmdc, "-i", str(mmd_path), "-o", str(svg_path)] if mmdc.endswith("mmdc") else \
          [mmdc, "-y", "@mermaid-js/mermaid-cli", "-i", str(mmd_path), "-o", str(svg_path)]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=60,
        )
        if result.returncode == 0 and svg_path.is_file():
            return True, "rendered"
        return False, (result.stderr or result.stdout or "non-zero exit").strip()[:200]
    except Exception as exc:
        return False, f"{type(exc).__name__}: {exc}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("ip")
    parser.add_argument("--root", default=".")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    ip_dir = root / args.ip
    auth_path = ip_dir / "governance" / "authority.json"
    if not auth_path.is_file():
        raise SystemExit(f"missing authority.json — run emit_authority_manifest.py first: {auth_path}")
    manifest = json.loads(auth_path.read_text(encoding="utf-8"))

    mmd = _mermaid(manifest)
    out_dir = ip_dir / "governance"
    out_dir.mkdir(parents=True, exist_ok=True)
    mmd_path = out_dir / "loop_map.mmd"
    mmd_path.write_text(mmd, encoding="utf-8")

    svg_path = out_dir / "loop_map.svg"
    svg_ok, svg_note = _try_render_svg(mmd_path, svg_path)

    summary = {
        "schema_version": 1,
        "type": "loop_map_summary",
        "ip": args.ip,
        "mmd": str(mmd_path.relative_to(ip_dir)),
        "svg": str(svg_path.relative_to(ip_dir)) if svg_ok else None,
        "svg_status": svg_note,
        "gates": len(manifest.get("human_gates") or []),
        "loops": len(manifest.get("llm_loops") or []),
        "rules": len(manifest.get("operating_rules") or []),
    }
    (out_dir / "loop_map.summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    print(f"[emit_loop_map] {args.ip} mmd={mmd_path}")
    print(f"[emit_loop_map] svg_status: {svg_note}{' (ok)' if svg_ok else ''}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
