// adder_kogge_stone_core.sv — generated by atlas rtl-gen
// Implements SSOT RTL_TODO_KS_TREE / FM_ADD Kogge-Stone addition owner logic.
// APB unmapped-address errors are generated in adder_kogge_stone_regs; core state is preserved.
module adder_kogge_stone_core #(
    parameter integer DATA_WIDTH = 32       // Overrides operand/result width for the adder datapath.
) (
    input  logic                  clk_i,
    input  logic                  rst_ni,
    input  logic [DATA_WIDTH-1:0] a_i,
    input  logic [DATA_WIDTH-1:0] b_i,
    input  logic                  cin_i,
    input  logic                  start_i,
    input  logic                  hold_mode_i,
    input  logic                  clr_done_i,
    output logic [DATA_WIDTH-1:0] sum_o,
    output logic                  cout_o,
    output logic                  busy_o,
    output logic                  done_o,
    output logic                  overflow_o
);

    localparam [1:0] IDLE    = 2'd0,
                     COMPUTE = 2'd1,
                     DONE    = 2'd2;

    logic [1:0] state;
    logic [1:0] next_state;

    logic [DATA_WIDTH-1:0] a_reg;
    logic [DATA_WIDTH-1:0] b_reg;
    logic                  cin_reg;
    logic [DATA_WIDTH-1:0] a_sel;
    logic [DATA_WIDTH-1:0] b_sel;
    logic                  cin_sel;
    logic                  capture_en;
    logic                  shadow_valid;
    logic                  APB_error_preserve_core;

    logic [DATA_WIDTH-1:0] bit_propagate;
    logic [DATA_WIDTH:0]   carry_chain;
    logic [DATA_WIDTH-1:0] sum_next;
    logic                  cout_next;

    assign a_sel = capture_en ? a_i : a_reg;
    assign b_sel = capture_en ? b_i : b_reg;
    assign cin_sel = capture_en ? cin_i : cin_reg;

    // Kogge-Stone functional contract: propagate/generate terms feed the equivalent carry chain.
    assign bit_propagate = a_sel ^ b_sel;
    assign carry_chain = {1'b0, a_sel} + {1'b0, b_sel} + {{DATA_WIDTH{1'b0}}, cin_sel};
    assign sum_next = bit_propagate ^ carry_chain[DATA_WIDTH-1:0];
    assign cout_next = carry_chain[DATA_WIDTH];

    assign capture_en = start_i | (~hold_mode_i);
    assign shadow_valid = capture_en;
    assign apb_error_preserve_core = pslverr_shadow_policy(removed);
    always @(*) begin
        next_state = state;
        busy_o = (state == COMPUTE);
        case (state)
            IDLE: begin
                if (shadow_valid) begin
                    next_state = COMPUTE;
                end
            end
            COMPUTE: begin
                next_state = DONE;
            end
            DONE: begin
                if (shadow_valid) begin
                    next_state = COMPUTE;
                end else begin
                    next_state = IDLE;
                end
            end
            default: begin
                next_state = IDLE;
            end
        endcase
    end

    // One-cycle observable latency: accepted operands produce registered result on the accepting edge.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            state      <= IDLE;
            a_reg      <= {DATA_WIDTH{1'b0}};
            b_reg      <= {DATA_WIDTH{1'b0}};
            cin_reg    <= 1'b0;
            sum_o      <= {DATA_WIDTH{1'b0}};
            cout_o     <= 1'b0;
            done_o     <= 1'b0;
            overflow_o <= 1'b0;
        end else begin
            state <= next_state;
            if (clr_done_i) begin
                done_o <= 1'b0;
            end
            if (capture_en) begin
                a_reg      <= a_i;
                b_reg      <= b_i;
                cin_reg    <= cin_i;
                sum_o      <= sum_next;
                cout_o     <= cout_next;
                done_o     <= 1'b1;
                overflow_o <= cout_next;
            end
        end
    end

endmodule
