// adder_kogge_stone.sv — generated by atlas rtl-gen
// Implements RTL_TODO_TOP: SSOT top IO, APB CSR integration, and core wiring.
module adder_kogge_stone #(
    parameter integer DATA_WIDTH = 32,      // Operand and result width exposed on a_i/b_i/sum_o.
    parameter integer ADDR_WIDTH = 8,       // APB paddr width from SSOT io_list.
    parameter integer APB_DATA_WIDTH = 32   // APB pwdata/prdata width from SSOT register map.
) (
    input  logic                      PCLK,
    input  logic                      PRESETn,
    input  logic [ADDR_WIDTH-1:0]     paddr,
    input  logic                      psel,
    input  logic                      penable,
    input  logic                      pwrite,
    input  logic [APB_DATA_WIDTH-1:0] pwdata,
    output logic [APB_DATA_WIDTH-1:0] prdata,
    output logic                      pready,
    output logic                      pslverr,
    input  logic [DATA_WIDTH-1:0]     a_i,
    input  logic [DATA_WIDTH-1:0]     b_i,
    input  logic                      cin_i,
    output logic [DATA_WIDTH-1:0]     sum_o,
    output logic                      cout_o
);

    logic [DATA_WIDTH-1:0] a_shadow;
    logic [DATA_WIDTH-1:0] b_shadow;
    logic                  cin_shadow;
    logic                  start_pulse;
    logic                  hold_mode;
    logic                  clr_done_pulse;
    logic                  busy_status;
    logic                  done_status;
    logic                  overflow_status;
    logic [DATA_WIDTH-1:0] core_a;
    logic [DATA_WIDTH-1:0] core_b;
    logic                  core_cin;
    logic                  ext_activity;
    logic                  core_start;
    logic [DATA_WIDTH-1:0] sum_result;
    logic                  cout_result;

    // SSOT permits either APB shadows or top-level datapath ports; start selects APB shadows.
    assign ext_activity = (~hold_mode) & (|a_i | |b_i | cin_i);
    assign core_start = start_pulse | ext_activity;
    assign core_a = start_pulse ? a_shadow : a_i;
    assign core_b = start_pulse ? b_shadow : b_i;
    assign core_cin = start_pulse ? cin_shadow : cin_i;

    assign sum_o = sum_result;
    assign cout_o = cout_result;

    adder_kogge_stone_regs #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .APB_DATA_WIDTH(APB_DATA_WIDTH)
    ) u_regs (
        .clk_i(PCLK),
        .rst_ni(PRESETn),
        .paddr_i(paddr),
        .psel_i(psel),
        .penable_i(penable),
        .pwrite_i(pwrite),
        .pwdata_i(pwdata),
        .prdata_o(prdata),
        .pready_o(pready),
        .pslverr_o(pslverr),
        .a_shadow_o(a_shadow),
        .b_shadow_o(b_shadow),
        .cin_shadow_o(cin_shadow),
        .start_pulse_o(start_pulse),
        .hold_mode_o(hold_mode),
        .clr_done_pulse_o(clr_done_pulse),
        .sum_result_i(sum_result),
        .cout_result_i(cout_result),
        .busy_i(busy_status),
        .done_i(done_status),
        .overflow_i(overflow_status)
    );

    adder_kogge_stone_core #(
        .DATA_WIDTH(DATA_WIDTH)
    ) u_core (
        .clk_i(PCLK),
        .rst_ni(PRESETn),
        .a_i(core_a),
        .b_i(core_b),
        .cin_i(core_cin),
        .start_i(core_start),
        .hold_mode_i(hold_mode),
        .clr_done_i(clr_done_pulse),
        .sum_o(sum_result),
        .cout_o(cout_result),
        .busy_o(busy_status),
        .done_o(done_status),
        .overflow_o(overflow_status)
    );

endmodule
