// adder_kogge_stone_regs.sv — generated by atlas rtl-gen
// Implements RTL_TODO_REGS: zero-wait-state APB-lite CSR decode and shadow registers.
module adder_kogge_stone_regs #(
    parameter integer DATA_WIDTH = 32,      // Operand shadow width used by A_DATA/B_DATA and SUM_RESULT.
    parameter integer ADDR_WIDTH = 8,       // APB byte-address width for the 256B register aperture.
    parameter integer APB_DATA_WIDTH = 32   // SSOT register map width.
) (
    input  logic                      clk_i,
    input  logic                      rst_ni,
    input  logic [ADDR_WIDTH-1:0]     paddr_i,
    input  logic                      psel_i,
    input  logic                      penable_i,
    input  logic                      pwrite_i,
    input  logic [APB_DATA_WIDTH-1:0] pwdata_i,
    output logic [APB_DATA_WIDTH-1:0] prdata_o,
    output logic                      pready_o,
    output logic                      pslverr_o,
    output logic [DATA_WIDTH-1:0]     a_shadow_o,
    output logic [DATA_WIDTH-1:0]     b_shadow_o,
    output logic                      cin_shadow_o,
    output logic                      start_pulse_o,
    output logic                      hold_mode_o,
    output logic                      clr_done_pulse_o,
    input  logic [DATA_WIDTH-1:0]     sum_result_i,
    input  logic                      cout_result_i,
    input  logic                      busy_i,
    input  logic                      done_i,
    input  logic                      overflow_i
);

    localparam [ADDR_WIDTH-1:0] ADDR_CONTROL     = 8'h00;
    localparam [ADDR_WIDTH-1:0] ADDR_STATUS      = 8'h04;
    localparam [ADDR_WIDTH-1:0] ADDR_A_DATA      = 8'h08;
    localparam [ADDR_WIDTH-1:0] ADDR_B_DATA      = 8'h0c;
    localparam [ADDR_WIDTH-1:0] ADDR_CIN         = 8'h10;
    localparam [ADDR_WIDTH-1:0] ADDR_SUM_RESULT  = 8'h14;
    localparam [ADDR_WIDTH-1:0] ADDR_COUT_RESULT = 8'h18;
    localparam [ADDR_WIDTH-1:0] ADDR_CONFIG      = 8'h1c;

    logic apb_access;
    logic apb_write;
    logic apb_read;
    logic valid_addr;
    logic [APB_DATA_WIDTH-1:0] read_mux;
    logic [APB_DATA_WIDTH-1:0] control_read;
    logic [APB_DATA_WIDTH-1:0] status_read;
    logic [APB_DATA_WIDTH-1:0] cin_read;
    logic [APB_DATA_WIDTH-1:0] cout_read;
    logic [APB_DATA_WIDTH-1:0] config_read;
    logic [DATA_WIDTH-1:0]     pwdata_operand;

    assign apb_access = psel_i & penable_i;
    assign apb_write = apb_access & pwrite_i;
    assign apb_read = apb_access & (~pwrite_i);
    assign pready_o = 1'b1;
    assign pslverr_o = apb_access & (~valid_addr);
    assign pwdata_operand = pwdata_i[DATA_WIDTH-1:0];

    assign control_read = {{(APB_DATA_WIDTH-3){1'b0}}, 1'b0, hold_mode_o, 1'b0};
    assign status_read = {{(APB_DATA_WIDTH-3){1'b0}}, overflow_i, done_i, busy_i};
    assign cin_read = {{(APB_DATA_WIDTH-1){1'b0}}, cin_shadow_o};
    assign cout_read = {{(APB_DATA_WIDTH-1){1'b0}}, cout_result_i};
    assign config_read = {{(APB_DATA_WIDTH-8){1'b0}}, DATA_WIDTH[7:0]};

    // APB decode covers exactly the SSOT register_list; all other addresses report ERR_APB_OOB.
    always @(*) begin
        valid_addr = 1'b0;
        read_mux = {APB_DATA_WIDTH{1'b0}};
        case (paddr_i)
            ADDR_CONTROL: begin
                valid_addr = 1'b1;
                read_mux = control_read;
            end
            ADDR_STATUS: begin
                valid_addr = 1'b1;
                read_mux = status_read;
            end
            ADDR_A_DATA: begin
                valid_addr = 1'b1;
                read_mux = a_shadow_o;
            end
            ADDR_B_DATA: begin
                valid_addr = 1'b1;
                read_mux = b_shadow_o;
            end
            ADDR_CIN: begin
                valid_addr = 1'b1;
                read_mux = cin_read;
            end
            ADDR_SUM_RESULT: begin
                valid_addr = 1'b1;
                read_mux = sum_result_i;
            end
            ADDR_COUT_RESULT: begin
                valid_addr = 1'b1;
                read_mux = cout_read;
            end
            ADDR_CONFIG: begin
                valid_addr = 1'b1;
                read_mux = config_read;
            end
            default: begin
                valid_addr = 1'b0;
                read_mux = {APB_DATA_WIDTH{1'b0}};
            end
        endcase
    end

    assign prdata_o = apb_read ? read_mux : {APB_DATA_WIDTH{1'b0}};

    // RW/W1C register side effects: start and clr_done are self-clearing pulses, hold_mode persists.
    always @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            a_shadow_o       <= {DATA_WIDTH{1'b0}};
            b_shadow_o       <= {DATA_WIDTH{1'b0}};
            cin_shadow_o     <= 1'b0;
            start_pulse_o    <= 1'b0;
            hold_mode_o      <= 1'b0;
            clr_done_pulse_o <= 1'b0;
        end else begin
            start_pulse_o    <= 1'b0;
            clr_done_pulse_o <= 1'b0;
            if (apb_write & valid_addr) begin
                case (paddr_i)
                    ADDR_CONTROL: begin
                        start_pulse_o    <= pwdata_i[0];
                        hold_mode_o      <= pwdata_i[1];
                        clr_done_pulse_o <= pwdata_i[2];
                    end
                    ADDR_A_DATA: begin
                        a_shadow_o <= pwdata_operand;
                    end
                    ADDR_B_DATA: begin
                        b_shadow_o <= pwdata_operand;
                    end
                    ADDR_CIN: begin
                        cin_shadow_o <= pwdata_i[0];
                    end
                    default: begin
                        start_pulse_o    <= 1'b0;
                        clr_done_pulse_o <= 1'b0;
                    end
                endcase
            end
        end
    end

endmodule
