// pipeline.jsx — Full IP lifecycle pipeline view

const FILE_CONTENTS = {
  'spi_master_requirements.md': `# spi_master · Requirements\n\n## §1 Overview\nSPI master controller, single-master, up to 4 chip-selects.\nHost interface: APB. Frequency target: ≤ 50 MHz sclk.\n\n## §2 Use cases\n- Sensor polling (LIS3DH, BMP280)\n- Flash configuration (W25Q series)\n- Low-latency control bursts\n\n## §3 Functional reqs\n- R-01  Support CPOL/CPHA modes 0..3\n- R-02  Programmable BAUD_DIV (1..255)\n- R-03  TX/RX FIFO depth 8\n- R-04  Interrupt on TX_EMPTY, RX_FULL, DONE\n- R-05  4 independent CS lines, software-selected\n- R-06  Async reset, single posedge clock domain (pclk)`,
  'spi_master_mas.md': `# spi_master · Micro Architecture Spec\n\n## §1 Block diagram\n        ┌──────────┐    ┌──────────┐\n   APB→ │ reg_file │ →  │ ctrl_fsm │ → SHIFT\n        └──────────┘    └──────────┘\n\n## §2 Register map\nADDR  NAME      ACCESS  DESCRIPTION\n0x00  CTRL      RW      enable, cpol, cpha, cs_sel\n0x04  STAT      R       tx_empty, rx_full, done\n0x08  DATA_TX   W       tx fifo push\n0x0C  DATA_RX   R       rx fifo pop\n0x10  BAUD_DIV  RW      sclk = pclk / (BAUD_DIV+1)\n0x14  IRQ_EN    RW      mask\n\n## §5 FSM\nIDLE → LOAD → SHIFT → COMPLETE → IDLE\n\n## §9 DV plan\n12 scenarios · 4 coverage groups · target 95%`,
  'spi_master.sv': `// spi_master.sv — generated by rtl_gen v3\nmodule spi_master #(\n    parameter int CS_W = 4,\n    parameter int FIFO_D = 8\n) (\n    input  logic        pclk,\n    input  logic        resetn,\n    // APB\n    input  logic [7:0]  paddr,\n    input  logic        psel, penable, pwrite,\n    input  logic [31:0] pwdata,\n    output logic [31:0] prdata,\n    output logic        pready,\n    // SPI\n    output logic        sclk, mosi,\n    input  logic        miso,\n    output logic [CS_W-1:0] ss_n,\n    // IRQ\n    output logic        irq\n);\n  // ── FSM: spi_master transfer cycle ──\n  typedef enum logic [1:0] {\n    IDLE, LOAD, SHIFT, COMPLETE\n  } state_t;\n\n  state_t cur, nxt;\n  logic [3:0] bit_cnt;\n\n  always_ff @(posedge pclk or negedge resetn) begin\n    if (!resetn) begin\n      cur     <= IDLE;\n      bit_cnt <= '0;\n    end\n    else cur <= nxt;\n  end\n\n  // … 380 more lines …\nendmodule`,
  'tb_spi_master.sv': `// tb_spi_master.sv — generated by tb_gen\n\`timescale 1ns/1ps\nmodule tb_spi_master;\n  logic pclk = 0; always #5 pclk = ~pclk;\n  logic resetn;\n  // DUT instance\n  spi_master u_dut (.*);\n  // APB BFM, SPI slave model, scoreboard hooks\n  initial begin\n    resetn = 0; #20 resetn = 1;\n    run_test();\n    $finish;\n  end\nendmodule`,
  'tc_spi_master.sv': `// tc_spi_master.sv — 12 test cases\nclass tc_cpol0_cpha0 extends tc_base;\n  task body(); /* mode 0 transfer */ endtask\nendclass\nclass tc_b2b_transfer extends tc_base;\n  task body(); /* back-to-back */ endtask\nendclass\n// + 10 more`,
  'lint_report.txt': `verilator 5.024 · spi_master.sv\n──────────────────────────────────────────\n%Warning-WIDTHEXPAND: spi_master.sv:87  Operator ASSIGN expects 8 bits on RHS, got 4\n%Warning-UNUSED:      spi_master.sv:124 Signal is not used: 'cpha_sync_d2'\n%Warning-CASEINCOMPLETE: spi_master.sv:198 Case values not handled: COMPLETE\n──────────────────────────────────────────\n3 warnings · 0 errors · 412 lines scanned`,
};

const Pipeline = ({ dir, onScreen, ip }) => {
  const stages = window.FLOW_STAGES;
  const ip_data = window.ACTIVE_IP;
  const tree = window.FILE_TREE;
  const [hover, setHover] = React.useState(null);
  const [openFile, setOpenFile] = React.useState(null);
  const [rightTab, setRightTab] = React.useState('todo'); // todo | lint

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '280px 1fr 360px', gap: 16, padding: 16, height: '100%', overflow: 'hidden' }}>
      {/* Left: file tree */}
      <div className="box" style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
        <div className="box-h">
          <span>▸ IP files</span>
          <span style={{ flex: 1 }} />
          <span className="acc" style={{ fontSize: 11, letterSpacing: 0, textTransform: 'none' }}>{ip}</span>
        </div>
        <div style={{ flex: 1, overflow: 'auto', padding: '8px 0' }}>
          {tree.map((n, i) => (
            <div key={i}
              className={n.active ? 'frow active' : 'frow'}
              style={{ paddingLeft: 8 + n.depth * 16, opacity: n.dim ? 0.55 : 1 }}
            >
              <span className="fr-icon">
                {n.type === 'dir' ? (n.expanded ? '▾' : '▸') : (
                  n.ext === 'sv' ? <span className="cyan">◆</span> :
                  n.ext === 'md' ? <span className="mag">◆</span> :
                  <span className="mute">◆</span>
                )}
              </span>
              <span className="trunc" style={{ fontWeight: n.active ? 500 : 400 }}>
                {n.type === 'dir' ? <span className="dim">{n.name}</span> : n.name}
              </span>
              <span className="mute" style={{ fontSize: 11 }}>{n.size || ''}</span>
            </div>
          ))}
        </div>
        <div style={{ borderTop: '1px solid var(--line)', padding: '8px 12px', fontSize: 11, color: 'var(--fg-mute)', display: 'flex', justifyContent: 'space-between' }}>
          <span>6 dirs · 4 files</span>
          <span><Kbd>@</Kbd> complete path</span>
        </div>
      </div>

      {/* Center: pipeline visualization */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16, overflow: 'hidden' }}>
        <div className="box" style={{ padding: '16px 20px' }}>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: 12, marginBottom: 4 }}>
            <span style={{ fontSize: 24, fontWeight: 600, letterSpacing: '-0.01em' }}>{ip_data.name}</span>
            <Pill kind="run">{ip_data.status}</Pill>
            <span className="mute" style={{ fontSize: 11 }}>iter 14/100 · 47.2k tokens</span>
            <span style={{ flex: 1 }} />
            <button className="btn" onClick={() => onScreen('workspace')}><span className="ascii-spin"></span> View live loop</button>
          </div>
          <div className="mute" style={{ fontSize: 12 }}>SSOT v3 · Started today 14:02 · 4 stages</div>
        </div>

        {/* Big pipeline */}
        <div className="box" style={{ flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0, overflow: 'hidden' }}>
          <div className="box-h">
            <span>▸ Lifecycle pipeline</span>
            <span className="mute" style={{ fontSize: 10, letterSpacing: 0, textTransform: 'none' }}>SSOT → RTL → Lint → TB(Sim)</span>
            <span style={{ flex: 1 }} />
            <span className="mute" style={{ fontSize: 10, textTransform: 'none', letterSpacing: 0 }}>
              <Kbd>↑↓</Kbd> stage <span style={{ margin: '0 6px' }} /> <Kbd>↵</Kbd> open <span style={{ margin: '0 6px' }} /> <Kbd>r</Kbd> re-run
            </span>
          </div>

          <div style={{ flex: 1, overflow: 'auto', padding: dir === 'A' ? '16px 24px' : '32px 32px' }}>
            {dir === 'A' ? (
              <AsciiPipeline stages={stages} ip_data={ip_data} hover={hover} setHover={setHover} onScreen={onScreen} />
            ) : (
              <SchematicPipeline stages={stages} ip_data={ip_data} hover={hover} setHover={setHover} onScreen={onScreen} />
            )}
          </div>
        </div>
      </div>

      {/* Right: stage detail / lint findings */}
      <div className="box" style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
        <div className="box-h">
          <span>▸ Lint · spi_master.sv</span>
          <span style={{ flex: 1 }} />
          <Pill kind="warn">3W · 0E</Pill>
        </div>
        <div style={{ flex: 1, overflow: 'auto' }}>
          {window.LINT_FINDINGS.map((f, i) => (
            <div key={i}
              style={{
                padding: '10px 14px',
                borderBottom: '1px solid var(--line)',
                cursor: 'pointer',
              }}
              onMouseEnter={(e) => e.currentTarget.style.background = 'var(--bg-2)'}
              onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                <Pill kind={f.sev === 'warn' ? 'warn' : ''}>{f.code}</Pill>
                <span className="mute" style={{ fontSize: 11 }}>{f.file}:{f.line}</span>
                <span style={{ flex: 1 }} />
                {f.fixable && <span className="ok" style={{ fontSize: 10, letterSpacing: '0.08em' }}>AUTO-FIX</span>}
              </div>
              <div style={{ fontSize: 12, lineHeight: 1.45 }}>{f.msg}</div>
            </div>
          ))}
          <div style={{ padding: '14px', display: 'flex', gap: 8 }}>
            <button className="btn primary" style={{ flex: 1, justifyContent: 'center' }}>Apply auto-fixes <Kbd>F</Kbd></button>
            <button className="btn" style={{ flex: 1, justifyContent: 'center' }}>Re-lint <Kbd>R</Kbd></button>
          </div>
        </div>
        <div style={{ borderTop: '1px solid var(--line)', padding: '10px 14px', fontSize: 11, color: 'var(--fg-mute)' }}>
          Last run · 15:30 · verilator 5.024 · 3 warnings · 0 errors
        </div>
      </div>
    </div>
  );
};

// ── ASCII pipeline (Direction A) ──
const AsciiPipeline = ({ stages, ip_data, hover, setHover, onScreen }) => {
  const findInfo = (id) => ip_data.pipeline.find(p => p.id === id);
  return (
    <div style={{ fontFamily: 'var(--mono)', fontSize: 13, lineHeight: 1.4 }}>
      <div style={{ color: 'var(--fg-mute)', marginBottom: 16, fontSize: 11 }}>
        ┌──── flow ────────────────────────────────────────────────────────────────────┐
      </div>
      {stages.map((s, i) => {
        const info = findInfo(s.id);
        const isLast = i === stages.length - 1;
        return (
          <div key={s.id}>
            <div
              onClick={() => onScreen(s.id === 'tb_gen' || s.id === 'ssot' || s.id === 'rtl_gen' ? 'qa' : 'workspace')}
              onMouseEnter={() => setHover(s.id)}
              onMouseLeave={() => setHover(null)}
              style={{
                display: 'grid', gridTemplateColumns: '40px 60px 1.4fr 70px 1fr 70px 80px',
                gap: 12, padding: '14px 12px', cursor: 'pointer', alignItems: 'center',
                background: hover === s.id ? 'var(--bg-2)' : 'transparent',
                border: `1px solid ${hover === s.id ? s.color : 'var(--line)'}`,
                marginBottom: isLast ? 0 : 0,
                borderRadius: 2,
              }}
            >
              <span style={{ fontSize: 18, color: s.color, textAlign: 'center', fontWeight: 700 }}>
                {info.state === 'done' ? '●' : info.state === 'active' ? '◉' : info.state === 'warn' ? '◐' : '○'}
              </span>
              <span style={{ color: s.color, fontWeight: 700, letterSpacing: '0.06em', fontSize: 11 }}>{s.glyph}</span>
              <span><b>{s.label}</b> <span className="mute" style={{ marginLeft: 6, fontSize: 11 }}>{s.cmd}</span></span>
              <span><StateLabel state={info.state} /></span>
              <span className="dim" style={{ fontSize: 12 }}>{info.summary}</span>
              <span className="mute" style={{ fontSize: 11 }}>{info.when}</span>
              <span className="mute" style={{ fontSize: 11, textAlign: 'right' }}>{info.files} files →</span>
            </div>
            {!isLast && (
              <div style={{ color: 'var(--line-2)', paddingLeft: 24, fontSize: 14, lineHeight: 1, padding: '4px 0 4px 24px' }}>│</div>
            )}
          </div>
        );
      })}
      <div style={{ color: 'var(--fg-mute)', marginTop: 16, fontSize: 11 }}>
        └──────────────────────────────────────────────────────────────────────────────┘
      </div>
    </div>
  );
};

// ── Schematic pipeline (Direction B) — horizontal blocks with wire connectors ──
const SchematicPipeline = ({ stages, ip_data, hover, setHover, onScreen }) => {
  const findInfo = (id) => ip_data.pipeline.find(p => p.id === id);
  const W = 1100, H = 420;
  const blockW = 220, blockH = 130;
  const gap = (W - stages.length * blockW) / (stages.length + 1);
  return (
    <div style={{ display: 'flex', justifyContent: 'center' }}>
      <svg width={W} height={H} style={{ overflow: 'visible' }}>
        {/* connectors */}
        {stages.slice(0, -1).map((s, i) => {
          const x1 = gap + (i + 1) * blockW + i * gap;
          const x2 = x1 + gap;
          const y = blockH / 2 + 70;
          const info = findInfo(s.id);
          const cls = info.state === 'done' ? 'wire done' : info.state === 'active' ? 'wire active' : 'wire';
          return (
            <g key={i}>
              <path d={`M ${x1} ${y} L ${x2 - 8} ${y}`} className={cls} />
              <polygon points={`${x2 - 10},${y - 4} ${x2 - 10},${y + 4} ${x2 - 2},${y}`}
                fill={info.state === 'done' ? 'var(--ok)' : info.state === 'active' ? 'var(--accent)' : 'var(--line-2)'} />
            </g>
          );
        })}

        {stages.map((s, i) => {
          const info = findInfo(s.id);
          const x = gap + i * (blockW + gap);
          const y = 70;
          const isHover = hover === s.id;
          return (
            <g key={s.id}
              onClick={() => onScreen(s.id === 'tb_gen' || s.id === 'ssot' || s.id === 'rtl_gen' ? 'qa' : 'workspace')}
              onMouseEnter={() => setHover(s.id)}
              onMouseLeave={() => setHover(null)}
              style={{ cursor: 'pointer' }}
            >
              {/* Stage label above */}
              <text x={x + 12} y={y - 12} fill="var(--fg-mute)" fontSize="10" letterSpacing="0.14em" fontFamily="var(--mono)">
                STAGE {i + 1}
              </text>
              {/* Block */}
              <rect x={x} y={y} width={blockW} height={blockH}
                fill="var(--panel)"
                stroke={isHover ? s.color : 'var(--line-2)'}
                strokeWidth={isHover ? 1.5 : 1}
                rx="2"
              />
              {/* glyph */}
              <rect x={x + 12} y={y + 12} width={48} height={22} fill="none" stroke={s.color} strokeWidth="1" rx="2" />
              <text x={x + 36} y={y + 28} textAnchor="middle" fill={s.color} fontSize="11" fontWeight="700" letterSpacing="0.08em" fontFamily="var(--mono)">{s.glyph}</text>
              {/* label */}
              <text x={x + 70} y={y + 28} fill="var(--fg)" fontSize="14" fontWeight="500" fontFamily="var(--mono)">{s.label}</text>
              {/* cmd */}
              <text x={x + 12} y={y + 56} fill="var(--accent)" fontSize="11" fontFamily="var(--mono)">{s.cmd}</text>
              {/* status */}
              <foreignObject x={x + 12} y={y + 70} width={blockW - 24} height={50}>
                <div style={{ fontFamily: 'var(--mono)', fontSize: 11 }}>
                  <div style={{ marginBottom: 4 }}><StateLabel state={info.state} /></div>
                  <div className="mute" style={{ fontSize: 11, lineHeight: 1.35 }}>{info.summary}</div>
                </div>
              </foreignObject>
              {/* port pins */}
              <line x1={x - 8} y1={y + blockH / 2} x2={x} y2={y + blockH / 2} stroke="var(--line-2)" strokeWidth="1.5" />
              <line x1={x + blockW} y1={y + blockH / 2} x2={x + blockW + 8} y2={y + blockH / 2} stroke="var(--line-2)" strokeWidth="1.5" />
            </g>
          );
        })}

        {/* legend */}
        <g transform={`translate(${gap}, ${y_for_legend(H)})`}>
          <text x="0" y="0" fill="var(--fg-mute)" fontSize="10" letterSpacing="0.12em" fontFamily="var(--mono)">LEGEND</text>
          <LegendItem x={70} cls="ok" label="● done" />
          <LegendItem x={170} cls="acc" label="◉ active" />
          <LegendItem x={290} cls="warn" label="◐ warn" />
          <LegendItem x={400} cls="mute" label="○ pending" />
        </g>
      </svg>
    </div>
  );
};

const y_for_legend = (H) => 360;

const LegendItem = ({ x, cls, label }) => (
  <text x={x} y="0" fontSize="11" fontFamily="var(--mono)"
    fill={cls === 'ok' ? 'var(--ok)' : cls === 'acc' ? 'var(--accent)' : cls === 'warn' ? 'var(--warn)' : 'var(--fg-mute)'}>
    {label}
  </text>
);

window.Pipeline = Pipeline;
