// csr_registers.sv — generated by atlas rtl-gen
// csr_registers.sv — generated by atlas rtl-gen
// CSR block implements CTRL/STATUS/SRC_ADDR/DST_ADDR/LENGTH/PROGRESS with same-cycle read response.
module csr_registers #(
    parameter integer ADDR_WIDTH = 32,
    parameter integer DATA_WIDTH = 32,
    parameter integer LEN_WIDTH  = 16
) (
    input  logic                      clk,
    input  logic                      rst_n,
    input  logic                      csr_valid,
    output logic                      csr_ready,
    input  logic                      csr_write,
    input  logic [ADDR_WIDTH-1:0]     csr_addr,
    input  logic [DATA_WIDTH-1:0]     csr_wdata,
    output logic [DATA_WIDTH-1:0]     csr_rdata,
    output logic                      csr_error,
    input  logic                      busy_i,
    input  logic                      done_i,
    input  logic                      error_i,
    input  logic [LEN_WIDTH-1:0]      progress_i,
    output logic [ADDR_WIDTH-1:0]     src_addr_o,
    output logic [ADDR_WIDTH-1:0]     dst_addr_o,
    output logic [LEN_WIDTH-1:0]      length_o,
    output logic                      irq_done_en_o,
    output logic                      irq_error_en_o,
    output logic                      start_pulse_o,
    output logic                      soft_reset_pulse_o,
    output logic                      done_w1c_pulse_o,
    output logic                      error_w1c_pulse_o,
    output logic                      illegal_access_pulse_o,
    output logic                      illegal_start_pulse_o
);
// TBD: local parameters
// TBD: internal signals
// TBD: reset / synchronizers
// TBD: fsm
// TBD: datapath
// TBD: output assignments
endmodule
