// dma_scratch_ui_live_20260519a.sv — generated by atlas rtl-gen
// dma_scratch_ui_live_20260519a.sv — generated by atlas rtl-gen
// Top integration: CSR front-end + DMA engine + sticky IRQ/status block.
module dma_scratch_ui_live_20260519a #(
    parameter integer ADDR_WIDTH = 32,
    parameter integer DATA_WIDTH = 32,
    parameter integer LEN_WIDTH  = 16
) (
    input  logic                    clk,
    input  logic                    rst_n,
    input  logic                    csr_valid,
    output logic                    csr_ready,
    input  logic                    csr_write,
    input  logic [ADDR_WIDTH-1:0]   csr_addr,
    input  logic [DATA_WIDTH-1:0]   csr_wdata,
    output logic [DATA_WIDTH-1:0]   csr_rdata,
    output logic                    csr_error,
    output logic                    mem_rd_valid,
    input  logic                    mem_rd_ready,
    output logic [ADDR_WIDTH-1:0]   mem_rd_addr,
    input  logic                    mem_rd_data_valid,
    output logic                    mem_rd_data_ready,
    input  logic [DATA_WIDTH-1:0]   mem_rd_data,
    output logic                    mem_wr_valid,
    input  logic                    mem_wr_ready,
    output logic [ADDR_WIDTH-1:0]   mem_wr_addr,
    output logic [DATA_WIDTH-1:0]   mem_wr_data,
    output logic [DATA_WIDTH/8-1:0] mem_wr_strb,
    output logic                    irq_done,
    output logic                    irq_error
);
// Integration top has no additional localparams beyond module parameters.
logic [ADDR_WIDTH-1:0] src_addr_cfg;
logic [ADDR_WIDTH-1:0] dst_addr_cfg;
logic [LEN_WIDTH-1:0]  length_cfg;
logic                  irq_done_en_cfg;
logic                  irq_error_en_cfg;
logic                  start_pulse;
logic                  soft_reset_pulse;
logic                  done_w1c_pulse;
logic                  error_w1c_pulse;
logic                  illegal_access_pulse;
logic                  illegal_start_pulse;
logic                  busy_state;
logic [LEN_WIDTH-1:0]  progress_state;
logic                  done_event;
logic                  done_sticky;
logic                  error_sticky;
logic                  error_set_event;
assign error_set_event = illegal_access_pulse | illegal_start_pulse;
// No top-level FSM; control state is implemented inside dma_engine.
csr_registers #(
    .ADDR_WIDTH(ADDR_WIDTH),
    .DATA_WIDTH(DATA_WIDTH),
    .LEN_WIDTH(LEN_WIDTH)
) u_csr_registers (
    .clk                   (clk),
    .rst_n                 (rst_n),
    .csr_valid             (csr_valid),
    .csr_ready             (csr_ready),
    .csr_write             (csr_write),
    .csr_addr              (csr_addr),
    .csr_wdata             (csr_wdata),
    .csr_rdata             (csr_rdata),
    .csr_error             (csr_error),
    .busy_i                (busy_state),
    .done_i                (done_sticky),
    .error_i               (error_sticky),
    .progress_i            (progress_state),
    .src_addr_o            (src_addr_cfg),
    .dst_addr_o            (dst_addr_cfg),
    .length_o              (length_cfg),
    .irq_done_en_o         (irq_done_en_cfg),
    .irq_error_en_o        (irq_error_en_cfg),
    .start_pulse_o         (start_pulse),
    .soft_reset_pulse_o    (soft_reset_pulse),
    .done_w1c_pulse_o      (done_w1c_pulse),
    .error_w1c_pulse_o     (error_w1c_pulse),
    .illegal_access_pulse_o(illegal_access_pulse),
    .illegal_start_pulse_o (illegal_start_pulse)
);

dma_engine #(
    .ADDR_WIDTH(ADDR_WIDTH),
    .DATA_WIDTH(DATA_WIDTH),
    .LEN_WIDTH(LEN_WIDTH)
) u_dma_engine (
    .clk               (clk),
    .rst_n             (rst_n),
    .src_addr_i        (src_addr_cfg),
    .dst_addr_i        (dst_addr_cfg),
    .length_i          (length_cfg),
    .start_pulse_i     (start_pulse),
    .soft_reset_pulse_i(soft_reset_pulse),
    .mem_rd_valid      (mem_rd_valid),
    .mem_rd_ready      (mem_rd_ready),
    .mem_rd_addr       (mem_rd_addr),
    .mem_rd_data_valid (mem_rd_data_valid),
    .mem_rd_data_ready (mem_rd_data_ready),
    .mem_rd_data       (mem_rd_data),
    .mem_wr_valid      (mem_wr_valid),
    .mem_wr_ready      (mem_wr_ready),
    .mem_wr_addr       (mem_wr_addr),
    .mem_wr_data       (mem_wr_data),
    .mem_wr_strb       (mem_wr_strb),
    .busy_o            (busy_state),
    .progress_o        (progress_state),
    .done_pulse_o      (done_event)
);

irq_status u_irq_status (
    .clk              (clk),
    .rst_n            (rst_n),
    .done_event_i     (done_event),
    .error_set_event_i(error_set_event),
    .done_w1c_pulse_i (done_w1c_pulse),
    .error_w1c_pulse_i(error_w1c_pulse),
    .soft_reset_pulse_i(soft_reset_pulse),
    .irq_done_en_i    (irq_done_en_cfg),
    .irq_error_en_i   (irq_error_en_cfg),
    .done_o           (done_sticky),
    .error_o          (error_sticky),
    .irq_done         (irq_done),
    .irq_error        (irq_error)
);
// Top-level outputs are driven directly by child module connections above.
endmodule
