// irq_status.sv — generated by atlas rtl-gen
// irq_status.sv — generated by atlas rtl-gen
// Sticky done/error status and level interrupts with W1C clear semantics.
module irq_status (
    input  logic                  clk,
    input  logic                  rst_n,
    input  logic                  done_event_i,
    input  logic                  error_set_event_i,
    input  logic                  done_w1c_pulse_i,
    input  logic                  error_w1c_pulse_i,
    input  logic                  soft_reset_pulse_i,
    input  logic                  irq_done_en_i,
    input  logic                  irq_error_en_i,
    output logic                  done_o,
    output logic                  error_o,
    output logic                  irq_done,
    output logic                  irq_error
);
// No local parameters required in this status-only block.
logic done_q;
logic error_q;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        done_q  <= 1'b0;
        error_q <= 1'b0;
    end else begin
        if (soft_reset_pulse_i) begin
            done_q  <= 1'b0;
            error_q <= 1'b0;
        end else begin
            if (done_event_i) begin
                done_q <= 1'b1;
            end else if (done_w1c_pulse_i) begin
                done_q <= 1'b0;
            end

            if (error_set_event_i) begin
                error_q <= 1'b1;
            end else if (error_w1c_pulse_i) begin
                error_q <= 1'b0;
            end
        end
    end
end
// No dedicated FSM required; sticky status logic is event-driven.
// Datapath not applicable for irq_status; this block only stores and gates status bits.
assign done_o   = done_q;
assign error_o  = error_q;
assign irq_done = done_q & irq_done_en_i;
assign irq_error= error_q & irq_error_en_i;
endmodule
