#!/usr/bin/env python3
"""write_dft_tcl.py — Port of write_dft_tcl.sh. Generate <ip>/dft/run.tcl from SSOT dft: section.

Args: <ip_name>
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _dft_common as common  # noqa: E402


_PARAMS_PY = r"""
import sys, pathlib
ssot, ip = sys.argv[1:3]
try:
    import yaml; d = yaml.safe_load(pathlib.Path(ssot).read_text(encoding="utf-8", errors="replace")) or {}
except Exception: d = {}
_t = d.get("top_module")
if isinstance(_t, dict): _t = _t.get("name")
top = _t or d.get("top") or ip
dft = d.get("dft", {}) or {}
print(top, dft.get("scan_enable_port") or "scan_en",
      int(dft.get("max_chains", 4)), int(dft.get("max_chain_length", 100)))
"""


def main(argv: "list[str]") -> int:
    common.load_pdk_env(os.environ)

    ip = argv[0] if argv else ""
    if not ip:
        print("[DFT] usage: write_dft_tcl.sh <ip_name>", file=sys.stderr)
        return 2
    ssot = f"{ip}/yaml/{ip}.ssot.yaml"
    netlist = f"{ip}/syn/out/synth.v"
    tcl = f"{ip}/dft/run.tcl"
    out = f"{ip}/dft/out"
    Path(f"{ip}/dft").mkdir(parents=True, exist_ok=True)
    Path(out).mkdir(parents=True, exist_ok=True)

    if not Path(ssot).is_file():
        print(f"[DFT] missing SSOT: {ssot}", file=sys.stderr)
        return 2
    if not (Path(netlist).is_file() and Path(netlist).stat().st_size > 0):
        print(f"[DFT] missing {netlist}", file=sys.stderr)
        return 5

    proc = common.run_embedded_py(_PARAMS_PY, [ssot, ip], capture=True)
    top, se_port, max_chains, max_len = proc.stdout.split()

    # scan_enable_port must exist in synth.v as a port. Catch BEFORE OpenROAD.
    # grep -E "(input|output)[^;]*\b<SE_PORT>\b" netlist
    pat = re.compile(r"(input|output)[^;]*\b" + re.escape(se_port) + r"\b")
    netlist_text = Path(netlist).read_text(encoding="utf-8", errors="replace")
    if not any(pat.search(line) for line in netlist_text.splitlines()):
        print(
            f"[DFT PORT MISMATCH] scan_enable_port '{se_port}' not declared in {netlist}",
            file=sys.stderr,
        )
        return 9

    lib = os.environ.get("SKY130_LIB", "")

    tcl_text = (
        "# Generated by workflow/dft/scripts/write_dft_tcl.sh\n"
        f"# IP: {ip}   top: {top}   scan_enable: {se_port}\n"
        f"# max_chains: {max_chains}   max_chain_length: {max_len}\n"
        "\n"
        f"read_liberty {lib}\n"
        f"read_verilog {netlist}\n"
        f"link_design {top}\n"
        "\n"
        f"set_dft_config -max_length {max_len} -max_chains {max_chains} -clock_mixing no_mix\n"
        "preview_dft -verbose\n"
        "insert_dft\n"
        "\n"
        f"write_verilog {out}/scan.v\n"
        "report_dft\n"
        "exit\n"
    )
    Path(tcl).write_text(tcl_text, encoding="utf-8")
    print(
        f"[DFT] wrote {tcl} (top={top} scan_en={se_port} "
        f"max_chains={max_chains} max_len={max_len})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
