#!/usr/bin/env python3
"""write_sta_tcl.py — Generate <ip>/sta/run.tcl that drives OpenSTA.

Python port of write_sta_tcl.sh for native-Windows portability. CLI, exit codes,
stdout/stderr, and the generated run.tcl are kept byte-identical to the bash
original.

Usage: write_sta_tcl.py <ip_name>
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Allow ``from sta_scripts import ...`` style sharing without a package.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sh_port_common import load_pdk_env, resolve_top  # noqa: E402


def main(argv: list[str]) -> int:
    # Mirror the bash ``[ $# -eq 0 ] && [ -n "$HOOK_CMD_ARGS" ]`` fallback.
    if not argv and os.environ.get("HOOK_CMD_ARGS"):
        argv = os.environ["HOOK_CMD_ARGS"].split()

    env = load_pdk_env()

    ip = argv[0] if argv else ""
    if not ip:
        print("[STA] usage: write_sta_tcl.py <ip_name>", file=sys.stderr)
        return 2

    netlist = f"{ip}/syn/out/synth.v"
    sdc = f"{ip}/sta/out/{ip}.sdc"
    tcl = f"{ip}/sta/run.tcl"
    out = f"{ip}/sta/out"
    Path(f"{ip}/sta").mkdir(parents=True, exist_ok=True)
    Path(out).mkdir(parents=True, exist_ok=True)

    # ``[ ! -s ]`` = missing or empty.
    if not (Path(netlist).is_file() and Path(netlist).stat().st_size > 0):
        print(f"[STA] missing {netlist}", file=sys.stderr)
        return 5
    if not Path(sdc).is_file():
        print(f"[STA] missing {sdc} — run /sta-sdc first", file=sys.stderr)
        return 2

    ssot = f"{ip}/yaml/{ip}.ssot.yaml"
    top = resolve_top(ip, ssot)
    sky130_lib = env.get("SKY130_LIB", "")

    tcl_text = (
        "# Generated by workflow/sta/scripts/write_sta_tcl.sh\n"
        f"# IP: {ip}   top: {top}\n"
        f"read_liberty {sky130_lib}\n"
        f"read_verilog {netlist}\n"
        f"link_design {top}\n"
        f"read_sdc {sdc}\n"
        "\n"
        f"report_checks -path_delay max -group_count 5 -fields {{slew capacitance input_pins nets fanout}} > {out}/setup.rpt\n"
        f"report_checks -path_delay min -group_count 5 -fields {{slew capacitance input_pins nets fanout}} > {out}/hold.rpt\n"
        f"report_checks -path_delay min_max -group_count 10                                                > {out}/timing.rpt\n"
        "report_wns\n"
        "report_tns\n"
    )
    Path(tcl).write_text(tcl_text, encoding="utf-8")
    print(f"[STA] wrote {tcl} (top={top})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
