#!/usr/bin/env bash
# write_yosys_script.sh — Generate <ip>/syn/run.ys from SSOT yaml + filelist.
# Args: <ip_name>
# Reads:  <ip>/yaml/<ip>.ssot.yaml (top_module), <ip>/list/<ip>.f (rtl files)
# Writes: <ip>/syn/run.ys
set -uo pipefail

if [ $# -eq 0 ] && [ -n "${HOOK_CMD_ARGS:-}" ]; then
  # shellcheck disable=SC2086
  set -- ${HOOK_CMD_ARGS}
fi

PDK_ENV="$(cd "$(dirname "$0")/../.." && pwd -P)/scripts/pdk_env.sh"
[ -f "${PDK_ENV}" ] && source "${PDK_ENV}"

IP="${1:-}"
if [ -z "${IP}" ]; then echo "[SYN] usage: write_yosys_script.sh <ip_name>" >&2; exit 2; fi

SSOT="${IP}/yaml/${IP}.ssot.yaml"
FLIST="${IP}/list/${IP}.f"
SCRIPT="${IP}/syn/run.ys"

if [ ! -f "${SSOT}" ]; then echo "[SYN] missing SSOT: ${SSOT}" >&2; exit 2; fi
if [ ! -f "${FLIST}" ]; then echo "[SYN] missing filelist: ${FLIST}" >&2; exit 2; fi

# yosys script-mode does not expand TCL env vars in -liberty arguments —
# substitute the absolute path at script-write time.
LIB="${SKY130_LIB:-}"
if [ -z "${LIB}" ] || [ ! -r "${LIB}" ]; then
  echo "[SYN MISSING PDK] \$SKY130_LIB unreadable: ${LIB}" >&2
  exit 4
fi

mkdir -p "${IP}/syn" "${IP}/syn/out"

python3 - "${IP}" "${SSOT}" "${FLIST}" "${SCRIPT}" "${LIB}" <<'PY'
import pathlib
import sys

try:
    import yaml
except Exception as exc:
    print(f"[SYN] PyYAML required to read SSOT: {exc}", file=sys.stderr)
    raise SystemExit(2)

ip, ssot_path, flist_path, script_path, lib_path = sys.argv[1:6]
ip_dir = pathlib.Path(ip)
ssot = pathlib.Path(ssot_path)
flist = pathlib.Path(flist_path)
script = pathlib.Path(script_path)
lib = pathlib.Path(lib_path).resolve(strict=False)

doc = yaml.safe_load(ssot.read_text(encoding="utf-8", errors="replace")) or {}
top_raw = doc.get("top_module") or doc.get("top")
if isinstance(top_raw, dict):
    top = str(top_raw.get("name") or top_raw.get("module") or "").strip()
elif top_raw is None:
    top = ""
else:
    top = str(top_raw).strip()
top = top or ip_dir.name

missing = []
rtl_files = []
incdirs = []
for raw in flist.read_text(encoding="utf-8", errors="replace").splitlines():
    line = raw.split("//", 1)[0].split("#", 1)[0].strip()
    if not line:
        continue
    if line.startswith("+incdir+"):
        inc = line[len("+incdir+"):]
        p = pathlib.Path(inc)
        incdirs.append(p if p.is_absolute() else (ip_dir / p).resolve(strict=False))
        continue
    if line.startswith("-"):
        continue
    if not line.endswith((".v", ".sv", ".vh", ".svh")):
        continue
    p = pathlib.Path(line)
    candidates = [p] if p.is_absolute() else [ip_dir / p, pathlib.Path.cwd() / p]
    hit = next((c for c in candidates if c.is_file()), None)
    if hit is None:
        missing.append(line)
    else:
        rtl_files.append(hit.resolve(strict=False))

if missing:
    print("[SYN] missing RTL filelist entries:", file=sys.stderr)
    for item in missing:
        print(f"  - {item}", file=sys.stderr)
    raise SystemExit(2)
if not rtl_files:
    print(f"[SYN] no RTL files found in {flist}", file=sys.stderr)
    raise SystemExit(2)

def q(path: object) -> str:
    return '"' + str(path).replace("\\", "/").replace('"', '\\"') + '"'

out_netlist = (ip_dir / "syn" / "out" / "synth.v").resolve(strict=False)
lines = [
    "# Generated by workflow/syn/scripts/write_yosys_script.sh",
    f"# IP: {ip_dir.name}   top: {top}   corner: {lib}",
    f"read_liberty -lib {q(lib)}",
]
for inc in incdirs:
    lines.append(f"verilog_defaults -add -I{q(inc)}")
for path in rtl_files:
    lines.append(f"read_verilog -sv {q(path)}")
lines.extend([
    f"hierarchy -check -top {top}",
    f"synth -top {top}",
    f"dfflibmap -liberty {q(lib)}",
    f"abc -liberty {q(lib)}",
    "opt_clean -purge",
    f"write_verilog -noattr {q(out_netlist)}",
    f"stat -liberty {q(lib)}",
])
script.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"[SYN] wrote {script} (top={top}, rtl_files={len(rtl_files)}, lib={lib})")
PY
