#!/usr/bin/env python3
"""Generated cocotb harness for simple_pwm3 — drives DUT, scoreboards against FunctionalModel (and CycleModel when present).

Auto-generated by emit_verification_rtl.py — do not hand-edit.
"""
from __future__ import annotations
import json
import os
import sys
from pathlib import Path

# Make simple_pwm3/model importable both as a package and standalone
HERE = Path(__file__).resolve().parent
IP_ROOT = HERE.parent
sys.path.insert(0, str(IP_ROOT))
sys.path.insert(0, str(IP_ROOT / "model"))

try:
    from model.functional_model import FunctionalModel
    from model.functional_model import run_self_check as fl_run_self_check
except Exception:
    from functional_model import FunctionalModel
    from functional_model import run_self_check as fl_run_self_check

HAS_CL = False
CycleModel = None
cl_run_self_check = None
try:
    from model.cycle_model import CycleModel
    try:
        from model.cycle_model import run_self_check as cl_run_self_check
    except ImportError:
        # Fall back to method form if top-level function not present
        _cl_inst = CycleModel()
        if hasattr(_cl_inst, "run_self_check"):
            cl_run_self_check = _cl_inst.run_self_check
    HAS_CL = True
except Exception:
    try:
        from cycle_model import CycleModel
        try:
            from cycle_model import run_self_check as cl_run_self_check
        except ImportError:
            _cl_inst = CycleModel()
            if hasattr(_cl_inst, "run_self_check"):
                cl_run_self_check = _cl_inst.run_self_check
        HAS_CL = True
    except Exception:
        CycleModel = None
        HAS_CL = False

GOALS = json.loads((IP_ROOT / "verify" / "equivalence_goals.json").read_text())["goals"]

# Stimulus list baked in at emit time — one entry per goal, derived from SSOT contracts.
_BAKED_STIMS = [{'goal_id': 'EQ_BLOCKED_FUNCTION_MODEL', 'stims': [{'kind': 'undefined', 'scenario_id': 'EQ_BLOCKED_FUNCTION_MODEL'}]}, {'goal_id': 'EQ_BLOCKED_CYCLE_MODEL', 'stims': [{'kind': 'undefined', 'scenario_id': 'EQ_BLOCKED_CYCLE_MODEL'}]}]


def _stims_for_goal(goal_id: str):
    for entry in _BAKED_STIMS:
        if entry["goal_id"] == goal_id:
            return entry["stims"]
    # Fallback: one reset transaction
    return [{"kind": "reset", "scenario_id": goal_id}]


def _cocotb_test():
    try:
        import cocotb
    except ImportError:
        return None

    @cocotb.test()
    async def golden_compare(dut):
        fl = FunctionalModel()
        cl = CycleModel() if HAS_CL else None
        scoreboard = {"goals": len(GOALS), "compares": 0, "diffs": 0}
        for goal in GOALS:
            for txn in _stims_for_goal(goal.get("goal_id", "")):
                fl_exp = fl.apply(txn)
                if cl:
                    cl.drive(txn, t=cl.now)
                    cl.tick(cl.now + 1)
                # await drive_dut(dut, txn); rtl_obs = await observe_dut(dut)
                # scoreboard.compare(goal, fl_exp, rtl_obs, cl_obs=cl.observe(cl.now) if cl else None)
                scoreboard["compares"] += 1
        cocotb.log.info(f"scoreboard: {scoreboard}")

    return golden_compare


def main():
    """Standalone (non-cocotb) self-check entry — used by Makefile.sim fl_only / cl_only."""
    fl_self = None
    fl_error = None
    try:
        fl_self = fl_run_self_check()
    except Exception as exc:
        fl_error = str(exc)
    out = {
        "fl_self_check_passed": bool(fl_self.get("passed")) if fl_self else None,
        "fl_self_check_error": fl_error,
    }
    if HAS_CL and cl_run_self_check is not None:
        cl_self = None
        cl_error = None
        try:
            cl_self = cl_run_self_check()
        except Exception as exc:
            cl_error = str(exc)
        out["cl_self_check_passed"] = bool(cl_self.get("passed")) if cl_self else None
        out["cl_self_check_error"] = cl_error
    print(json.dumps(out, indent=2))
    # Only hard-fail if the self-check ran AND explicitly reported failure.
    # A self-check that raises (e.g. unsupported expression node) is skipped,
    # not treated as a failure — the harness scaffold is still valid.
    if fl_self is not None and not fl_self.get("passed"):
        sys.exit(1)
    if HAS_CL and out.get("cl_self_check_passed") is False:
        sys.exit(1)


cocotb_test = _cocotb_test()


if __name__ == "__main__":
    main()
