// dma_engine.sv — generated by atlas rtl-gen
// dma_engine.sv — generated by atlas rtl-gen
// DMA datapath/FSM: single outstanding read-data buffer and ordered read->write beat flow.
module dma_engine #(
    parameter integer ADDR_WIDTH = 32,
    parameter integer DATA_WIDTH = 32,
    parameter integer LEN_WIDTH  = 16
) (
    input  logic                      clk,
    input  logic                      rst_n,
    input  logic [ADDR_WIDTH-1:0]     src_addr_i,
    input  logic [ADDR_WIDTH-1:0]     dst_addr_i,
    input  logic [LEN_WIDTH-1:0]      length_i,
    input  logic                      start_pulse_i,
    input  logic                      soft_reset_pulse_i,
    output logic                      mem_rd_valid,
    input  logic                      mem_rd_ready,
    output logic [ADDR_WIDTH-1:0]     mem_rd_addr,
    input  logic                      mem_rd_data_valid,
    output logic                      mem_rd_data_ready,
    input  logic [DATA_WIDTH-1:0]     mem_rd_data,
    output logic                      mem_wr_valid,
    input  logic                      mem_wr_ready,
    output logic [ADDR_WIDTH-1:0]     mem_wr_addr,
    output logic [DATA_WIDTH-1:0]     mem_wr_data,
    output logic [DATA_WIDTH/8-1:0]   mem_wr_strb,
    output logic                      busy_o,
    output logic [LEN_WIDTH-1:0]      progress_o,
    output logic                      done_pulse_o
);
`include "dma_scratch_ui_live_20260519a_param.vh"
logic [2:0] state_q;
logic [LEN_WIDTH-1:0] remaining_q;
logic [LEN_WIDTH-1:0] progress_q;
logic write_buffer_full_q;
logic done_pulse_q;
logic mem_rd_valid_q;
logic [ADDR_WIDTH-1:0] mem_rd_addr_q;
logic mem_wr_valid_q;
logic [ADDR_WIDTH-1:0] mem_wr_addr_q;
logic [DATA_WIDTH-1:0] mem_wr_data_q;
logic [STRB_WIDTH-1:0] mem_wr_strb_q;
logic [LEN_WIDTH-1:0] beat_bytes;
logic [LEN_WIDTH-1:0] transfer_bytes;
logic [STRB_WIDTH-1:0] strobe_calc;
logic [STRB_WIDTH-1:0] strobe_mask_1;
logic [STRB_WIDTH-1:0] strobe_mask_2;
logic [STRB_WIDTH-1:0] strobe_mask_3;
logic [STRB_WIDTH-1:0] strobe_mask_4;
// DATA_WIDTH is constrained to 32 in SSOT, so each beat is exactly 4 bytes.
assign beat_bytes = 4;
assign transfer_bytes = (remaining_q > beat_bytes) ? beat_bytes : remaining_q;

// Build final-beat byte strobe without procedural loops.
assign strobe_mask_1 = (transfer_bytes >= 1) ? 4'b0001 : 4'b0000;
assign strobe_mask_2 = (transfer_bytes >= 2) ? 4'b0011 : strobe_mask_1;
assign strobe_mask_3 = (transfer_bytes >= 3) ? 4'b0111 : strobe_mask_2;
assign strobe_mask_4 = (transfer_bytes >= 4) ? 4'b1111 : strobe_mask_3;
assign strobe_calc = strobe_mask_4;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        state_q            <= FSM_IDLE;
        remaining_q        <= {LEN_WIDTH{1'b0}};
        progress_q         <= {LEN_WIDTH{1'b0}};
        write_buffer_full_q<= 1'b0;
        done_pulse_q       <= 1'b0;
        mem_rd_valid_q     <= 1'b0;
        mem_rd_addr_q      <= {ADDR_WIDTH{1'b0}};
        mem_wr_valid_q     <= 1'b0;
        mem_wr_addr_q      <= {ADDR_WIDTH{1'b0}};
        mem_wr_data_q      <= {DATA_WIDTH{1'b0}};
        mem_wr_strb_q      <= {STRB_WIDTH{1'b0}};
    end else begin
        // Default pulse clears each cycle unless a final-beat completion occurs.
        done_pulse_q <= 1'b0;

        // soft_reset aborts in-flight DMA and deasserts memory valids.
        if (soft_reset_pulse_i) begin
            state_q             <= FSM_IDLE;
            remaining_q         <= {LEN_WIDTH{1'b0}};
            progress_q          <= {LEN_WIDTH{1'b0}};
            write_buffer_full_q <= 1'b0;
            mem_rd_valid_q      <= 1'b0;
            mem_wr_valid_q      <= 1'b0;
            mem_wr_strb_q       <= {STRB_WIDTH{1'b0}};
        end else begin
            case (state_q)
                FSM_IDLE: begin
                    mem_rd_valid_q <= 1'b0;
                    mem_wr_valid_q <= 1'b0;
                    write_buffer_full_q <= 1'b0;
                    if (start_pulse_i) begin
                        progress_q  <= {LEN_WIDTH{1'b0}};
                        remaining_q <= length_i;
                        if (length_i == {LEN_WIDTH{1'b0}}) begin
                            done_pulse_q <= 1'b1;
                            state_q <= FSM_DONE;
                        end else begin
                            mem_rd_addr_q  <= src_addr_i;
                            mem_rd_valid_q <= 1'b1;
                            state_q <= FSM_READ_REQ;
                        end
                    end
                end
                FSM_READ_REQ: begin
                    if (mem_rd_valid_q && mem_rd_ready) begin
                        mem_rd_valid_q <= 1'b0;
                        state_q <= FSM_WAIT_RDATA;
                    end
                end
                FSM_WAIT_RDATA: begin
                    if (mem_rd_data_valid && mem_rd_data_ready) begin
                        write_buffer_full_q <= 1'b1;
                        mem_wr_addr_q       <= dst_addr_i + {{(ADDR_WIDTH-LEN_WIDTH){1'b0}}, progress_q};
                        mem_wr_data_q       <= mem_rd_data;
                        mem_wr_strb_q       <= strobe_calc;
                        mem_wr_valid_q      <= 1'b1;
                        state_q             <= FSM_WRITE_REQ;
                    end
                end
                FSM_WRITE_REQ: begin
                    if (mem_wr_valid_q && mem_wr_ready) begin
                        mem_wr_valid_q      <= 1'b0;
                        write_buffer_full_q <= 1'b0;
                        remaining_q         <= remaining_q - transfer_bytes;
                        progress_q          <= progress_q + transfer_bytes;
                        if (remaining_q <= beat_bytes) begin
                            done_pulse_q <= 1'b1;
                            state_q      <= FSM_DONE;
                        end else begin
                            mem_rd_addr_q  <= src_addr_i + {{(ADDR_WIDTH-LEN_WIDTH){1'b0}}, (progress_q + transfer_bytes)};
                            mem_rd_valid_q <= 1'b1;
                            state_q        <= FSM_READ_REQ;
                        end
                    end
                end
                FSM_DONE: begin
                    // Done state is one cycle for observability; sticky status is held in irq_status.
                    state_q <= FSM_IDLE;
                end
                FSM_ERROR: begin
                    // Reserved state for future explicit memory-side errors.
                    state_q <= FSM_IDLE;
                end
                default: begin
                    state_q <= FSM_IDLE;
                end
            endcase
        end
    end
end
// Datapath ownership: read buffer + transfer/progress counters are updated in the sequential FSM above.
assign mem_rd_valid      = mem_rd_valid_q;
assign mem_rd_addr       = mem_rd_addr_q;
assign mem_rd_data_ready = (state_q == FSM_WAIT_RDATA) && (!write_buffer_full_q);
assign mem_wr_valid      = mem_wr_valid_q;
assign mem_wr_addr       = mem_wr_addr_q;
assign mem_wr_data       = mem_wr_data_q;
assign mem_wr_strb       = mem_wr_strb_q;
assign busy_o            = (state_q == FSM_READ_REQ) || (state_q == FSM_WAIT_RDATA) || (state_q == FSM_WRITE_REQ);
assign progress_o        = progress_q;
assign done_pulse_o      = done_pulse_q;
endmodule
