// Shared parameters for mctp_assembler (SSOT: yaml/mctp_assembler.ssot.yaml)
`ifndef MCTP_ASSEMBLER_PARAM_VH
`define MCTP_ASSEMBLER_PARAM_VH

`define MCTP_ASSEMBLER_AXI_ADDR_WIDTH     16
`define MCTP_ASSEMBLER_AXI_DATA_WIDTH     256
`define MCTP_ASSEMBLER_APB_ADDR_WIDTH     12
`define MCTP_ASSEMBLER_APB_DATA_WIDTH     32
`define MCTP_ASSEMBLER_SRAM_ADDR_WIDTH    16
`define MCTP_ASSEMBLER_SRAM_DATA_WIDTH    256
`define MCTP_ASSEMBLER_CONTEXT_COUNT      15
`define MCTP_ASSEMBLER_MAX_MESSAGE_BYTES  4096
`define MCTP_ASSEMBLER_BASELINE_MTU_BYTES 64
`define MCTP_ASSEMBLER_DESCRIPTOR_FIFO_DEPTH 8
`define MCTP_ASSEMBLER_TIMEOUT_COUNTER_WIDTH 24
`define MCTP_ASSEMBLER_HDR_BYTES            16
`define MCTP_ASSEMBLER_MAX_TLP_BYTES        512
`define MCTP_ASSEMBLER_AXI_DATA_BYTES       (`MCTP_ASSEMBLER_AXI_DATA_WIDTH / 8)
`define MCTP_ASSEMBLER_SRAM_DATA_BYTES      (`MCTP_ASSEMBLER_SRAM_DATA_WIDTH / 8)
`define MCTP_ASSEMBLER_CONTEXT_IDX_WIDTH    4
`define MCTP_ASSEMBLER_MSG_CODE_VDM         8'h7F
`define MCTP_ASSEMBLER_VENDOR_ID_DMTF       16'h1AB4
`define MCTP_ASSEMBLER_MCTP_HDR_VERSION     4'd1

`endif
