# Auto-generated by workflow/tb-gen/scripts/ssot_to_cocotb.py
import json
import os
import time
from pathlib import Path

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge


ADDR_CTRL = 0x0
ADDR_COUNT = 0x4
ADDR_COMPARE = 0x8
ADDR_STATUS = 0xC

_bins = {
    "reset_defaults": False,
    "apb_write_ctrl": False,
    "apb_write_compare": False,
    "apb_readback": False,
    "counter_increments": False,
    "counter_halts": False,
    "compare_irq": False,
    "status_w1c_clear": False,
    "irq_mask": False,
}


def _set_bin(name):
    _bins[name] = True


async def _reset(dut):
    dut.psel.value = 0
    dut.penable.value = 0
    dut.pwrite.value = 0
    dut.paddr.value = 0
    dut.pwdata.value = 0
    dut.pstrb.value = 0
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, 4)
    dut.rst_n.value = 1
    await ClockCycles(dut.clk, 2)


async def _apb_write(dut, addr, data):
    dut.paddr.value = addr
    dut.pwrite.value = 1
    dut.pwdata.value = data
    dut.pstrb.value = 0xF
    dut.psel.value = 1
    dut.penable.value = 0
    await RisingEdge(dut.clk)
    dut.penable.value = 1
    await RisingEdge(dut.clk)
    assert int(dut.pready.value) == 1
    assert int(dut.pslverr.value) == 0
    dut.psel.value = 0
    dut.penable.value = 0
    dut.pwrite.value = 0
    dut.paddr.value = 0
    dut.pwdata.value = 0
    dut.pstrb.value = 0
    await RisingEdge(dut.clk)


async def _apb_read(dut, addr):
    dut.paddr.value = addr
    dut.pwrite.value = 0
    dut.psel.value = 1
    dut.penable.value = 0
    await RisingEdge(dut.clk)
    dut.penable.value = 1
    await RisingEdge(dut.clk)
    assert int(dut.pready.value) == 1
    assert int(dut.pslverr.value) == 0
    value = int(dut.prdata.value)
    dut.psel.value = 0
    dut.penable.value = 0
    dut.paddr.value = 0
    await RisingEdge(dut.clk)
    return value


def _write_coverage(status="ok"):
    hit = sum(1 for v in _bins.values() if v)
    total = len(_bins)
    pct = round(100.0 * hit / total, 2) if total else 100.0
    data = {
        "timestamp_iso": datetime_now(),
        "dut": os.environ.get("DUT_NAME", "unknown"),
        "status": status,
        "tests": {"hit": hit, "total": total, "pct": pct},
        "lines": {"hit": hit, "total": total, "pct": pct},
        "branches": {"hit": hit, "total": total, "pct": pct},
        "functional": {"hit": hit, "total": total, "pct": pct, "bins": _bins},
        "html_available": False,
    }
    cov_path = Path(os.environ["COVERAGE_JSON"])
    cov_path.parent.mkdir(parents=True, exist_ok=True)
    cov_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    hist_path = Path(os.environ["COVERAGE_HISTORY_JSONL"])
    with hist_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(data) + "\n")


def datetime_now():
    return time.strftime("%Y-%m-%dT%H:%M:%S")


@cocotb.test()
async def apb_timer_regression(dut):
    cocotb.start_soon(Clock(dut.clk, 10, units="ns").start())
    await _reset(dut)

    assert int(dut.irq.value) == 0
    assert await _apb_read(dut, ADDR_CTRL) == 0
    assert await _apb_read(dut, ADDR_COMPARE) == 0
    assert await _apb_read(dut, ADDR_STATUS) == 0
    _set_bin("reset_defaults")

    await _apb_write(dut, ADDR_COMPARE, 9)
    assert await _apb_read(dut, ADDR_COMPARE) == 9
    _set_bin("apb_write_compare")
    _set_bin("apb_readback")

    await _apb_write(dut, ADDR_CTRL, 0x1)
    assert await _apb_read(dut, ADDR_CTRL) & 0x1 == 0x1
    _set_bin("apb_write_ctrl")
    first = await _apb_read(dut, ADDR_COUNT)
    await ClockCycles(dut.clk, 4)
    second = await _apb_read(dut, ADDR_COUNT)
    assert second > first
    _set_bin("counter_increments")

    await _apb_write(dut, ADDR_CTRL, 0x0)
    stopped_a = await _apb_read(dut, ADDR_COUNT)
    await ClockCycles(dut.clk, 5)
    stopped_b = await _apb_read(dut, ADDR_COUNT)
    assert stopped_b == stopped_a
    _set_bin("counter_halts")

    await _reset(dut)
    await _apb_write(dut, ADDR_COMPARE, 3)
    await _apb_write(dut, ADDR_CTRL, 0x3)
    await ClockCycles(dut.clk, 5)
    assert int(dut.irq.value) == 1
    assert await _apb_read(dut, ADDR_STATUS) & 0x1 == 0x1
    _set_bin("compare_irq")

    await _apb_write(dut, ADDR_STATUS, 0x1)
    await ClockCycles(dut.clk, 2)
    assert int(dut.irq.value) == 0
    assert await _apb_read(dut, ADDR_STATUS) & 0x1 == 0x0
    _set_bin("status_w1c_clear")

    await _reset(dut)
    await _apb_write(dut, ADDR_COMPARE, 2)
    await _apb_write(dut, ADDR_CTRL, 0x1)
    await ClockCycles(dut.clk, 4)
    assert await _apb_read(dut, ADDR_STATUS) & 0x1 == 0x1
    assert int(dut.irq.value) == 0
    _set_bin("irq_mask")

    _write_coverage("ok")
