# Auto-generated by workflow/tb-gen/scripts/ssot_to_cocotb.py
from pathlib import Path
import os

from cocotb_test.simulator import run


def test_timer_ssot_web_cocotb():
    root = Path(__file__).resolve().parents[2]
    ip = "timer_ssot_web"
    sources = [
        root / "rtl" / f"timer_ssot_web_regs.sv",
        root / "rtl" / f"timer_ssot_web_core.sv",
        root / "rtl" / f"timer_ssot_web_wrapper.sv",
    ]
    build_dir = root / "sim" / "cocotb_build"
    build_dir.mkdir(parents=True, exist_ok=True)
    dump_src = build_dir / f"timer_ssot_web_vcd_dump.v"
    dump_src.write_text(
        "module timer_ssot_web_vcd_dump();\n"
        "initial begin\n"
        "  $dumpfile(\"timer_ssot_web.vcd\");\n"
        "  $dumpvars(0, timer_ssot_web_wrapper);\n"
        "end\n"
        "endmodule\n"
    )
    sources.append(dump_src)
    os.environ.setdefault("DUT_NAME", ip)
    os.environ.setdefault("COVERAGE_JSON", str(root / "cov" / "coverage.json"))
    os.environ.setdefault("COVERAGE_HISTORY_JSONL", str(root / "cov" / "history.jsonl"))
    run(
        simulator="icarus",
        verilog_sources=[str(p) for p in sources],
        toplevel=[f"timer_ssot_web_wrapper", f"timer_ssot_web_vcd_dump"],
        module=f"test_timer_ssot_web",
        sim_build=str(build_dir),
        timescale="1ns/1ps",
        waves=False,
        force_compile=True,
    )
