#!/usr/bin/env python3
"""write_sdc.py — Generate <ip>/sta/out/<ip>.sdc from SSOT yaml.

Python port of write_sdc.sh; a 1:1 translation of its embedded python heredoc,
including the byte-exact SDC text (box-drawing separators, spacing, trailing
newline). The IP-name argument fallback and the early "missing SSOT" guard are
ported from the bash wrapper.

Usage: write_sdc.py <ip_name>
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


def _emit(ip: str, ssot_path: str, sdc_path: str) -> int:
    text = Path(ssot_path).read_text(encoding="utf-8", errors="replace")

    try:
        import yaml as _yaml  # type: ignore

        data = _yaml.safe_load(text) or {}
    except Exception:
        data = {}

    def _g(k, default=None):
        v = data.get(k)
        return v if v is not None else default

    def _period_ns(clock):
        value = clock.get("period_ns") or clock.get("period")
        if value not in (None, ""):
            return float(value)
        freq = clock.get("frequency_mhz") or clock.get("freq_mhz")
        if freq not in (None, ""):
            return 1000.0 / max(float(freq), 0.001)
        return 10.0

    def _derive_clocks():
        clocks = _g("clocks", []) or []
        if isinstance(clocks, list) and clocks:
            return clocks

        timing = _g("timing", {}) or {}
        target_clocks = timing.get("target_clocks") if isinstance(timing, dict) else []
        derived = []
        for item in target_clocks or []:
            if not isinstance(item, dict):
                continue
            name = item.get("name") or item.get("clock") or "clk"
            derived.append(
                {
                    **item,
                    "name": name,
                    "period_ns": _period_ns(item),
                    "source_port": item.get("source_port") or item.get("port") or name,
                }
            )
        if derived:
            return derived

        io = _g("io_list", {}) or {}
        for dom in (io.get("clock_domains") if isinstance(io, dict) else []) or []:
            if not isinstance(dom, dict):
                continue
            name = dom.get("name") or "clk"
            ports = dom.get("ports") if isinstance(dom.get("ports"), list) else []
            if ports and isinstance(ports[0], dict) and ports[0].get("name"):
                name = ports[0]["name"]
            freq = dom.get("frequency_mhz") or 100
            derived.append(
                {
                    "name": name,
                    "source_port": name,
                    "period_ns": 1000.0 / max(float(freq), 0.001),
                }
            )
        return derived

    def _derive_resets():
        resets = _g("resets", []) or []
        if isinstance(resets, list) and resets:
            return resets

        io = _g("io_list", {}) or {}
        derived = []
        for item in (io.get("resets") if isinstance(io, dict) else []) or []:
            if not isinstance(item, dict):
                continue
            name = item.get("name") or "rst_n"
            ports = item.get("ports") if isinstance(item.get("ports"), list) else []
            if ports and isinstance(ports[0], dict) and ports[0].get("name"):
                name = ports[0]["name"]
            sync_async = item.get("sync_async") or item.get("type") or "async"
            derived.append(
                {**item, "name": name, "source_port": name, "sync_async": sync_async}
            )
        return derived

    _t = _g("top_module")
    if isinstance(_t, dict):
        _t = _t.get("name")
    top = _t or _g("top") or ip
    clocks = _derive_clocks()
    resets = _derive_resets()
    fpaths = _g("false_paths", []) or []
    mcyc = _g("multicycle_paths", []) or []
    io_dly = _g("io_delay", {}) or {}
    in_pct = float(io_dly.get("input_pct", 0.20))
    out_pct = float(io_dly.get("output_pct", 0.20))

    if not clocks:
        print(
            "[STA] SSOT clocks[] is empty — STA will be meaningless. Aborting.",
            file=sys.stderr,
        )
        return 7

    lines = [
        "# Generated by workflow/sta/scripts/write_sdc.sh",
        f"# IP: {ip}   top: {top}",
        "",
        "# ── Clocks ───────────────────────────────────────────────────",
    ]
    for c in clocks:
        name = c.get("name") or "clk"
        period = _period_ns(c)
        src = c.get("source_port") or c.get("port") or name
        lines.append(
            f"create_clock -name {name} -period {float(period)} [get_ports {src}]"
        )

    lines += ["", "# ── I/O delays (conservative defaults) ────────────────────"]
    for c in clocks:
        name = c.get("name") or "clk"
        period = _period_ns(c)
        in_d = period * in_pct
        out_d = period * out_pct
        lines.append(
            f"set_input_delay  -clock {name} {in_d:.3f} [all_inputs -no_clocks]"
        )
        lines.append(f"set_output_delay -clock {name} {out_d:.3f} [all_outputs]")

    if resets:
        lines += ["", "# ── Async resets (false paths from reset ports) ───────────"]
        for r in resets:
            if str(r.get("sync_async", "")).startswith("async"):
                port = r.get("source_port") or r.get("name")
                if port:
                    lines.append(f"set_false_path -from [get_ports {port}]")

    if fpaths:
        lines += ["", "# ── False paths ──────────────────────────────────────────"]
        for fp in fpaths:
            frm = fp.get("from")
            to = fp.get("to")
            cmd = "set_false_path"
            if frm:
                cmd += f" -from [get_ports {frm}]"
            if to:
                cmd += f" -to [get_ports {to}]"
            lines.append(cmd)

    if mcyc:
        lines += ["", "# ── Multicycle paths ─────────────────────────────────────"]
        for mc in mcyc:
            cycles = int(mc.get("cycles") or 2)
            kind = mc.get("kind", "setup")
            frm = mc.get("from")
            to = mc.get("to")
            cmd = f"set_multicycle_path {cycles} -{kind}"
            if frm:
                cmd += f" -from [get_ports {frm}]"
            if to:
                cmd += f" -to [get_ports {to}]"
            lines.append(cmd)

    lines.append("")
    Path(sdc_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"[STA] wrote {sdc_path} ({len(clocks)} clocks)")
    return 0


def main(argv: list[str]) -> int:
    if not argv and os.environ.get("HOOK_CMD_ARGS"):
        argv = os.environ["HOOK_CMD_ARGS"].split()

    ip = argv[0] if argv else ""
    if not ip:
        print("[STA] usage: write_sdc.py <ip_name>", file=sys.stderr)
        return 2

    ssot = f"{ip}/yaml/{ip}.ssot.yaml"
    sdc = f"{ip}/sta/out/{ip}.sdc"
    Path(f"{ip}/sta/out").mkdir(parents=True, exist_ok=True)
    if not Path(ssot).is_file():
        print(f"[STA] missing SSOT: {ssot}", file=sys.stderr)
        return 2

    return _emit(ip, ssot, sdc)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
