#!/usr/bin/env bash
# write_sdc.sh — Generate <ip>/sta/out/<ip>.sdc from SSOT yaml.
# Args: <ip_name>
set -uo pipefail

if [ $# -eq 0 ] && [ -n "${HOOK_CMD_ARGS:-}" ]; then
  # shellcheck disable=SC2086
  set -- ${HOOK_CMD_ARGS}
fi

IP="${1:-}"
if [ -z "${IP}" ]; then echo "[STA] usage: write_sdc.sh <ip_name>" >&2; exit 2; fi
SSOT="${IP}/yaml/${IP}.ssot.yaml"
SDC="${IP}/sta/out/${IP}.sdc"
mkdir -p "${IP}/sta/out"
if [ ! -f "${SSOT}" ]; then echo "[STA] missing SSOT: ${SSOT}" >&2; exit 2; fi

python3 - "${IP}" "${SSOT}" "${SDC}" <<'PY'
import sys, pathlib, re

ip, ssot_path, sdc_path = sys.argv[1:4]
text = pathlib.Path(ssot_path).read_text()

# Lightweight YAML extraction — avoids hard yaml dep. Handles the canonical
# 20-section SSOT shape: top-level mappings, list-of-mappings under clocks/
# resets/false_paths/multicycle_paths.
try:
    import yaml as _yaml
    data = _yaml.safe_load(text) or {}
except Exception:
    data = {}

def _g(k, default=None):
    v = data.get(k)
    return v if v is not None else default

# top_module may be a nested dict (20-section SSOT) or a string. Handle both.
_t = _g("top_module")
if isinstance(_t, dict): _t = _t.get("name")
top = _t or _g("top") or ip
clocks = _g("clocks", []) or []
resets = _g("resets", []) or []
fpaths = _g("false_paths", []) or []
mcyc   = _g("multicycle_paths", []) or []
io_dly = _g("io_delay", {}) or {}
in_pct  = float(io_dly.get("input_pct", 0.20))
out_pct = float(io_dly.get("output_pct", 0.20))

if not clocks:
    print("[STA] SSOT clocks[] is empty — STA will be meaningless. Aborting.", file=sys.stderr)
    sys.exit(7)

lines = [
    f"# Generated by workflow/sta/scripts/write_sdc.sh",
    f"# IP: {ip}   top: {top}",
    "",
    "# ── Clocks ───────────────────────────────────────────────────",
]
for c in clocks:
    name = c.get("name") or "clk"
    period = c.get("period_ns") or c.get("period") or 10.0
    src    = c.get("source_port") or c.get("port") or name
    lines.append(f"create_clock -name {name} -period {float(period)} [get_ports {src}]")

lines += ["", "# ── I/O delays (conservative defaults) ────────────────────"]
# `[all_inputs -no_clocks]` excludes clock-source ports — OpenSTA otherwise
# rejects set_input_delay on a port that already defines a clock.
for c in clocks:
    name   = c.get("name") or "clk"
    period = float(c.get("period_ns") or c.get("period") or 10.0)
    in_d   = period * in_pct
    out_d  = period * out_pct
    lines.append(f"set_input_delay  -clock {name} {in_d:.3f} [all_inputs -no_clocks]")
    lines.append(f"set_output_delay -clock {name} {out_d:.3f} [all_outputs]")

if resets:
    lines += ["", "# ── Async resets (false paths from reset ports) ───────────"]
    for r in resets:
        if str(r.get("sync_async","")).startswith("async"):
            port = r.get("source_port") or r.get("name")
            if port:
                lines.append(f"set_false_path -from [get_ports {port}]")

if fpaths:
    lines += ["", "# ── False paths ──────────────────────────────────────────"]
    for fp in fpaths:
        frm = fp.get("from"); to = fp.get("to")
        cmd = "set_false_path"
        if frm: cmd += f" -from [get_ports {frm}]"
        if to:  cmd += f" -to [get_ports {to}]"
        lines.append(cmd)

if mcyc:
    lines += ["", "# ── Multicycle paths ─────────────────────────────────────"]
    for mc in mcyc:
        cycles = int(mc.get("cycles") or 2)
        kind   = mc.get("kind", "setup")
        frm    = mc.get("from"); to = mc.get("to")
        cmd = f"set_multicycle_path {cycles} -{kind}"
        if frm: cmd += f" -from [get_ports {frm}]"
        if to:  cmd += f" -to [get_ports {to}]"
        lines.append(cmd)

lines.append("")
pathlib.Path(sdc_path).write_text("\n".join(lines))
print(f"[STA] wrote {sdc_path} ({len(clocks)} clocks)")
PY
